import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import {
  absolutePrefixes,
  EngineError,
  hashJson,
  runEngineTool,
  toolVersion,
  toPosix,
  type Engine,
  type EngineAvailability,
  type EngineConfigHandle,
  type EngineRuleSelection,
  type FileBatch,
  type RawDiagnostic,
  type RunContext,
} from '@misaon/slop-gate-core'
import { parseActionlintOutput, readActionlintErrors } from './parse.ts'
import { ACTIONLINT_PATH_ENV, resolveActionlintBinary, type ActionlintResolution } from './resolve-binary.ts'

export {
  ACTIONLINT_ASSETS,
  ACTIONLINT_CHECKSUMS,
  ACTIONLINT_RELEASE_URL,
  ACTIONLINT_VERSION,
  actionlintAsset,
} from './release.ts'
export { ActionlintInstallError, extractTarGzEntry, installActionlint, type InstallActionlintResult } from './install.ts'
export { parseActionlintOutput, rangeFromLineColumn, readActionlintErrors, sanitize, type ActionlintError } from './parse.ts'
export {
  ACTIONLINT_RULES,
  ACTIONLINT_RULE_IDS,
  DISABLED_INTEGRATION_RULES,
  MESSAGE_EXCLUSIONS,
  MESSAGE_REWRITES,
  conceptForEngineRuleId,
  type ActionlintRuleId,
} from './rules.ts'
export {
  ACTIONLINT_PATH_ENV,
  CACHE_DIR_ENV,
  actionlintBinaryName,
  actionlintCacheDir,
  resolveActionlintBinary,
  type ActionlintResolution,
  type ActionlintSource,
} from './resolve-binary.ts'

const MAX_FINDINGS_EXIT_CODE = 1

export function createActionlintEngine(options: { binaryPath?: string } = {}): Engine {
  const selections = new Map<string, ReadonlySet<string>>()

  const resolution = (): ActionlintResolution | undefined =>
    options.binaryPath === undefined ? resolveActionlintBinary() : { command: options.binaryPath, source: 'env' }

  const required = (): ActionlintResolution => {
    const resolved = resolution()
    if (resolved === undefined) throw new EngineError('actionlint', unavailableReason())
    return resolved
  }

  return {
    id: 'actionlint',

    capabilities: {
      languages: ['github-workflow'],
      granularity: 'file',
      provides: [],
      fixes: false,
    },

    async availability(): Promise<EngineAvailability> {
      const resolved = resolution()
      if (resolved !== undefined) return { available: true }
      return { available: false, reason: unavailableReason(), install: 'sgate engines install actionlint' }
    },

    async version(cache) {
      return toolVersion({ command: required().command, prefixArgs: [] }, undefined, cache)
    },

    async materializeConfig(selection: EngineRuleSelection, context: RunContext) {
      const enabled = [...selection].filter(([, [level]]) => level !== 'off')
      const rulesetHash = hashJson(enabled.map(([rule, [level]]) => [rule, level]).sort())
      const path = join(context.tmpDir, `actionlint.${rulesetHash.slice(0, 12)}.yaml`)
      selections.set(path, new Set(enabled.map(([rule]) => rule)))
      await mkdir(context.tmpDir, { recursive: true })
      await writeFile(
        path,
        ['# Generated by slop-gate. Do not edit; it is deleted when the run ends.', 'self-hosted-runner:', '  labels: []', ''].join(
          '\n',
        ),
        'utf8',
      )
      return {
        path,
        rulesetHash,
        async dispose() {
          selections.delete(path)
        },
      } satisfies EngineConfigHandle
    },

    run(batch: FileBatch, handle: EngineConfigHandle, context: RunContext, signal: AbortSignal) {
      return execute(required(), batch, handle, context, signal, selections.get(handle.path) ?? new Set())
    },
  }
}

function unavailableReason(): string {
  return `actionlint was not found on PATH, in the slop-gate cache, or at ${ACTIONLINT_PATH_ENV}`
}

async function* execute(
  invocation: ActionlintResolution,
  batch: FileBatch,
  handle: EngineConfigHandle,
  context: RunContext,
  signal: AbortSignal,
  selected: ReadonlySet<string>,
): AsyncIterable<RawDiagnostic> {
  if (batch.files.length === 0) return

  const args = [
    '-shellcheck=',
    '-pyflakes=',
    '-no-color',
    '-config-file',
    handle.path,
    '-format',
    '{{json .}}',
    ...batch.files.map((file) => file.path),
  ]

  const { stdout } = await runEngineTool({
    engine: 'actionlint',
    command: invocation.command,
    args,
    cwd: context.rootDir,
    signal,
    maxFindingsExitCode: MAX_FINDINGS_EXIT_CODE,
  })

  const errors = readActionlintErrors(stdout)

  const sources = new Map<string, string | undefined>()
  for (const error of errors) {
    const file = toPosix(error.filepath)
    if (file === '' || sources.has(file)) continue
    try {
      sources.set(file, await readFile(join(context.rootDir, file), 'utf8'))
    } catch {
      sources.set(file, undefined)
    }
  }

  yield* parseActionlintOutput(errors, {
    absolutePrefixes: await absolutePrefixes(context),
    enabled: (rule) => selected.has(rule),
    readSource: (file) => sources.get(file),
  })
}
