import { readdirSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { defineConfig } from 'vitest/config'

/**
 * Every workspace package, aliased to its `src/index.ts`.
 *
 * Without this, a cross-package import resolves through the package's `exports` map to `dist/index.js`,
 * so `pnpm test` silently tests the *previous* build of every dependency — a correctness bug in the
 * suite, not a slow-workflow complaint, and it has bitten in both directions (recorded in
 * docs/superpowers/specs/2026-07-31-m0-followups.md). Generated by scanning `packages/` rather than
 * written out as a literal map, because a newly added package nothing has linked yet resolves to nothing
 * at all, and the resulting failure names neither the package nor the cause.
 *
 * **What still proves the build works.** Aliasing means no in-process test exercises `dist`, so the
 * guarantee has to be named. Three suites spawn a real child process, which resolves against real
 * `node_modules` and cannot see this alias: packages/cli/src/main.test.ts,
 * packages/cli/src/commands/mcp/e2e.test.ts and packages/core/src/registry/entries.generated.test.ts.
 * With every `dist` deleted, 28 tests across exactly those three fail and the rest pass; deleting only
 * `packages/engine-schema/dist` fails them too, so the cover is per-package. **Weakening any of the three
 * to an in-process import would leave the suite unable to tell a working build from no build at all.**
 *
 * Not covered either way: a build that succeeds and emits subtly wrong output on a path no spawned
 * process walks. `pnpm build` runs first in CI and `pnpm typecheck` rebuilds through turbo's
 * `dependsOn: ["^build"]`, which is what stands behind that case.
 */
const workspaceAlias = Object.fromEntries(
  readdirSync('packages', { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => {
      const manifest = JSON.parse(readFileSync(resolve('packages', entry.name, 'package.json'), 'utf8')) as {
        name: string
      }
      return [manifest.name, resolve('packages', entry.name, 'src/index.ts')]
    }),
)

export default defineConfig({
  resolve: { alias: workspaceAlias },
  test: {
    include: ['packages/*/src/**/*.test.ts'],
    environment: 'node',
  },
})
