import { readdirSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { defineConfig } from 'vitest/config'

/**
 * Every workspace package, aliased to its `src/index.ts`.
 *
 * Without this, a cross-package import resolves through the package's `exports` map to
 * `dist/index.js`, so `pnpm test` silently tests the *previous* build of every dependency. That is
 * not a slow-workflow complaint, it is a correctness bug in the suite, and it has produced failures
 * in both directions: three CLI-level tests once kept passing against a stale build for several
 * edits (recorded in docs/superpowers/specs/2026-07-31-m0-followups.md), and a branch switch that
 * left `dist` behind produces a wall of red that reads like a semantic conflict between branches
 * rather than a missing `pnpm build`.
 *
 * Generated by scanning `packages/`, not written out as a literal map, for the sharper half of the
 * same problem: a newly added package that nothing has linked yet resolves to nothing at all, and
 * the resulting failure names neither the package nor the cause. A scan cannot miss one.
 *
 * **What still proves the build works.** Aliasing means no in-process test exercises `dist` any
 * more, so the guarantee has to be named rather than assumed. Three suites spawn a real child
 * process, which does real Node resolution against real `node_modules` and therefore cannot see this
 * alias at all:
 *
 *   - packages/cli/src/main.test.ts — spawns `main.ts`, whose imports pull every engine's `dist`
 *     in through `cli/src/engine-registry.ts`
 *   - packages/cli/src/commands/mcp/e2e.test.ts — spawns the published `bin/sgate.js` -> `dist/main.js`
 *   - packages/core/src/registry/entries.generated.test.ts — spawns `scripts/generate-registry.ts`,
 *     which imports `@misaon/slop-gate-engine-oxlint` by name
 *
 * Measured, not assumed: with this alias in place and every package's `dist` directory deleted, 28
 * tests across exactly those three files fail and the other 1703 pass. Removing only
 * `packages/engine-schema/dist` fails them too, naming the missing module — so the cover is
 * per-package, not just core. Weakening any of those three to an in-process import would leave the
 * suite unable to tell a working build from no build at all; that is the reason they spawn.
 *
 * Not covered either way, before or after this change: a build that succeeds and emits subtly wrong
 * output on a path no spawned process walks. `pnpm build` runs first in CI (.github/workflows/ci.yml)
 * and `pnpm typecheck` rebuilds through turbo's `dependsOn: ["^build"]`, which is what stands behind
 * that case.
 */
const workspaceAlias = Object.fromEntries(
  readdirSync('packages', { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => {
      const manifest = JSON.parse(readFileSync(resolve('packages', entry.name, 'package.json'), 'utf8')) as {
        name: string
      }
      return [manifest.name, resolve('packages', entry.name, 'src/index.ts')]
    }),
)

export default defineConfig({
  resolve: { alias: workspaceAlias },
  test: {
    include: ['packages/*/src/**/*.test.ts'],
    environment: 'node',
  },
})
