import { GENERATED_RECOMMENDED_RULES } from '../registry/entries.generated.ts'
import { OPTIONED_RECOMMENDED_RULES } from './rule-options.ts'
import type { PresetName, RuleMap } from './types.ts'

const optionedRules: RuleMap = Object.fromEntries(
  Object.entries(OPTIONED_RECOMMENDED_RULES).map(([concept, rule]) => [concept, rule.setting]),
)

const slop: RuleMap = {
  'slop.as-any-cast': 'warn',
  'slop.double-cast': 'warn',
  'slop.narrative-comment': 'warn',
  'slop.stub-implementation': 'warn',
}

const recommended: RuleMap = {
  'correctness.parse-error': 'error',
  ...GENERATED_RECOMMENDED_RULES,
  ...slop,
  'types.type-error': 'error',
  'dead-code.unused-export': 'warn',
  'dead-code.unused-exported-type': 'warn',
  'deps.unlisted-dependency': 'warn',
  'deps.unresolved-import': 'error',

  'security.vulnerable-dependency': 'warn',
  'security.malicious-dependency': 'error',
  'deps.advisory-coverage-gap': 'warn',
  ...optionedRules,
  'pedantic.prefer-ts-expect-error': 'warn',
  'restriction.no-import-type-side-effects': 'warn',
  'perf.no-accumulating-spread': 'warn',

  // `perf` and `nursery` are outside the two categories the generator promotes, so these are named here
  // one by one. Each was read against its documentation; see docs/measurements.md#perf-nursery-audit.
  'perf.prefer-array-find': 'warn',
  'perf.prefer-array-flat-map': 'warn',
  'perf.prefer-set-has': 'warn',
  'perf.no-useless-call': 'warn',
  'perf.jsx-no-constructed-context-values': 'warn',
  'perf.no-object-type-as-default-prop': 'warn',
  'perf.useless-iterator-to-array': 'warn',
  'correctness.duplicate-export-name': 'error',
  'correctness.missing-named-export': 'error',
  'correctness.return-in-finally': 'error',
  'correctness.component-missing-return': 'error',
  'dead-code.useless-assignment': 'warn',

  // `pedantic` read in full: 30 of its 104 reachable rules fire here and are argued with in
  // not-recommended.ts; these are the ones that hold a defect. docs/measurements.md#pedantic-audit.
  'correctness.rules-of-hooks': 'error',
  'security.target-blank': 'warn',
  'pedantic.ban-ts-comment': 'warn',
  'pedantic.no-constructor-return': 'warn',
  'pedantic.no-self-compare': 'warn',
  'pedantic.no-throw-literal': 'warn',
  'pedantic.no-new-wrappers': 'warn',
  'pedantic.no-object-constructor': 'warn',
  'pedantic.no-array-constructor': 'warn',
  'pedantic.no-prototype-builtins': 'warn',
  'pedantic.no-case-declarations': 'warn',
  'pedantic.no-fallthrough': 'warn',
  'pedantic.no-redeclare': 'warn',
  'pedantic.radix': 'warn',
  'pedantic.array-callback-return': 'warn',
  'pedantic.no-inner-declarations': 'warn',
  'pedantic.no-useless-return': 'warn',
  'pedantic.symbol-description': 'warn',
  'pedantic.branches-sharing-code': 'warn',
  'pedantic.display-name': 'warn',
  'pedantic.checked-requires-onchange-or-readonly': 'warn',
  'pedantic.jsx-no-useless-fragment': 'warn',
  'pedantic.no-unescaped-entities': 'warn',
  'pedantic.no-unsafe-function-type': 'warn',
  'pedantic.ban-types': 'warn',
  'pedantic.prefer-enum-initializers': 'warn',
  'pedantic.new-for-builtins': 'warn',
  'pedantic.no-instanceof-array': 'warn',
  'pedantic.no-new-buffer': 'warn',
  'pedantic.no-typeof-undefined': 'warn',
  'pedantic.no-negation-in-equality-check': 'warn',
  'pedantic.no-object-as-default-parameter': 'warn',
  'pedantic.no-hex-escape': 'warn',
  'pedantic.no-unreadable-iife': 'warn',
  'pedantic.no-this-assignment': 'warn',
  'pedantic.no-static-only-class': 'warn',
  'pedantic.no-useless-switch-case': 'warn',
  'pedantic.no-unnecessary-array-flat-depth': 'warn',
  'pedantic.no-unnecessary-array-splice-count': 'warn',
  'pedantic.no-unnecessary-slice-end': 'warn',
  'pedantic.consistent-empty-array-spread': 'warn',
  'pedantic.prefer-date-now': 'warn',
  'pedantic.prefer-regexp-test': 'warn',
  'pedantic.prefer-type-error': 'warn',
  'pedantic.require-number-to-fixed-digits-argument': 'warn',
  'pedantic.prefer-array-some': 'warn',
  'pedantic.prefer-array-flat': 'warn',
  'pedantic.prefer-math-min-max': 'warn',
  'pedantic.prefer-number-coercion': 'warn',
  'pedantic.prefer-prototype-methods': 'warn',
  'pedantic.prefer-string-slice': 'warn',
  'pedantic.prefer-string-replace-all': 'warn',
  'pedantic.prefer-code-point': 'warn',
  'pedantic.prefer-blob-reading-methods': 'warn',
  'pedantic.prefer-import-meta-properties': 'warn',
  'pedantic.prefer-at': 'warn',
  'pedantic.prefer-query-selector': 'warn',
  'pedantic.prefer-dom-node-append': 'warn',
  'pedantic.prefer-dom-node-remove': 'warn',
  'pedantic.prefer-dom-node-dataset': 'warn',
  'pedantic.prefer-native-coercion-functions': 'warn',
  'pedantic.no-useless-promise-resolve-reject': 'warn',

  'restriction.no-non-null-asserted-nullish-coalescing': 'warn',

  // `restriction` is a menu upstream — 37 of its rules fire here and every one is a preference, several
  // mutually exclusive. These are the ones that restrict something for a reason, not for a house style.
  // docs/measurements.md#restriction-audit.
  'security.dangerous-html': 'warn',
  'restriction.no-proto': 'warn',
  'restriction.no-regex-spaces': 'warn',
  'restriction.no-sequences': 'warn',
  'restriction.no-implicit-globals': 'warn',
  'restriction.unicode-bom': 'warn',
  'restriction.no-amd': 'warn',
  'restriction.no-commonjs': 'warn',
  'restriction.no-dynamic-require': 'warn',
  'restriction.no-webpack-loader-syntax': 'warn',
  'restriction.no-require-imports': 'warn',
  'restriction.no-var-requires': 'warn',
  'restriction.prefer-node-protocol': 'warn',
  'restriction.no-new-require': 'warn',
  'restriction.no-path-concat': 'warn',
  'restriction.handle-callback-err': 'warn',
  'restriction.bad-bitwise-operator': 'warn',
  'restriction.no-const-enum': 'warn',
  'restriction.catch-or-return': 'warn',
  'restriction.spec-only': 'warn',
  'restriction.button-has-type': 'warn',
  'restriction.no-clone-element': 'warn',
  'restriction.no-react-children': 'warn',
  'restriction.no-empty-object-type': 'warn',
  'restriction.no-namespace': 'warn',
  'restriction.prefer-literal-enum-member': 'warn',
  'restriction.no-abusive-eslint-disable': 'warn',
  'restriction.no-document-cookie': 'warn',
  'restriction.no-length-as-slice-end': 'warn',
  'restriction.no-magic-array-flat-depth': 'warn',
  'restriction.no-useless-error-capture-stack-trace': 'warn',
  'restriction.prefer-modern-math-apis': 'warn',
  'restriction.prefer-number-properties': 'warn',
  'restriction.no-anonymous-default-export': 'warn',
  'restriction.anchor-ambiguous-text': 'warn',
  'restriction.no-alert': 'warn',
  'restriction.no-import-compiler-macros': 'warn',
  'restriction.no-multiple-slot-args': 'warn',

  // `style` read in full: 96 of its 270 reachable rules fire here and every one is formatting or house
  // preference — oxfmt owns the first and nobody owns the second. These are the rules oxlint files under
  // style that hold a defect. docs/measurements.md#style-audit.
  'security.script-url': 'warn',
  'security.jsx-script-url': 'warn',
  'security.function-constructor': 'error',
  'style.no-return-assign': 'warn',
  'style.no-multi-str': 'warn',
  'style.guard-for-in': 'warn',
  'style.default-param-last': 'warn',
  'style.default-case-last': 'warn',
  'style.prefer-promise-reject-errors': 'warn',
  'style.prefer-regex-literals': 'warn',
  'style.prefer-object-has-own': 'warn',
  'style.no-mutable-exports': 'warn',
  'style.no-exports-assign': 'warn',
  'style.no-return-wrap': 'warn',
  'style.error-message': 'warn',
  'style.throw-new-error': 'warn',
  'style.no-array-method-this-argument': 'warn',
  'style.prefer-keyboard-event-key': 'warn',
  'style.require-array-join-separator': 'warn',
  'style.consistent-date-clone': 'warn',
  'style.consistent-existence-index-check': 'warn',
  'style.no-unreadable-array-destructuring': 'warn',
  'style.explicit-timer-delay': 'warn',
  'style.prefer-array-index-of': 'warn',
  'style.prefer-includes': 'warn',
  'style.prefer-object-from-entries': 'warn',
  'style.prefer-string-trim-start-end': 'warn',
  'style.text-encoding-identifier-case': 'warn',
  'style.no-zero-fractions': 'warn',
  'style.prefer-global-this': 'warn',
  'style.prefer-modern-dom-apis': 'warn',
  'style.prefer-dom-node-text-content': 'warn',
  'style.prefer-response-static-json': 'warn',
  'style.prefer-reflect-apply': 'warn',
  'style.prefer-classlist-toggle': 'warn',
  'style.prefer-bigint-literals': 'warn',
  'style.jest-no-identical-title': 'warn',
  'style.vitest-no-identical-title': 'warn',
  'style.jest-no-duplicate-hooks': 'warn',
  'style.vitest-no-duplicate-hooks': 'warn',
  'style.no-deprecated-functions': 'warn',
  'style.no-jasmine-globals': 'warn',
  'style.no-confusing-set-timeout': 'warn',
  'style.jest-no-test-return-statement': 'warn',
  'style.vitest-no-test-return-statement': 'warn',
  'style.no-import-node-test': 'warn',
  'style.jest-no-alias-methods': 'warn',
  'style.vitest-no-alias-methods': 'warn',
  'style.jest-no-mocks-import': 'warn',
  'style.vitest-no-mocks-import': 'warn',
  'style.no-untyped-mock-factory': 'warn',
  'style.prefer-const': 'warn',
  'style.logical-assignment-operators': 'warn',
  'style.operator-assignment': 'warn',
  'style.prefer-exponentiation-operator': 'warn',
  'style.prefer-numeric-literals': 'warn',
  'style.prefer-object-spread': 'warn',
  'style.prefer-rest-params': 'warn',
  'style.eslint-prefer-spread': 'warn',
  'style.prefer-arrow-callback': 'warn',
  'style.prefer-for-of': 'warn',
  'style.no-empty-interface': 'warn',
  'style.prefer-function-type': 'warn',
  'style.adjacent-overload-signatures': 'warn',
  'style.unified-signatures': 'warn',
  'style.prefer-logical-operator-over-ternary': 'warn',
  'style.prefer-default-parameters': 'warn',
  'style.prefer-class-fields': 'warn',

  'config.compose-schema': 'error',
  'config.rule-overlap': 'info',
  'config.dead-override': 'warn',
  'config.unused-suppression': 'warn',
  'config.suppression-missing-reason': 'warn',
  'config.fix-oscillation': 'error',
  'config.workflow-call': 'warn',
  'config.workflow-condition': 'warn',
  'config.workflow-deprecated-command': 'warn',
  'config.workflow-env-var': 'warn',
  'config.workflow-event': 'warn',
  'config.workflow-expression': 'warn',
  'config.workflow-glob': 'warn',
  'config.workflow-id': 'warn',
  'config.workflow-job-needs': 'warn',
  'config.workflow-matrix': 'warn',
  'config.workflow-permissions': 'warn',
  'config.workflow-shell': 'warn',
  'security.workflow-hardcoded-credential': 'warn',
  'config.dockerfile-base-image-mutable-tag': 'warn',
  'config.dockerfile-base-image-untagged': 'warn',
  'config.dockerfile-entrypoint-form': 'warn',
  'config.dockerfile-package-cache': 'warn',
  'config.dockerfile-pipefail': 'warn',
  'config.dockerfile-platform': 'warn',
  'correctness.css-deprecated-media-type': 'warn',
  'correctness.css-duplicate-custom-property': 'warn',
  'correctness.css-duplicate-font-name': 'warn',
  'correctness.css-duplicate-import': 'warn',
  'correctness.css-duplicate-keyframe-selector': 'warn',
  'correctness.css-duplicate-property': 'warn',
  'correctness.css-import-position': 'warn',
  'correctness.css-important-in-keyframe': 'warn',
  'correctness.css-invalid-gradient-direction': 'warn',
  'correctness.css-irregular-whitespace': 'warn',
  'correctness.css-missing-var-function': 'warn',
  'correctness.css-shorthand-override': 'warn',
  'correctness.css-unknown-property': 'warn',
  'correctness.css-unknown-pseudo-class': 'warn',
  'correctness.css-unknown-pseudo-element': 'warn',
  'correctness.css-unknown-type-selector': 'warn',
  'correctness.css-unmatchable-selector': 'warn',
  'config.css-not-analysed': 'warn',
  'config.foreign-suppression': 'warn',
}

const strict: RuleMap = {
  ...recommended,
  'dead-code.unused-import': 'error',
  'dead-code.unused-variable': 'error',
  'style.no-var': 'error',
  'config.rule-overlap': 'warn',
}

const essential: RuleMap = Object.fromEntries(
  Object.entries(recommended).filter(([, setting]) => (Array.isArray(setting) ? setting[0] : setting) === 'error'),
)

export const PRESETS: Readonly<Record<PresetName, RuleMap>> = { essential, recommended, strict, slop }
