import { GENERATED_RECOMMENDED_RULES } from '../registry/entries.generated.ts'
import { OPTIONED_RECOMMENDED_RULES } from './rule-options.ts'
import type { PresetName, RuleMap } from './types.ts'

const optionedRules: RuleMap = Object.fromEntries(
  Object.entries(OPTIONED_RECOMMENDED_RULES).map(([concept, rule]) => [concept, rule.setting]),
)

const slop: RuleMap = {
  'slop.as-any-cast': 'warn',
  'slop.double-cast': 'warn',
  'slop.emoji-in-code': 'warn',
  'slop.narrative-comment': 'warn',
  'slop.stub-implementation': 'warn',
  'slop.swallowed-error': 'warn',
}

const recommended: RuleMap = {
  'correctness.parse-error': 'error',
  ...GENERATED_RECOMMENDED_RULES,
  ...slop,
  'types.type-error': 'error',
  'dead-code.unused-export': 'warn',
  'dead-code.unused-exported-type': 'warn',
  'deps.unlisted-dependency': 'warn',
  'deps.unresolved-import': 'error',

  'security.vulnerable-dependency': 'error',
  'security.malicious-dependency': 'error',
  'deps.advisory-coverage-gap': 'warn',
  ...optionedRules,
  'pedantic.prefer-ts-expect-error': 'warn',
  'restriction.no-import-type-side-effects': 'warn',
  'perf.no-accumulating-spread': 'warn',

  // `perf` and `nursery` are outside the two categories the generator promotes, so these are named here
  // one by one. Each was read against its documentation; see docs/measurements.md#perf-nursery-audit.
  'perf.prefer-array-find': 'warn',
  'perf.prefer-array-flat-map': 'warn',
  'perf.prefer-set-has': 'warn',
  'perf.no-useless-call': 'warn',
  'perf.jsx-no-constructed-context-values': 'warn',
  'perf.no-object-type-as-default-prop': 'warn',
  'perf.useless-iterator-to-array': 'warn',
  'correctness.duplicate-export-name': 'error',
  'correctness.missing-named-export': 'error',
  'correctness.return-in-finally': 'error',
  'correctness.component-missing-return': 'error',
  'dead-code.useless-assignment': 'warn',

  // `pedantic` read in full: 30 of its 104 reachable rules fire here and are argued with in
  // not-recommended.ts; these are the ones that hold a defect. docs/measurements.md#pedantic-audit.
  'correctness.rules-of-hooks': 'error',
  'security.target-blank': 'warn',
  'pedantic.ban-ts-comment': 'warn',
  'pedantic.no-constructor-return': 'warn',
  'pedantic.no-self-compare': 'warn',
  'pedantic.no-throw-literal': 'warn',
  'pedantic.no-new-wrappers': 'warn',
  'pedantic.no-object-constructor': 'warn',
  'pedantic.no-array-constructor': 'warn',
  'pedantic.no-prototype-builtins': 'warn',
  'pedantic.no-case-declarations': 'warn',
  'pedantic.no-fallthrough': 'warn',
  'pedantic.no-redeclare': 'warn',
  'pedantic.radix': 'warn',
  'pedantic.array-callback-return': 'warn',
  'pedantic.no-inner-declarations': 'warn',
  'pedantic.no-useless-return': 'warn',
  'pedantic.symbol-description': 'warn',
  'pedantic.branches-sharing-code': 'warn',
  'pedantic.display-name': 'warn',
  'pedantic.checked-requires-onchange-or-readonly': 'warn',
  'pedantic.no-unescaped-entities': 'warn',
  'pedantic.no-unsafe-function-type': 'warn',
  'pedantic.ban-types': 'warn',
  'pedantic.prefer-enum-initializers': 'warn',
  'pedantic.new-for-builtins': 'warn',
  'pedantic.no-instanceof-array': 'warn',
  'pedantic.no-new-buffer': 'warn',
  'pedantic.no-typeof-undefined': 'warn',
  'pedantic.no-negation-in-equality-check': 'warn',
  'pedantic.no-object-as-default-parameter': 'warn',
  'pedantic.no-hex-escape': 'warn',
  'pedantic.no-unreadable-iife': 'warn',
  'pedantic.no-this-assignment': 'warn',
  'pedantic.no-static-only-class': 'warn',
  'pedantic.no-useless-switch-case': 'warn',
  'pedantic.no-unnecessary-array-flat-depth': 'warn',
  'pedantic.no-unnecessary-array-splice-count': 'warn',
  'pedantic.no-unnecessary-slice-end': 'warn',
  'pedantic.consistent-empty-array-spread': 'warn',
  'pedantic.prefer-date-now': 'warn',
  'pedantic.prefer-regexp-test': 'warn',
  'pedantic.prefer-type-error': 'warn',
  'pedantic.require-number-to-fixed-digits-argument': 'warn',
  'pedantic.prefer-array-some': 'warn',
  'pedantic.prefer-array-flat': 'warn',
  'pedantic.prefer-math-min-max': 'warn',
  'pedantic.prefer-number-coercion': 'warn',
  'pedantic.prefer-prototype-methods': 'warn',
  'pedantic.prefer-string-slice': 'warn',
  'pedantic.prefer-string-replace-all': 'warn',
  'pedantic.prefer-code-point': 'warn',
  'pedantic.prefer-blob-reading-methods': 'warn',
  'pedantic.prefer-import-meta-properties': 'warn',
  'pedantic.prefer-at': 'warn',
  'pedantic.prefer-query-selector': 'warn',
  'pedantic.prefer-dom-node-remove': 'warn',
  'pedantic.prefer-dom-node-dataset': 'warn',
  'pedantic.prefer-native-coercion-functions': 'warn',
  'pedantic.no-useless-promise-resolve-reject': 'warn',

  'restriction.no-non-null-asserted-nullish-coalescing': 'warn',

  // `restriction` is a menu upstream — 37 of its rules fire here and every one is a preference, several
  // mutually exclusive. These are the ones that restrict something for a reason, not for a house style.
  // docs/measurements.md#restriction-audit.
  'security.dangerous-html': 'warn',
  'restriction.no-proto': 'warn',
  'restriction.no-regex-spaces': 'warn',
  'restriction.no-sequences': 'warn',
  'restriction.no-implicit-globals': 'warn',
  'restriction.unicode-bom': 'warn',
  'restriction.no-dynamic-require': 'warn',
  'restriction.no-webpack-loader-syntax': 'warn',
  'restriction.prefer-node-protocol': 'warn',
  'restriction.no-new-require': 'warn',
  'restriction.no-path-concat': 'warn',
  'restriction.handle-callback-err': 'warn',
  'restriction.bad-bitwise-operator': 'warn',
  'restriction.no-const-enum': 'warn',
  'restriction.catch-or-return': 'warn',
  'restriction.spec-only': 'warn',
  'restriction.button-has-type': 'warn',
  'restriction.no-clone-element': 'warn',
  'restriction.no-react-children': 'warn',
  'restriction.no-empty-object-type': 'warn',
  'restriction.no-namespace': 'warn',
  'restriction.prefer-literal-enum-member': 'warn',
  'restriction.no-abusive-eslint-disable': 'warn',
  'restriction.no-document-cookie': 'warn',
  'restriction.no-length-as-slice-end': 'warn',
  'restriction.no-magic-array-flat-depth': 'warn',
  'restriction.no-useless-error-capture-stack-trace': 'warn',
  'restriction.prefer-modern-math-apis': 'warn',
  'restriction.prefer-number-properties': 'warn',
  'restriction.no-anonymous-default-export': 'warn',
  'restriction.anchor-ambiguous-text': 'warn',
  'restriction.no-alert': 'warn',
  'restriction.no-cycle': 'error',
  'restriction.no-import-compiler-macros': 'warn',
  'restriction.no-multiple-slot-args': 'warn',

  // `style` read in full: 96 of its 270 reachable rules fire here and every one is formatting or house
  // preference — oxfmt owns the first and nobody owns the second. These are the rules oxlint files under
  // style that hold a defect. docs/measurements.md#style-audit.
  'security.script-url': 'warn',
  'security.jsx-script-url': 'warn',
  'security.function-constructor': 'error',
  'style.no-return-assign': 'warn',
  'style.no-multi-str': 'warn',
  'style.guard-for-in': 'warn',
  'style.default-param-last': 'warn',
  'style.default-case-last': 'warn',
  'style.prefer-promise-reject-errors': 'warn',
  'style.prefer-regex-literals': 'warn',
  'style.prefer-object-has-own': 'warn',
  'style.no-mutable-exports': 'warn',
  'style.no-exports-assign': 'warn',
  'style.no-return-wrap': 'warn',
  'style.error-message': 'warn',
  'style.throw-new-error': 'warn',
  'style.prefer-negative-index': 'warn',
  'style.require-typed-ref': 'warn',
  'style.custom-error-definition': 'warn',
  'style.jest-no-interpolation-in-snapshots': 'warn',
  'style.vitest-no-interpolation-in-snapshots': 'warn',
  'style.no-array-method-this-argument': 'warn',
  'style.prefer-keyboard-event-key': 'warn',
  'style.require-array-join-separator': 'warn',
  'style.consistent-date-clone': 'warn',
  'style.consistent-existence-index-check': 'warn',
  'style.no-unreadable-array-destructuring': 'warn',
  'style.explicit-timer-delay': 'warn',
  'style.prefer-array-index-of': 'warn',
  'style.prefer-includes': 'warn',
  'style.prefer-object-from-entries': 'warn',
  'style.prefer-string-trim-start-end': 'warn',
  'style.text-encoding-identifier-case': 'warn',
  'style.no-zero-fractions': 'warn',
  'style.prefer-modern-dom-apis': 'warn',
  'style.prefer-dom-node-text-content': 'warn',
  'style.prefer-response-static-json': 'warn',
  'style.prefer-reflect-apply': 'warn',
  'style.prefer-classlist-toggle': 'warn',
  'style.prefer-bigint-literals': 'warn',
  'style.jest-no-identical-title': 'warn',
  'style.vitest-no-identical-title': 'warn',
  'style.jest-no-duplicate-hooks': 'warn',
  'style.vitest-no-duplicate-hooks': 'warn',
  'style.no-deprecated-functions': 'warn',
  'style.no-jasmine-globals': 'warn',
  'style.no-confusing-set-timeout': 'warn',
  'style.jest-no-test-return-statement': 'warn',
  'style.vitest-no-test-return-statement': 'warn',
  'style.no-import-node-test': 'warn',
  'style.jest-no-alias-methods': 'warn',
  'style.vitest-no-alias-methods': 'warn',
  'style.jest-no-mocks-import': 'warn',
  'style.vitest-no-mocks-import': 'warn',
  'style.no-untyped-mock-factory': 'warn',
  'style.prefer-const': 'warn',
  'style.logical-assignment-operators': 'warn',
  'style.operator-assignment': 'warn',
  'style.prefer-exponentiation-operator': 'warn',
  'style.prefer-numeric-literals': 'warn',
  'style.prefer-object-spread': 'warn',
  'style.prefer-rest-params': 'warn',
  'style.eslint-prefer-spread': 'warn',
  'style.prefer-for-of': 'warn',
  'style.no-empty-interface': 'warn',
  'style.prefer-function-type': 'warn',
  'style.adjacent-overload-signatures': 'warn',
  'style.unified-signatures': 'warn',
  'style.prefer-logical-operator-over-ternary': 'warn',
  'style.prefer-default-parameters': 'warn',
  'style.prefer-class-fields': 'warn',

  // knip's three that an import graph can answer. The two about dependencies cannot — see
  // not-recommended.ts — and `formatting.unformatted` is a formatter, which is the project's own choice.
  'deps.unlisted-binary': 'warn',
  'dead-code.duplicate-export': 'warn',
  'dead-code.unused-enum-member': 'warn',

  // Type-aware, so they run only where `oxlint-tsgolint` is installed and are a reported coverage gap
  // otherwise — 5.7 s against 0.09 s for the same rules is why it is not a dependency.
  // docs/measurements.md#type-aware-audit.
  'correctness.await-thenable': 'error',
  'correctness.no-array-delete': 'error',
  'correctness.no-base-to-string': 'error',
  'correctness.no-duplicate-type-constituents': 'error',
  'correctness.no-floating-promises': 'error',
  'correctness.no-for-in-array': 'error',
  'correctness.no-implied-eval': 'error',
  'correctness.no-meaningless-void-operator': 'error',
  'correctness.no-redundant-type-constituents': 'error',
  'correctness.no-unsafe-unary-minus': 'error',
  'correctness.no-useless-default-assignment': 'error',
  'correctness.require-array-sort-compare': 'error',
  'correctness.restrict-template-expressions': 'error',
  'suspicious.no-unsafe-enum-comparison': 'warn',
  'suspicious.no-unnecessary-type-assertion': 'warn',
  'suspicious.no-unnecessary-boolean-literal-compare': 'warn',
  'suspicious.no-unnecessary-template-expression': 'warn',
  'suspicious.no-unnecessary-type-conversion': 'warn',
  'suspicious.no-unnecessary-type-arguments': 'warn',
  'pedantic.no-misused-promises': 'warn',
  'pedantic.only-throw-error': 'warn',
  'pedantic.switch-exhaustiveness-check': 'warn',
  'pedantic.prefer-promise-reject-errors': 'warn',
  'pedantic.no-mixed-enums': 'warn',
  'pedantic.related-getter-setter-pairs': 'warn',
  'pedantic.prefer-includes': 'warn',
  'pedantic.no-deprecated': 'warn',

  // The rest of `style`, read one at a time under a stricter bar than the first pass used: a rule goes in
  // unless it is a false positive, a threshold, a conflict, or something oxfmt owns.
  // docs/measurements.md#style-tail.
  'style.func-name-matching': 'warn',
  'style.grouped-accessor-pairs': 'warn',
  'style.first': 'warn',
  'style.no-named-default': 'warn',
  'style.jest-no-unneeded-async-expect-function': 'warn',
  'style.jest-prefer-comparison-matcher': 'warn',
  'style.jest-prefer-each': 'warn',
  'style.jest-prefer-equality-matcher': 'warn',
  'style.jest-prefer-expect-resolves': 'warn',
  'style.jest-prefer-hooks-in-order': 'warn',
  'style.jest-prefer-hooks-on-top': 'warn',
  'style.prefer-jest-mocked': 'warn',
  'style.jest-prefer-mock-promise-shorthand': 'warn',
  'style.jest-prefer-mock-return-shorthand': 'warn',
  'style.jest-prefer-spy-on': 'warn',
  'style.jest-prefer-to-contain': 'warn',
  'style.prefer-to-have-been-called': 'warn',
  'style.jest-prefer-to-have-been-called-times': 'warn',
  'style.jest-prefer-todo': 'warn',
  'style.no-extra-label': 'warn',
  'style.no-label-var': 'warn',
  'style.no-labels': 'warn',
  'style.no-lone-blocks': 'warn',
  'style.no-multi-assign': 'warn',
  'style.no-useless-computed-key': 'warn',
  'style.no-nesting': 'warn',
  'style.hook-use-state': 'warn',
  'style.jsx-boolean-value': 'warn',
  'style.jsx-curly-brace-presence': 'warn',
  'style.jsx-fragments': 'warn',
  'style.jsx-handler-names': 'warn',
  'style.jsx-pascal-case': 'warn',
  'style.no-redundant-should-component-update': 'warn',
  'style.no-set-state': 'warn',
  'style.prefer-es6-class': 'warn',
  'style.state-in-constructor': 'warn',
  'style.ban-tslint-comment': 'warn',
  'style.class-literal-property-style': 'warn',
  'style.consistent-generic-constructors': 'warn',
  'style.consistent-type-assertions': 'warn',
  'style.consistent-template-literal-escape': 'warn',
  'style.no-console-spaces': 'warn',
  'style.prefer-optional-catch-binding': 'warn',
  'style.relative-url-style': 'warn',
  'style.switch-case-break-position': 'warn',
  'style.consistent-each-for': 'warn',
  'style.consistent-test-filename': 'warn',
  'style.consistent-vitest-vi': 'warn',
  'style.vitest-no-unneeded-async-expect-function': 'warn',
  'style.prefer-called-exactly-once-with': 'warn',
  'style.prefer-called-times': 'warn',
  'style.vitest-prefer-comparison-matcher': 'warn',
  'style.vitest-prefer-hooks-in-order': 'warn',
  'style.prefer-import-in-mock': 'warn',
  'style.vitest-prefer-mock-promise-shorthand': 'warn',
  'style.vitest-prefer-spy-on': 'warn',
  'style.prefer-to-be-object': 'warn',
  'style.vitest-prefer-to-have-been-called-times': 'warn',
  'style.vitest-prefer-todo': 'warn',
  'style.component-definition-name-casing': 'warn',
  'style.define-emits-declaration': 'warn',
  'style.define-props-declaration': 'warn',
  'style.next-tick-style': 'warn',
  'style.prop-name-casing': 'warn',
  'style.require-direct-export': 'warn',
  'style.require-prop-types': 'warn',
  'style.yoda': 'warn',

  'style.empty-brace-spaces': 'warn',
  'style.no-duplicates': 'warn',
  'style.vitest-prefer-mock-return-shorthand': 'warn',
  'style.prefer-expect-type-of': 'warn',

  // The last of `style`, kept because fifty repositories say they are quiet: each is under 20 findings
  // per thousand files across the corpus. docs/measurements.md#rule-corpus.
  'restriction.no-div-regex': 'warn',
  'style.vitest-prefer-equality-matcher': 'warn',
  'style.no-useless-collection-argument': 'warn',
  'style.vitest-prefer-to-contain': 'warn',
  'style.vitest-prefer-hooks-on-top': 'warn',
  'pedantic.no-loop-func': 'warn',
  'style.jest-no-test-prefixes': 'warn',
  'style.vitest-no-test-prefixes': 'warn',
  'style.require-module-attributes': 'warn',
  'style.no-inferrable-types': 'warn',
  'style.prefer-string-raw': 'warn',

  // Everything that is not a false positive and not a collision with another rule. The bar is the
  // product's, not any one repository's: a rule that is right every time it fires belongs here even when
  // it fires often, and a project that disagrees says so in its own config.
  'style.css-descending-specificity': 'warn',
  'duplication.css-duplicate-selector': 'warn',
  'duplication.css-empty-block': 'warn',
  'style.css-hex-color': 'warn',
  'complexity.css-important': 'warn',
  'style.css-baseline': 'warn',
  'a11y.css-generic-font-name': 'warn',
  'pedantic.accessor-pairs': 'warn',
  'style.arrow-body-style': 'warn',
  'style.capitalized-comments': 'warn',
  'restriction.class-methods-use-this': 'warn',
  'restriction.complexity': 'warn',
  'style.curly': 'warn',
  'restriction.default-case': 'warn',
  'style.func-names': 'warn',
  'style.func-style': 'warn',
  'style.id-length': 'warn',
  'style.consistent-type-specifier-style': 'warn',
  'style.exports-last': 'warn',
  'style.group-exports': 'warn',
  'pedantic.max-dependencies': 'warn',
  'style.newline-after-import': 'warn',
  'restriction.no-commonjs': 'warn',
  'style.no-namespace': 'warn',
  'style.no-nodejs-modules': 'warn',
  'restriction.no-relative-parent-imports': 'warn',
  'restriction.unambiguous': 'warn',
  'style.init-declarations': 'warn',
  'style.jest-consistent-test-it': 'warn',
  'style.jest-max-expects': 'warn',
  'style.jest-max-nested-describe': 'warn',
  'pedantic.jest-no-conditional-in-test': 'warn',
  'style.jest-no-large-snapshots': 'warn',
  'style.jest-padding-around-after-all-blocks': 'warn',
  'style.jest-padding-around-test-blocks': 'warn',
  'style.jest-prefer-called-with': 'warn',
  'style.prefer-ending-with-an-expect': 'warn',
  'style.jest-prefer-expect-assertions': 'warn',
  'style.prefer-importing-jest-globals': 'warn',
  'style.jest-prefer-lowercase-title': 'warn',
  'style.jest-prefer-strict-equal': 'warn',
  'style.jest-prefer-to-be': 'warn',
  'style.jest-prefer-to-have-length': 'warn',
  'style.jest-require-top-level-describe': 'warn',
  'restriction.check-access': 'warn',
  'restriction.empty-tags': 'warn',
  'pedantic.require-param': 'warn',
  'pedantic.require-param-description': 'warn',
  'pedantic.require-param-name': 'warn',
  'pedantic.require-param-type': 'warn',
  'pedantic.require-returns': 'warn',
  'pedantic.require-returns-description': 'warn',
  'pedantic.require-returns-type': 'warn',
  'style.require-throws-description': 'warn',
  'pedantic.require-throws-type': 'warn',
  'pedantic.require-yields-type': 'warn',
  'pedantic.max-classes-per-file': 'warn',
  'pedantic.max-depth': 'warn',
  'pedantic.max-lines': 'warn',
  'pedantic.max-lines-per-function': 'warn',
  'style.max-params': 'warn',
  'style.max-statements': 'warn',
  'style.new-cap': 'warn',
  'perf.no-await-in-loop': 'warn',
  'restriction.no-bitwise': 'warn',
  'restriction.no-console': 'warn',
  'style.no-continue': 'warn',
  'style.no-duplicate-imports': 'warn',
  'pedantic.no-else-return': 'warn',
  'restriction.no-empty': 'warn',
  'restriction.no-empty-function': 'warn',
  'restriction.no-eq-null': 'warn',
  'style.no-implicit-coercion': 'warn',
  'pedantic.no-inline-comments': 'warn',
  'pedantic.eslint-no-lonely-if': 'warn',
  'style.no-magic-numbers': 'warn',
  'pedantic.eslint-no-negated-condition': 'warn',
  'style.eslint-no-nested-ternary': 'warn',
  'restriction.no-param-reassign': 'warn',
  'restriction.no-plusplus': 'warn',
  'pedantic.no-promise-executor-return': 'warn',
  'restriction.no-use-before-define': 'warn',
  'style.no-var': 'warn',
  'restriction.no-void': 'warn',
  'pedantic.no-warning-comments': 'warn',
  'style.exports-style': 'warn',
  'style.global-require': 'warn',
  'style.no-mixed-requires': 'warn',
  'restriction.no-process-env': 'warn',
  'style.no-sync': 'warn',
  'restriction.no-top-level-await': 'warn',
  'style.object-shorthand': 'warn',
  'restriction.no-barrel-file': 'warn',
  'style.prefer-arrow-callback': 'warn',
  'style.prefer-destructuring': 'warn',
  'style.prefer-named-capture-group': 'warn',
  'style.prefer-template': 'warn',
  'style.avoid-new': 'warn',
  'style.param-names': 'warn',
  'style.prefer-await-to-callbacks': 'warn',
  'style.prefer-await-to-then': 'warn',
  'perf.jsx-no-jsx-as-prop': 'warn',
  'perf.jsx-no-new-array-as-prop': 'warn',
  'perf.jsx-no-new-function-as-prop': 'warn',
  'perf.jsx-no-new-object-as-prop': 'warn',
  'restriction.forbid-component-props': 'warn',
  'style.function-component-definition': 'warn',
  'restriction.jsx-filename-extension': 'warn',
  'style.jsx-max-depth': 'warn',
  'restriction.jsx-no-literals': 'warn',
  'pedantic.jsx-no-useless-fragment': 'warn',
  'style.jsx-props-no-spreading': 'warn',
  'correctness.jsx-key-index': 'warn',
  'restriction.no-multi-comp': 'warn',
  'restriction.only-export-components': 'warn',
  'restriction.prefer-function-component': 'warn',
  'nursery.react-compiler': 'warn',
  'style.self-closing-comp': 'warn',
  'pedantic.eslint-require-await': 'warn',
  'pedantic.require-unicode-regexp': 'warn',
  'style.sort-imports': 'warn',
  'style.sort-keys': 'warn',
  'pedantic.sort-vars': 'warn',
  'style.array-type': 'warn',
  'style.consistent-indexed-object-style': 'warn',
  'style.consistent-type-definitions': 'warn',
  'style.consistent-type-imports': 'warn',
  'restriction.explicit-function-return-type': 'warn',
  'restriction.explicit-member-accessibility': 'warn',
  'restriction.explicit-module-boundary-types': 'warn',
  'style.method-signature-style': 'warn',
  'restriction.no-dynamic-delete': 'warn',
  'restriction.no-invalid-void-type': 'warn',
  'restriction.no-non-null-assertion': 'warn',
  'restriction.no-require-imports': 'warn',
  'restriction.no-var-requires': 'warn',
  'style.parameter-properties': 'warn',
  'pedantic.consistent-assert': 'warn',
  'pedantic.escape-case': 'warn',
  'pedantic.explicit-length-check': 'warn',
  'style.filename-case': 'warn',
  'restriction.import-style': 'warn',
  'style.max-nested-calls': 'warn',
  'pedantic.no-array-callback-reference': 'warn',
  'restriction.no-array-for-each': 'warn',
  'restriction.no-array-reduce': 'warn',
  'style.no-await-expression-member': 'warn',
  'pedantic.no-immediate-mutation': 'warn',
  'pedantic.unicorn-no-lonely-if': 'warn',
  'pedantic.unicorn-no-negated-condition': 'warn',
  'style.unicorn-no-nested-ternary': 'warn',
  'style.no-null': 'warn',
  'restriction.no-process-exit': 'warn',
  'pedantic.no-useless-undefined': 'warn',
  'style.number-literal-case': 'warn',
  'style.numeric-separators-style': 'warn',
  'pedantic.prefer-dom-node-append': 'warn',
  'pedantic.prefer-event-target': 'warn',
  'style.prefer-export-from': 'warn',
  'style.prefer-global-this': 'warn',
  'restriction.prefer-module': 'warn',
  'pedantic.prefer-single-call': 'warn',
  'style.prefer-ternary': 'warn',
  'pedantic.prefer-top-level-await': 'warn',
  'style.switch-case-braces': 'warn',
  'style.vars-on-top': 'warn',
  'style.vitest-consistent-test-it': 'warn',
  'style.vitest-max-expects': 'warn',
  'style.vitest-max-nested-describe': 'warn',
  'pedantic.vitest-no-conditional-in-test': 'warn',
  'style.vitest-no-large-snapshots': 'warn',
  'style.vitest-padding-around-after-all-blocks': 'warn',
  'style.vitest-padding-around-test-blocks': 'warn',
  'style.prefer-called-once': 'warn',
  'style.vitest-prefer-called-with': 'warn',
  'style.vitest-prefer-expect-assertions': 'warn',
  'style.vitest-prefer-expect-resolves': 'warn',
  'style.prefer-importing-vitest-globals': 'warn',
  'style.vitest-prefer-lowercase-title': 'warn',
  'style.vitest-prefer-strict-equal': 'warn',
  'style.vitest-prefer-to-be': 'warn',
  'style.vitest-prefer-to-have-length': 'warn',
  'restriction.require-test-timeout': 'warn',
  'style.vitest-require-top-level-describe': 'warn',
  'style.define-props-destructuring': 'warn',
  'restriction.max-props': 'warn',
  'style.require-default-prop': 'warn',

  // Type-aware, and re-decided on the same bar as everything else. These were held out for being
  // traceable to `JSON.parse`, or for being silent on one repository — neither of which says a finding
  // is wrong. `pedantic.return-await` sits in `rule-options.ts`, which is where its option lives.
  'pedantic.no-unsafe-assignment': 'warn',
  'pedantic.no-unsafe-call': 'warn',
  'pedantic.no-unsafe-argument': 'warn',
  'pedantic.no-unsafe-return': 'warn',
  'pedantic.no-unsafe-member-access': 'warn',
  'suspicious.no-unsafe-type-assertion': 'warn',
  'style.consistent-type-exports': 'warn',
  'style.no-unnecessary-qualifier': 'warn',
  'style.prefer-readonly': 'warn',
  'style.prefer-reduce-type-parameter': 'warn',
  'style.prefer-regexp-exec': 'warn',
  'style.prefer-return-this-type': 'warn',
  'style.prefer-string-starts-ends-with': 'warn',
  'pedantic.prefer-readonly-parameter-types': 'warn',
  'pedantic.strict-boolean-expressions': 'warn',
  'pedantic.restrict-plus-operands': 'warn',
  'restriction.promise-function-async': 'warn',
  'pedantic.strict-void-return': 'warn',
  'pedantic.no-confusing-void-expression': 'warn',

  // biome's CSS rules, re-decided on the same bar. These three were held out for being accurate but
  // unactionable, or for measuring a threshold slop-gate had no policy on — it has one now.
  'suspicious.css-empty-source': 'warn',
  'style.css-value-at-rule': 'warn',
  'pedantic.css-max-lines': 'warn',

  // knip's pnpm-catalog pair. Both were held out as unmeasured for want of a catalog-using repository;
  // this one is, and an authored fixture puts a finding on each.
  'dead-code.unused-catalog-entry': 'warn',
  'deps.unresolved-catalog-reference': 'error',

  // hadolint ships 72 rules and slop-gate had looked at 20. These are the ones whose behaviour an
  // authored Dockerfile reproduces; the rest are in `not-recommended.ts` with what stopped them.
  'config.dockerfile-absolute-workdir': 'warn',
  'config.dockerfile-pointless-command': 'warn',
  'config.dockerfile-last-user-root': 'warn',
  'config.dockerfile-sudo': 'warn',
  'config.dockerfile-add-archive': 'warn',
  'config.dockerfile-invalid-port': 'warn',
  'config.dockerfile-multiple-healthcheck': 'warn',
  'config.dockerfile-apt-get-yes': 'warn',
  'config.dockerfile-pin-npm': 'warn',
  'config.dockerfile-copy-multiple-targets': 'warn',
  'config.dockerfile-copy-from-unknown-stage': 'warn',
  'config.dockerfile-copy-from-self': 'warn',
  'config.dockerfile-duplicate-stage-name': 'warn',
  'config.dockerfile-apt-not-apt-get': 'warn',
  'config.dockerfile-pin-gem': 'warn',
  'config.dockerfile-yum-yes': 'warn',
  'config.dockerfile-zypper-yes': 'warn',
  'config.dockerfile-zypper-dist-upgrade': 'warn',
  'config.dockerfile-dnf-yes': 'warn',
  'config.dockerfile-onbuild-onbuild': 'warn',
  'config.dockerfile-env-self-reference': 'warn',
  'config.dockerfile-invalid-label-key': 'warn',
  'config.dockerfile-missing-healthcheck': 'warn',
  'config.dockerfile-instruction-order': 'warn',
  'config.dockerfile-pin-go': 'warn',
  'config.dockerfile-reserved-stage-name': 'warn',
  'config.dockerfile-redundant-platform': 'warn',
  'config.dockerfile-copy-whole-filesystem': 'warn',
  'config.dockerfile-maintainer-deprecated': 'warn',
  'config.dockerfile-multiple-cmd': 'warn',
  'config.dockerfile-multiple-entrypoint': 'warn',
  'config.dockerfile-shell-via-symlink': 'warn',

  'config.compose-schema': 'error',
  'config.rule-overlap': 'info',
  'config.dead-override': 'warn',
  'config.unused-suppression': 'warn',
  'config.suppression-missing-reason': 'warn',
  'config.fix-oscillation': 'error',
  'config.workflow-call': 'warn',
  'config.workflow-condition': 'warn',
  'config.workflow-deprecated-command': 'warn',
  'config.workflow-env-var': 'warn',
  'config.workflow-event': 'warn',
  'config.workflow-expression': 'warn',
  'config.workflow-glob': 'warn',
  'config.workflow-id': 'warn',
  'config.workflow-job-needs': 'warn',
  'config.workflow-matrix': 'warn',
  'config.workflow-permissions': 'warn',
  'config.workflow-shell': 'warn',
  'security.workflow-hardcoded-credential': 'error',
  'config.dockerfile-base-image-mutable-tag': 'warn',
  'config.dockerfile-base-image-untagged': 'warn',
  'config.dockerfile-entrypoint-form': 'warn',
  'config.dockerfile-package-cache': 'warn',
  'config.dockerfile-pipefail': 'warn',
  'config.dockerfile-platform': 'warn',
  'correctness.css-deprecated-media-type': 'warn',
  'correctness.css-duplicate-custom-property': 'warn',
  'correctness.css-duplicate-font-name': 'warn',
  'correctness.css-duplicate-import': 'warn',
  'correctness.css-duplicate-keyframe-selector': 'warn',
  'correctness.css-duplicate-property': 'warn',
  'correctness.css-import-position': 'warn',
  'correctness.css-important-in-keyframe': 'warn',
  'correctness.css-invalid-gradient-direction': 'warn',
  'correctness.css-irregular-whitespace': 'warn',
  'correctness.css-missing-var-function': 'warn',
  'correctness.css-shorthand-override': 'warn',
  'correctness.css-unknown-property': 'warn',
  'correctness.css-unknown-pseudo-class': 'warn',
  'correctness.css-unknown-pseudo-element': 'warn',
  'correctness.css-unknown-type-selector': 'warn',
  'correctness.css-unmatchable-selector': 'warn',
  'config.css-not-analysed': 'warn',
  'config.foreign-suppression': 'warn',
}

const strict: RuleMap = {
  ...recommended,
  'dead-code.unused-import': 'error',
  'dead-code.unused-variable': 'error',
  'style.no-var': 'error',
  'config.rule-overlap': 'warn',
}

const essential: RuleMap = Object.fromEntries(
  Object.entries(recommended).filter(([, setting]) => (Array.isArray(setting) ? setting[0] : setting) === 'error'),
)

export const PRESETS: Readonly<Record<PresetName, RuleMap>> = { essential, recommended, strict, slop }
