import { expect, test } from 'vitest'
import { isGeneratedPath, isGeneratedSource } from './detect-generated.ts'

test.each([
  'packages/bat-api/src/v1/client/client.gen.ts',
  'packages/loan-api/src/v2/client/types.gen.ts',
  'src/core/queryKeySerializer.gen.ts',
  'src/schema.generated.ts',
  'src/api/__generated__/operations.ts',
  'proto/service.gen.go',
])('treats %s as generated', (path) => {
  expect(isGeneratedPath(path)).toBe(true)
})

test.each([
  'apps/app-acquisition/src/types/nextAuth.d.ts',
  'apps/app-client-zone/src/types/global.d.ts',
  'packages/theme/src/muiTheme/palette.d.ts',
  'src/generator.ts',
  'src/regenerate.ts',
  'src/gen.ts',
  'src/generated.ts',
  'docs/generated-output.md',
])('leaves %s alone', (path) => {
  expect(isGeneratedPath(path)).toBe(false)
})

test('a declaration file that also carries a marker is still generated', () => {
  expect(isGeneratedPath('src/client/types.gen.d.ts')).toBe(true)
})

test.each([
  '// This file is autogenerated by build/build-validation.js, do not edit\n"use strict";\n',
  '/**\n * @generated by protoc-gen-es v1.7.2\n */\nexport const x = 1\n',
  '/* eslint-disable */\n// Code generated by tsoa. DO NOT EDIT.\nexport {}\n',
  '\n#!/usr/bin/env node\n# AUTO-GENERATED FILE — DO NOT MODIFY\n',
  '<!-- Generated by openapi-typescript. Do not edit. -->\n',
])('reads the header of %j as a generated marker', (source) => {
  expect(isGeneratedSource(source)).toBe(true)
})

test.each([
  'export function generate() {}\n',
  '// A generator lives here.\nexport const x = 1\n',
  '// Do not edit this by hand without reading CONTRIBUTING.\nexport const x = 1\n',
  '{\n  "name": "pkg"\n}\n',
  'const a = 1\nconst b = 2\nconst c = 3\nconst d = 4\nconst e = 5\n// @generated\n',
])('leaves %j alone', (source) => {
  expect(isGeneratedSource(source)).toBe(false)
})

test('a marker below the header window does not count', () => {
  const source = `${'// preamble\n'.repeat(6)}// @generated\n`
  expect(isGeneratedSource(source)).toBe(false)
})
