import type { RuleEntry } from './types.ts'

const OXLINT_DOCS = 'https://oxc.rs/docs/guide/usage/linter/rules'

export const RULE_ENTRIES = [
  {
    engine: 'oxlint',
    // Synthetic: not a real `--rules`-listed oxlint rule, but the id oxlint's own adapter assigns
    // a parse failure (see packages/engine-oxlint/src/parse.ts) so it can flow through the same
    // ownership/severity/caching pipeline as every other finding. It must never reach oxlint's own
    // `--config` (parsing isn't a rule that can be toggled, and oxlint's config parser hard-rejects
    // an unrecognised rule id) — `materializeOxlintConfig` filters it out before writing rules.
    engineRuleId: 'parse-error',
    concepts: ['correctness.parse-error'],
    tier: 0,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: 'https://oxc.rs/docs/guide/usage/linter.html',
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'no-debugger',
    concepts: ['correctness.no-debugger'],
    tier: 0,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'safe',
    fixTouches: ['statements'],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/no-debugger.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'no-dupe-keys',
    concepts: ['correctness.no-duplicate-object-key'],
    tier: 0,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/no-dupe-keys.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'no-constant-condition',
    concepts: ['correctness.no-constant-condition'],
    tier: 0,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/no-constant-condition.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'no-unused-vars',
    concepts: ['dead-code.unused-variable', 'dead-code.unused-import'],
    classify: [{ messagePattern: '\\bimport(ed)?\\b', concept: 'dead-code.unused-import' }],
    tier: 0,
    priority: 90,
    severityDefault: 'warn',
    fixKind: 'suggested',
    fixTouches: ['imports', 'statements'],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/no-unused-vars.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'no-var',
    concepts: ['style.no-var'],
    tier: 0,
    priority: 80,
    severityDefault: 'warn',
    fixKind: 'safe',
    fixTouches: ['statements'],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/no-var.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'typescript/no-explicit-any',
    concepts: ['slop.as-any-cast'],
    tier: 0,
    priority: 85,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/typescript/no-explicit-any.html`,
    since: '0.1.0',
  },
  // M0's curated stopgap expansion: 39 rules hand-picked from oxlint's `correctness` and
  // `suspicious` categories only (`oxlint --rules --format json`), all bare `eslint`-scope so none
  // of them need a new plugin activated in `materializeOxlintConfig`. `style` and `restriction` are
  // deliberately excluded — oxlint ships hundreds of rules in those two categories, and enabling
  // them by default would collide with a project's own Prettier/ESLint choices on every run,
  // teaching users to ignore the gate rather than trust it. Generating the registry from engine
  // introspection instead of hand-authoring it is M1 work; this is what M0 could verify by hand.
  {
    engine: 'oxlint',
    engineRuleId: 'constructor-super',
    concepts: ['correctness.invalid-super-call'],
    tier: 0,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/constructor-super.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'for-direction',
    concepts: ['correctness.invalid-loop-direction'],
    tier: 0,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/for-direction.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'getter-return',
    concepts: ['correctness.getter-missing-return'],
    tier: 0,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/getter-return.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'no-async-promise-executor',
    concepts: ['correctness.async-promise-executor'],
    tier: 0,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/no-async-promise-executor.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'no-class-assign',
    concepts: ['correctness.class-reassigned'],
    tier: 0,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/no-class-assign.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'no-compare-neg-zero',
    concepts: ['correctness.compare-negative-zero'],
    tier: 0,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/no-compare-neg-zero.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'no-cond-assign',
    concepts: ['correctness.assignment-in-condition'],
    tier: 0,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/no-cond-assign.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'no-const-assign',
    concepts: ['correctness.const-reassigned'],
    tier: 0,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/no-const-assign.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'no-constant-binary-expression',
    concepts: ['correctness.constant-binary-expression'],
    tier: 0,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/no-constant-binary-expression.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'no-dupe-class-members',
    concepts: ['correctness.duplicate-class-member'],
    tier: 0,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/no-dupe-class-members.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'no-dupe-else-if',
    concepts: ['correctness.duplicate-else-if-condition'],
    tier: 0,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/no-dupe-else-if.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'no-duplicate-case',
    concepts: ['correctness.duplicate-switch-case'],
    tier: 0,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/no-duplicate-case.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'no-empty-pattern',
    concepts: ['correctness.empty-destructuring-pattern'],
    tier: 0,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/no-empty-pattern.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'no-eval',
    concepts: ['security.eval-usage'],
    tier: 0,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/no-eval.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'no-ex-assign',
    concepts: ['correctness.caught-error-reassigned'],
    tier: 0,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/no-ex-assign.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'no-func-assign',
    concepts: ['correctness.function-reassigned'],
    tier: 0,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/no-func-assign.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'no-global-assign',
    concepts: ['correctness.global-reassigned'],
    tier: 0,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/no-global-assign.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'no-import-assign',
    concepts: ['correctness.import-binding-reassigned'],
    tier: 0,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/no-import-assign.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'no-invalid-regexp',
    concepts: ['correctness.invalid-regexp'],
    tier: 0,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/no-invalid-regexp.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'no-loss-of-precision',
    concepts: ['correctness.numeric-literal-loses-precision'],
    tier: 0,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/no-loss-of-precision.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'no-new-native-nonconstructor',
    concepts: ['correctness.invalid-native-constructor-call'],
    tier: 0,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/no-new-native-nonconstructor.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'no-obj-calls',
    concepts: ['correctness.namespace-object-called'],
    tier: 0,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/no-obj-calls.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'no-self-assign',
    concepts: ['correctness.self-assignment'],
    tier: 0,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/no-self-assign.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'no-setter-return',
    concepts: ['correctness.setter-returns-value'],
    tier: 0,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/no-setter-return.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'no-shadow-restricted-names',
    concepts: ['correctness.shadows-reserved-global'],
    tier: 0,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/no-shadow-restricted-names.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'no-sparse-arrays',
    concepts: ['correctness.sparse-array-literal'],
    tier: 0,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/no-sparse-arrays.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'no-this-before-super',
    concepts: ['correctness.this-before-super'],
    tier: 0,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/no-this-before-super.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'no-unreachable',
    concepts: ['correctness.unreachable-code'],
    tier: 0,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/no-unreachable.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'no-unsafe-finally',
    concepts: ['correctness.unsafe-finally-control-flow'],
    tier: 0,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/no-unsafe-finally.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'no-unsafe-negation',
    concepts: ['correctness.unsafe-negation'],
    tier: 0,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/no-unsafe-negation.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'no-unsafe-optional-chaining',
    concepts: ['correctness.unsafe-optional-chaining'],
    tier: 0,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/no-unsafe-optional-chaining.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'no-unused-expressions',
    concepts: ['dead-code.no-op-expression'],
    tier: 0,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/no-unused-expressions.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'require-yield',
    concepts: ['correctness.generator-never-yields'],
    tier: 0,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/require-yield.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'use-isnan',
    concepts: ['correctness.nan-comparison'],
    tier: 0,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/use-isnan.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'valid-typeof',
    concepts: ['correctness.invalid-typeof-comparison'],
    tier: 0,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/valid-typeof.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'no-unexpected-multiline',
    concepts: ['correctness.ambiguous-line-break'],
    tier: 0,
    priority: 80,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/no-unexpected-multiline.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'no-unmodified-loop-condition',
    concepts: ['correctness.unmodified-loop-condition'],
    tier: 0,
    priority: 80,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/no-unmodified-loop-condition.html`,
    since: '0.1.0',
  },
  // `no-implied-eval` was in this batch and is deliberately not: verified directly against oxlint
  // 1.76.0 with the classic `setTimeout("code", ms)` / `setInterval` / `new Function` /
  // `execScript` trigger patterns and it reported nothing for any of them, despite
  // `number_of_rules` confirming the rule was active. A rule that never fires is worse than no
  // rule — it would report false coverage of `security.implied-eval` (a concept no entry now
  // claims) for zero actual detection. Landing this batch at 39 rather than a forced 40.
  {
    engine: 'oxlint',
    engineRuleId: 'no-extend-native',
    concepts: ['correctness.native-prototype-extended'],
    tier: 0,
    priority: 80,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/no-extend-native.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'preserve-caught-error',
    concepts: ['correctness.discarded-caught-error'],
    tier: 0,
    priority: 80,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/preserve-caught-error.html`,
    since: '0.1.0',
  },
  // Five-fixes follow-up session: real-world use on a NestJS project (95 TS files under `src`) found
  // two oxlint rules beyond the 39-rule batch above that fire on real code. `no-shadow` is added
  // below, `category: "suspicious"` confirmed via `oxlint --rules --format json` (not "correctness" —
  // this registry already carries `suspicious`-sourced entries, see the batch above, so that's not a
  // reason to leave it out).
  {
    engine: 'oxlint',
    engineRuleId: 'no-shadow',
    concepts: ['correctness.shadows-outer-binding'],
    tier: 0,
    priority: 80,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/no-shadow.html`,
    since: '0.1.0',
  },
  // `typescript/no-extraneous-class` ("Unexpected empty class") is deliberately NOT an entry here —
  // this is not an oversight, so do not add it back without re-reading this note. Measured against
  // the same real NestJS project, enabled alongside `no-shadow` above: 12 total findings, 11 of them
  // `typescript/no-extraneous-class` and every single one a false positive — an empty
  // `@Module({...}) export class XModule {}`, one per `*.module.ts` file. NestJS (and Angular, and
  // any other decorator-driven DI framework) *requires* that class to be empty; the decorator, not
  // the class body, carries the behaviour. In isolation the rule is 11/11 (100%) false positives on
  // this codebase; "~92%" is its share of the combined 12-finding sample once the one genuine
  // `no-shadow` bug is counted alongside it — both figures are measured, not estimated, and are
  // quoted together here because they answer slightly different questions.
  //
  // The general lesson, for whoever next expands this registry: a rule's value depends on the
  // framework present in the repository, and this registry has no notion of framework awareness —
  // it cannot know a codebase uses decorator-driven DI and adjust. A curated, hand-picked registry
  // (like this one) can route around a case like this one rule at a time; a *generated* registry
  // (M1's stated direction — see the comment atop the batch above) cannot, unless framework detection
  // becomes one of its inputs. Recorded in full in
  // docs/superpowers/specs/2026-07-31-m0-followups.md.
  {
    engine: 'eslint',
    engineRuleId: '@typescript-eslint/no-unused-vars',
    concepts: ['dead-code.unused-variable'],
    tier: 2,
    priority: 50,
    severityDefault: 'warn',
    fixKind: 'suggested',
    fixTouches: ['imports', 'statements'],
    requires: [],
    languages: ['ts', 'tsx'],
    docsUrl: 'https://typescript-eslint.io/rules/no-unused-vars/',
    since: '0.1.0',
  },
] as const satisfies readonly RuleEntry[]
