import type { RuleEntry } from './types.ts'

const KNIP_DOCS = 'https://knip.dev/reference/issue-types'

const KNIP_RULE_ENTRIES = [
  {
    engine: 'knip',
    engineRuleId: 'files',
    concepts: ['dead-code.unused-file'],
    tier: 2,
    priority: 50,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx'],
    docsUrl: KNIP_DOCS,
    since: '0.1.0',
  },
  {
    engine: 'knip',
    engineRuleId: 'dependencies',
    concepts: ['deps.unused-dependency'],
    tier: 2,
    priority: 50,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx'],
    docsUrl: KNIP_DOCS,
    since: '0.1.0',
  },
  {
    engine: 'knip',
    engineRuleId: 'devDependencies',
    concepts: ['deps.unused-dev-dependency'],
    tier: 2,
    priority: 50,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx'],
    docsUrl: KNIP_DOCS,
    since: '0.1.0',
  },
  {
    engine: 'knip',
    engineRuleId: 'unlisted',
    concepts: ['deps.unlisted-dependency'],
    tier: 2,
    priority: 50,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx'],
    docsUrl: KNIP_DOCS,
    since: '0.1.0',
  },
  {
    engine: 'knip',
    engineRuleId: 'binaries',
    concepts: ['deps.unlisted-binary'],
    tier: 2,
    priority: 50,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx'],
    docsUrl: KNIP_DOCS,
    since: '0.1.0',
  },
  {
    engine: 'knip',
    engineRuleId: 'unresolved',
    concepts: ['deps.unresolved-import'],
    tier: 2,
    priority: 50,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx'],
    docsUrl: KNIP_DOCS,
    since: '0.1.0',
  },
  {
    engine: 'knip',
    engineRuleId: 'exports',
    concepts: ['dead-code.unused-export'],
    tier: 2,
    priority: 50,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx'],
    docsUrl: KNIP_DOCS,
    since: '0.1.0',
  },
  {
    engine: 'knip',
    engineRuleId: 'types',
    concepts: ['dead-code.unused-exported-type'],
    tier: 2,
    priority: 50,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx'],
    docsUrl: KNIP_DOCS,
    since: '0.1.0',
  },
  {
    engine: 'knip',
    engineRuleId: 'enumMembers',
    concepts: ['dead-code.unused-enum-member'],
    tier: 2,
    priority: 50,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx'],
    docsUrl: KNIP_DOCS,
    since: '0.1.0',
  },
  {
    engine: 'knip',
    engineRuleId: 'duplicates',
    concepts: ['dead-code.duplicate-export'],
    tier: 2,
    priority: 50,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx'],
    docsUrl: KNIP_DOCS,
    since: '0.1.0',
  },
  {
    engine: 'knip',
    engineRuleId: 'catalog',
    concepts: ['dead-code.unused-catalog-entry'],
    tier: 2,
    priority: 50,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx'],
    docsUrl: KNIP_DOCS,
    since: '0.1.0',
  },
  {
    engine: 'knip',
    engineRuleId: 'catalogReferences',
    concepts: ['deps.unresolved-catalog-reference'],
    tier: 2,
    priority: 50,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx'],
    docsUrl: KNIP_DOCS,
    since: '0.1.0',
  },
] as const satisfies readonly RuleEntry[]

const ASTGREP_DOCS = 'https://github.com/misaon/slop-gate/blob/main/docs/rules'

const ASTGREP_RULE_ENTRIES = [
  {
    engine: 'astgrep',
    engineRuleId: 'slop-double-cast',
    concepts: ['slop.double-cast'],
    tier: 0,
    priority: 50,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx'],
    docsUrl: `${ASTGREP_DOCS}/slop.double-cast.md`,
    since: '0.1.0',
  },
  {
    engine: 'astgrep',
    engineRuleId: 'slop-swallowed-error',
    concepts: ['slop.swallowed-error'],
    tier: 0,
    priority: 50,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx'],
    docsUrl: `${ASTGREP_DOCS}/slop.swallowed-error.md`,
    since: '0.1.0',
  },
  {
    engine: 'astgrep',
    engineRuleId: 'slop-stub-implementation',
    concepts: ['slop.stub-implementation'],
    tier: 0,
    priority: 50,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx'],
    docsUrl: `${ASTGREP_DOCS}/slop.stub-implementation.md`,
    since: '0.1.0',
  },
  {
    engine: 'astgrep',
    engineRuleId: 'slop-narrative-comment',
    concepts: ['slop.narrative-comment'],
    tier: 0,
    priority: 50,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx'],
    docsUrl: `${ASTGREP_DOCS}/slop.narrative-comment.md`,
    since: '0.1.0',
  },
  {
    engine: 'astgrep',
    engineRuleId: 'slop-emoji-in-code',
    concepts: ['slop.emoji-in-code'],
    tier: 0,
    priority: 50,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx'],
    docsUrl: `${ASTGREP_DOCS}/slop.emoji-in-code.md`,
    since: '0.1.0',
  },
] as const satisfies readonly RuleEntry[]

const SCHEMA_RULE_ENTRIES = [
  {
    engine: 'schema',
    engineRuleId: 'parse-error',
    concepts: ['correctness.parse-error'],
    tier: 2,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['yaml', 'github-workflow'],
    docsUrl: 'https://yaml.org/spec/1.2.2/',
    since: '0.1.0',
  },
  {
    engine: 'schema',
    engineRuleId: 'duplicate-mapping-key',
    concepts: ['correctness.no-duplicate-object-key'],
    tier: 2,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['yaml', 'github-workflow'],
    docsUrl: 'https://yaml.org/spec/1.2.2/#nodes',
    since: '0.1.0',
  },
  {
    engine: 'schema',
    engineRuleId: 'compose-spec',
    concepts: ['config.compose-schema'],
    tier: 2,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['yaml'],
    docsUrl: 'https://github.com/compose-spec/compose-spec/blob/main/spec.md',
    since: '0.1.0',
  },
] as const satisfies readonly RuleEntry[]

const DEPS_SECURITY_DOCS = 'https://osv.dev/'

const DEPS_SECURITY_RULE_ENTRIES = [
  {
    engine: 'deps-security',
    engineRuleId: 'vulnerability',
    concepts: ['security.vulnerable-dependency'],
    tier: 2,
    priority: 50,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['json', 'yaml'],
    docsUrl: DEPS_SECURITY_DOCS,
    since: '0.1.0',
  },
  {
    engine: 'deps-security',
    engineRuleId: 'malware',
    concepts: ['security.malicious-dependency'],
    tier: 2,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['json', 'yaml'],
    docsUrl: DEPS_SECURITY_DOCS,
    since: '0.1.0',
  },
  {
    engine: 'deps-security',
    engineRuleId: 'missing-lockfile-entry',
    concepts: ['deps.missing-lockfile-entry'],
    tier: 2,
    priority: 50,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['json', 'yaml'],
    docsUrl: DEPS_SECURITY_DOCS,
    since: '0.1.0',
  },
  {
    engine: 'deps-security',
    engineRuleId: 'coverage-gap',
    concepts: ['deps.advisory-coverage-gap'],
    tier: 2,
    priority: 50,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['json', 'yaml'],
    docsUrl: DEPS_SECURITY_DOCS,
    since: '0.1.0',
  },
] as const satisfies readonly RuleEntry[]

const ACTIONLINT_DOCS = 'https://github.com/rhysd/actionlint/blob/v1.7.12/docs/checks.md'

const ACTIONLINT_RULE_ENTRIES = [
  {
    engine: 'actionlint',
    engineRuleId: 'action',
    concepts: ['config.workflow-action'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['github-workflow'],
    docsUrl: `${ACTIONLINT_DOCS}#action-format-in-uses`,
    since: '0.1.0',
  },
  {
    engine: 'actionlint',
    engineRuleId: 'credentials',
    concepts: ['security.workflow-hardcoded-credential'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['github-workflow'],
    docsUrl: `${ACTIONLINT_DOCS}#hardcoded-credentials`,
    since: '0.1.0',
  },
  {
    engine: 'actionlint',
    engineRuleId: 'deprecated-commands',
    concepts: ['config.workflow-deprecated-command'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['github-workflow'],
    docsUrl: `${ACTIONLINT_DOCS}#check-deprecated-workflow-commands`,
    since: '0.1.0',
  },
  {
    engine: 'actionlint',
    engineRuleId: 'env-var',
    concepts: ['config.workflow-env-var'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['github-workflow'],
    docsUrl: `${ACTIONLINT_DOCS}#environment-variable-names`,
    since: '0.1.0',
  },
  {
    engine: 'actionlint',
    engineRuleId: 'events',
    concepts: ['config.workflow-event'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['github-workflow'],
    docsUrl: `${ACTIONLINT_DOCS}#webhook-events-validation`,
    since: '0.1.0',
  },
  {
    engine: 'actionlint',
    engineRuleId: 'expression',
    concepts: ['config.workflow-expression'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['github-workflow'],
    docsUrl: `${ACTIONLINT_DOCS}#contexts-and-built-in-functions`,
    since: '0.1.0',
  },
  {
    engine: 'actionlint',
    engineRuleId: 'glob',
    concepts: ['config.workflow-glob'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['github-workflow'],
    docsUrl: `${ACTIONLINT_DOCS}#glob-filter-pattern-syntax-validation`,
    since: '0.1.0',
  },
  {
    engine: 'actionlint',
    engineRuleId: 'id',
    concepts: ['config.workflow-id'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['github-workflow'],
    docsUrl: `${ACTIONLINT_DOCS}#job-id-and-step-id-uniqueness`,
    since: '0.1.0',
  },
  {
    engine: 'actionlint',
    engineRuleId: 'if-cond',
    concepts: ['config.workflow-condition'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['github-workflow'],
    docsUrl: `${ACTIONLINT_DOCS}#constant-conditions-at-if`,
    since: '0.1.0',
  },
  {
    engine: 'actionlint',
    engineRuleId: 'job-needs',
    concepts: ['config.workflow-job-needs'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['github-workflow'],
    docsUrl: `${ACTIONLINT_DOCS}#job-dependencies-validation`,
    since: '0.1.0',
  },
  {
    engine: 'actionlint',
    engineRuleId: 'matrix',
    concepts: ['config.workflow-matrix'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['github-workflow'],
    docsUrl: `${ACTIONLINT_DOCS}#matrix-values`,
    since: '0.1.0',
  },
  {
    engine: 'actionlint',
    engineRuleId: 'permissions',
    concepts: ['config.workflow-permissions'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['github-workflow'],
    docsUrl: `${ACTIONLINT_DOCS}#permissions`,
    since: '0.1.0',
  },
  {
    engine: 'actionlint',
    engineRuleId: 'runner-label',
    concepts: ['config.workflow-runner-label'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['github-workflow'],
    docsUrl: `${ACTIONLINT_DOCS}#runner-labels`,
    since: '0.1.0',
  },
  {
    engine: 'actionlint',
    engineRuleId: 'shell-name',
    concepts: ['config.workflow-shell'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['github-workflow'],
    docsUrl: `${ACTIONLINT_DOCS}#shell-name-validation-at-shell`,
    since: '0.1.0',
  },
  {
    engine: 'actionlint',
    engineRuleId: 'syntax-check',
    concepts: ['config.workflow-syntax'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['github-workflow'],
    docsUrl: `${ACTIONLINT_DOCS}#unexpected-keys`,
    since: '0.1.0',
  },
  {
    engine: 'actionlint',
    engineRuleId: 'workflow-call',
    concepts: ['config.workflow-call'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['github-workflow'],
    docsUrl: `${ACTIONLINT_DOCS}#reusable-workflows`,
    since: '0.1.0',
  },
] as const satisfies readonly RuleEntry[]

const BIOME_DOCS = 'https://biomejs.dev/linter/rules'

const BIOME_CSS_RULE_ENTRIES = [
  {
    engine: 'biome-css',
    engineRuleId: 'noShorthandPropertyOverrides',
    concepts: ['correctness.css-shorthand-override'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['css'],
    docsUrl: `${BIOME_DOCS}/no-shorthand-property-overrides`,
    since: '0.1.0',
  },
  {
    engine: 'biome-css',
    engineRuleId: 'noUnknownProperty',
    concepts: ['correctness.css-unknown-property'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['css'],
    docsUrl: `${BIOME_DOCS}/no-unknown-property`,
    since: '0.1.0',
  },
  {
    engine: 'biome-css',
    engineRuleId: 'noUnknownTypeSelector',
    concepts: ['correctness.css-unknown-type-selector'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['css'],
    docsUrl: `${BIOME_DOCS}/no-unknown-type-selector`,
    since: '0.1.0',
  },
  {
    engine: 'biome-css',
    engineRuleId: 'noDuplicateProperties',
    concepts: ['correctness.css-duplicate-property'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['css'],
    docsUrl: `${BIOME_DOCS}/no-duplicate-properties`,
    since: '0.1.0',
  },
  {
    engine: 'biome-css',
    engineRuleId: 'noInvalidDirectionInLinearGradient',
    concepts: ['correctness.css-invalid-gradient-direction'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['css'],
    docsUrl: `${BIOME_DOCS}/no-invalid-direction-in-linear-gradient`,
    since: '0.1.0',
  },
  {
    engine: 'biome-css',
    engineRuleId: 'noInvalidPositionAtImportRule',
    concepts: ['correctness.css-import-position'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['css'],
    docsUrl: `${BIOME_DOCS}/no-invalid-position-at-import-rule`,
    since: '0.1.0',
  },
  {
    engine: 'biome-css',
    engineRuleId: 'noMissingVarFunction',
    concepts: ['correctness.css-missing-var-function'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['css'],
    docsUrl: `${BIOME_DOCS}/no-missing-var-function`,
    since: '0.1.0',
  },
  {
    engine: 'biome-css',
    engineRuleId: 'noUnknownPseudoClass',
    concepts: ['correctness.css-unknown-pseudo-class'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['css'],
    docsUrl: `${BIOME_DOCS}/no-unknown-pseudo-class`,
    since: '0.1.0',
  },
  {
    engine: 'biome-css',
    engineRuleId: 'noUnknownPseudoElement',
    concepts: ['correctness.css-unknown-pseudo-element'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['css'],
    docsUrl: `${BIOME_DOCS}/no-unknown-pseudo-element`,
    since: '0.1.0',
  },
  {
    engine: 'biome-css',
    engineRuleId: 'noUnmatchableAnbSelector',
    concepts: ['correctness.css-unmatchable-selector'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['css'],
    docsUrl: `${BIOME_DOCS}/no-unmatchable-anb-selector`,
    since: '0.1.0',
  },
  {
    engine: 'biome-css',
    engineRuleId: 'noDuplicateAtImportRules',
    concepts: ['correctness.css-duplicate-import'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['css'],
    docsUrl: `${BIOME_DOCS}/no-duplicate-at-import-rules`,
    since: '0.1.0',
  },
  {
    engine: 'biome-css',
    engineRuleId: 'noDuplicateCustomProperties',
    concepts: ['correctness.css-duplicate-custom-property'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['css'],
    docsUrl: `${BIOME_DOCS}/no-duplicate-custom-properties`,
    since: '0.1.0',
  },
  {
    engine: 'biome-css',
    engineRuleId: 'noDuplicateFontNames',
    concepts: ['correctness.css-duplicate-font-name'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['css'],
    docsUrl: `${BIOME_DOCS}/no-duplicate-font-names`,
    since: '0.1.0',
  },
  {
    engine: 'biome-css',
    engineRuleId: 'noDuplicateSelectorsKeyframeBlock',
    concepts: ['correctness.css-duplicate-keyframe-selector'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['css'],
    docsUrl: `${BIOME_DOCS}/no-duplicate-selectors-keyframe-block`,
    since: '0.1.0',
  },
  {
    engine: 'biome-css',
    engineRuleId: 'noImportantInKeyframe',
    concepts: ['correctness.css-important-in-keyframe'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['css'],
    docsUrl: `${BIOME_DOCS}/no-important-in-keyframe`,
    since: '0.1.0',
  },
  {
    engine: 'biome-css',
    engineRuleId: 'noDeprecatedMediaType',
    concepts: ['correctness.css-deprecated-media-type'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['css'],
    docsUrl: `${BIOME_DOCS}/no-deprecated-media-type`,
    since: '0.1.0',
  },
  {
    engine: 'biome-css',
    engineRuleId: 'noIrregularWhitespace',
    concepts: ['correctness.css-irregular-whitespace'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['css'],
    docsUrl: `${BIOME_DOCS}/no-irregular-whitespace`,
    since: '0.1.0',
  },
  {
    engine: 'biome-css',
    engineRuleId: 'noUnknownAtRules',
    concepts: ['correctness.css-unknown-at-rule'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['css'],
    docsUrl: `${BIOME_DOCS}/no-unknown-at-rules`,
    since: '0.1.0',
  },
  {
    engine: 'biome-css',
    engineRuleId: 'noUnknownFunction',
    concepts: ['correctness.css-unknown-function'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['css'],
    docsUrl: `${BIOME_DOCS}/no-unknown-function`,
    since: '0.1.0',
  },
  {
    engine: 'biome-css',
    engineRuleId: 'useGenericFontNames',
    concepts: ['a11y.css-generic-font-name'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['css'],
    docsUrl: `${BIOME_DOCS}/use-generic-font-names`,
    since: '0.1.0',
  },
  {
    engine: 'biome-css',
    engineRuleId: 'noDuplicateSelectors',
    concepts: ['duplication.css-duplicate-selector'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['css'],
    docsUrl: `${BIOME_DOCS}/no-duplicate-selectors`,
    since: '0.1.0',
  },
  {
    engine: 'biome-css',
    engineRuleId: 'noEmptyBlock',
    concepts: ['duplication.css-empty-block'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['css'],
    docsUrl: `${BIOME_DOCS}/no-empty-block`,
    since: '0.1.0',
  },
  {
    engine: 'biome-css',
    engineRuleId: 'noHexColors',
    concepts: ['style.css-hex-color'],
    tier: 0,
    priority: 100,
    severityDefault: 'info',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['css'],
    docsUrl: `${BIOME_DOCS}/no-hex-colors`,
    since: '0.1.0',
  },
  {
    engine: 'biome-css',
    engineRuleId: 'noDescendingSpecificity',
    concepts: ['style.css-descending-specificity'],
    tier: 0,
    priority: 100,
    severityDefault: 'info',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['css'],
    docsUrl: `${BIOME_DOCS}/no-descending-specificity`,
    since: '0.1.0',
  },
  {
    engine: 'biome-css',
    engineRuleId: 'noEmptySource',
    concepts: ['suspicious.css-empty-source'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['css'],
    docsUrl: `${BIOME_DOCS}/no-empty-source`,
    since: '0.1.0',
  },
  {
    engine: 'biome-css',
    engineRuleId: 'noValueAtRule',
    concepts: ['style.css-value-at-rule'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['css'],
    docsUrl: `${BIOME_DOCS}/no-value-at-rule`,
    since: '0.1.0',
  },
  {
    engine: 'biome-css',
    engineRuleId: 'noExcessiveLinesPerFile',
    concepts: ['pedantic.css-max-lines'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['css'],
    docsUrl: `${BIOME_DOCS}/no-excessive-lines-per-file`,
    since: '0.1.0',
  },
  {
    engine: 'biome-css',
    engineRuleId: 'useBaseline',
    concepts: ['style.css-baseline'],
    tier: 0,
    priority: 100,
    severityDefault: 'info',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['css'],
    docsUrl: `${BIOME_DOCS}/use-baseline`,
    since: '0.1.0',
  },
  {
    engine: 'biome-css',
    engineRuleId: 'noImportantStyles',
    concepts: ['complexity.css-important'],
    tier: 0,
    priority: 100,
    severityDefault: 'info',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['css'],
    docsUrl: `${BIOME_DOCS}/no-important-styles`,
    since: '0.1.0',
  },
  {
    engine: 'biome-css',
    engineRuleId: 'css-parse-error',
    concepts: ['config.css-not-analysed'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['css'],
    docsUrl: 'https://biomejs.dev/internals/language-support/',
    since: '0.1.0',
  },
  {
    engine: 'biome-css',
    engineRuleId: 'foreign-suppression',
    concepts: ['config.foreign-suppression'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['css'],
    docsUrl: 'https://biomejs.dev/linter/#suppress-lint-rules',
    since: '0.1.0',
  },
] as const satisfies readonly RuleEntry[]

const HADOLINT_DOCS = 'https://github.com/hadolint/hadolint/wiki'

const HADOLINT_RULE_ENTRIES = [
  {
    engine: 'hadolint',
    engineRuleId: 'DL3006',
    concepts: ['config.dockerfile-base-image-untagged'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['dockerfile'],
    docsUrl: `${HADOLINT_DOCS}/DL3006`,
    since: '0.1.0',
  },
  {
    engine: 'hadolint',
    engineRuleId: 'DL3007',
    concepts: ['config.dockerfile-base-image-mutable-tag'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['dockerfile'],
    docsUrl: `${HADOLINT_DOCS}/DL3007`,
    since: '0.1.0',
  },
  {
    engine: 'hadolint',
    engineRuleId: 'DL3025',
    concepts: ['config.dockerfile-entrypoint-form'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['dockerfile'],
    docsUrl: `${HADOLINT_DOCS}/DL3025`,
    since: '0.1.0',
  },
  {
    engine: 'hadolint',
    engineRuleId: 'DL3029',
    concepts: ['config.dockerfile-platform'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['dockerfile'],
    docsUrl: `${HADOLINT_DOCS}/DL3029`,
    since: '0.1.0',
  },
  {
    engine: 'hadolint',
    engineRuleId: 'DL3042',
    concepts: ['config.dockerfile-package-cache'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['dockerfile'],
    docsUrl: `${HADOLINT_DOCS}/DL3042`,
    since: '0.1.0',
  },
  {
    engine: 'hadolint',
    engineRuleId: 'DL4006',
    concepts: ['config.dockerfile-pipefail'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['dockerfile'],
    docsUrl: `${HADOLINT_DOCS}/DL4006`,
    since: '0.1.0',
  },
  {
    engine: 'hadolint',
    engineRuleId: 'DL3000',
    concepts: ['config.dockerfile-absolute-workdir'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['dockerfile'],
    docsUrl: `${HADOLINT_DOCS}/DL3000`,
    since: '0.1.0',
  },
  {
    engine: 'hadolint',
    engineRuleId: 'DL3001',
    concepts: ['config.dockerfile-pointless-command'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['dockerfile'],
    docsUrl: `${HADOLINT_DOCS}/DL3001`,
    since: '0.1.0',
  },
  {
    engine: 'hadolint',
    engineRuleId: 'DL3002',
    concepts: ['config.dockerfile-last-user-root'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['dockerfile'],
    docsUrl: `${HADOLINT_DOCS}/DL3002`,
    since: '0.1.0',
  },
  {
    engine: 'hadolint',
    engineRuleId: 'DL3004',
    concepts: ['config.dockerfile-sudo'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['dockerfile'],
    docsUrl: `${HADOLINT_DOCS}/DL3004`,
    since: '0.1.0',
  },
  {
    engine: 'hadolint',
    engineRuleId: 'DL3010',
    concepts: ['config.dockerfile-add-archive'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['dockerfile'],
    docsUrl: `${HADOLINT_DOCS}/DL3010`,
    since: '0.1.0',
  },
  {
    engine: 'hadolint',
    engineRuleId: 'DL3011',
    concepts: ['config.dockerfile-invalid-port'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['dockerfile'],
    docsUrl: `${HADOLINT_DOCS}/DL3011`,
    since: '0.1.0',
  },
  {
    engine: 'hadolint',
    engineRuleId: 'DL3012',
    concepts: ['config.dockerfile-multiple-healthcheck'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['dockerfile'],
    docsUrl: `${HADOLINT_DOCS}/DL3012`,
    since: '0.1.0',
  },
  {
    engine: 'hadolint',
    engineRuleId: 'DL3014',
    concepts: ['config.dockerfile-apt-get-yes'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['dockerfile'],
    docsUrl: `${HADOLINT_DOCS}/DL3014`,
    since: '0.1.0',
  },
  {
    engine: 'hadolint',
    engineRuleId: 'DL3016',
    concepts: ['config.dockerfile-pin-npm'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['dockerfile'],
    docsUrl: `${HADOLINT_DOCS}/DL3016`,
    since: '0.1.0',
  },
  {
    engine: 'hadolint',
    engineRuleId: 'DL3021',
    concepts: ['config.dockerfile-copy-multiple-targets'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['dockerfile'],
    docsUrl: `${HADOLINT_DOCS}/DL3021`,
    since: '0.1.0',
  },
  {
    engine: 'hadolint',
    engineRuleId: 'DL3022',
    concepts: ['config.dockerfile-copy-from-unknown-stage'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['dockerfile'],
    docsUrl: `${HADOLINT_DOCS}/DL3022`,
    since: '0.1.0',
  },
  {
    engine: 'hadolint',
    engineRuleId: 'DL3023',
    concepts: ['config.dockerfile-copy-from-self'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['dockerfile'],
    docsUrl: `${HADOLINT_DOCS}/DL3023`,
    since: '0.1.0',
  },
  {
    engine: 'hadolint',
    engineRuleId: 'DL3024',
    concepts: ['config.dockerfile-duplicate-stage-name'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['dockerfile'],
    docsUrl: `${HADOLINT_DOCS}/DL3024`,
    since: '0.1.0',
  },
  {
    engine: 'hadolint',
    engineRuleId: 'DL3027',
    concepts: ['config.dockerfile-apt-not-apt-get'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['dockerfile'],
    docsUrl: `${HADOLINT_DOCS}/DL3027`,
    since: '0.1.0',
  },
  {
    engine: 'hadolint',
    engineRuleId: 'DL3028',
    concepts: ['config.dockerfile-pin-gem'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['dockerfile'],
    docsUrl: `${HADOLINT_DOCS}/DL3028`,
    since: '0.1.0',
  },
  {
    engine: 'hadolint',
    engineRuleId: 'DL3030',
    concepts: ['config.dockerfile-yum-yes'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['dockerfile'],
    docsUrl: `${HADOLINT_DOCS}/DL3030`,
    since: '0.1.0',
  },
  {
    engine: 'hadolint',
    engineRuleId: 'DL3034',
    concepts: ['config.dockerfile-zypper-yes'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['dockerfile'],
    docsUrl: `${HADOLINT_DOCS}/DL3034`,
    since: '0.1.0',
  },
  {
    engine: 'hadolint',
    engineRuleId: 'DL3035',
    concepts: ['config.dockerfile-zypper-dist-upgrade'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['dockerfile'],
    docsUrl: `${HADOLINT_DOCS}/DL3035`,
    since: '0.1.0',
  },
  {
    engine: 'hadolint',
    engineRuleId: 'DL3038',
    concepts: ['config.dockerfile-dnf-yes'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['dockerfile'],
    docsUrl: `${HADOLINT_DOCS}/DL3038`,
    since: '0.1.0',
  },
  {
    engine: 'hadolint',
    engineRuleId: 'DL3043',
    concepts: ['config.dockerfile-onbuild-onbuild'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['dockerfile'],
    docsUrl: `${HADOLINT_DOCS}/DL3043`,
    since: '0.1.0',
  },
  {
    engine: 'hadolint',
    engineRuleId: 'DL3044',
    concepts: ['config.dockerfile-env-self-reference'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['dockerfile'],
    docsUrl: `${HADOLINT_DOCS}/DL3044`,
    since: '0.1.0',
  },
  {
    engine: 'hadolint',
    engineRuleId: 'DL3048',
    concepts: ['config.dockerfile-invalid-label-key'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['dockerfile'],
    docsUrl: `${HADOLINT_DOCS}/DL3048`,
    since: '0.1.0',
  },
  {
    engine: 'hadolint',
    engineRuleId: 'DL3057',
    concepts: ['config.dockerfile-missing-healthcheck'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['dockerfile'],
    docsUrl: `${HADOLINT_DOCS}/DL3057`,
    since: '0.1.0',
  },
  {
    engine: 'hadolint',
    engineRuleId: 'DL3061',
    concepts: ['config.dockerfile-instruction-order'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['dockerfile'],
    docsUrl: `${HADOLINT_DOCS}/DL3061`,
    since: '0.1.0',
  },
  {
    engine: 'hadolint',
    engineRuleId: 'DL3062',
    concepts: ['config.dockerfile-pin-go'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['dockerfile'],
    docsUrl: `${HADOLINT_DOCS}/DL3062`,
    since: '0.1.0',
  },
  {
    engine: 'hadolint',
    engineRuleId: 'DL3063',
    concepts: ['config.dockerfile-reserved-stage-name'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['dockerfile'],
    docsUrl: `${HADOLINT_DOCS}/DL3063`,
    since: '0.1.0',
  },
  {
    engine: 'hadolint',
    engineRuleId: 'DL3065',
    concepts: ['config.dockerfile-redundant-platform'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['dockerfile'],
    docsUrl: `${HADOLINT_DOCS}/DL3065`,
    since: '0.1.0',
  },
  {
    engine: 'hadolint',
    engineRuleId: 'DL3067',
    concepts: ['config.dockerfile-copy-whole-filesystem'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['dockerfile'],
    docsUrl: `${HADOLINT_DOCS}/DL3067`,
    since: '0.1.0',
  },
  {
    engine: 'hadolint',
    engineRuleId: 'DL4000',
    concepts: ['config.dockerfile-maintainer-deprecated'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['dockerfile'],
    docsUrl: `${HADOLINT_DOCS}/DL4000`,
    since: '0.1.0',
  },
  {
    engine: 'hadolint',
    engineRuleId: 'DL4003',
    concepts: ['config.dockerfile-multiple-cmd'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['dockerfile'],
    docsUrl: `${HADOLINT_DOCS}/DL4003`,
    since: '0.1.0',
  },
  {
    engine: 'hadolint',
    engineRuleId: 'DL4004',
    concepts: ['config.dockerfile-multiple-entrypoint'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['dockerfile'],
    docsUrl: `${HADOLINT_DOCS}/DL4004`,
    since: '0.1.0',
  },
  {
    engine: 'hadolint',
    engineRuleId: 'DL4005',
    concepts: ['config.dockerfile-shell-via-symlink'],
    tier: 0,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['dockerfile'],
    docsUrl: `${HADOLINT_DOCS}/DL4005`,
    since: '0.1.0',
  },
] as const satisfies readonly RuleEntry[]

export const UNCATALOGUED_RULE_ENTRIES = [
  {
    engine: 'oxlint',
    engineRuleId: 'parse-error',
    concepts: ['correctness.parse-error'],
    tier: 0,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: 'https://oxc.rs/docs/guide/usage/linter.html',
    since: '0.1.0',
  },
  {
    engine: 'eslint',
    engineRuleId: '@typescript-eslint/no-unused-vars',
    concepts: ['dead-code.unused-variable'],
    tier: 2,
    priority: 50,
    severityDefault: 'warn',
    fixKind: 'suggested',
    fixTouches: ['imports', 'statements'],
    requires: [],
    languages: ['ts', 'tsx'],
    docsUrl: 'https://typescript-eslint.io/rules/no-unused-vars/',
    since: '0.1.0',
  },
  {
    engine: 'oxfmt',
    engineRuleId: 'unformatted',
    concepts: ['formatting.unformatted'],
    tier: 1,
    priority: 100,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'json', 'yaml', 'css', 'markdown'],
    docsUrl: 'https://oxc.rs/docs/guide/usage/formatter.html',
    since: '0.1.0',
  },
  {
    engine: 'tsc',
    engineRuleId: 'type-error',
    concepts: ['types.type-error'],
    tier: 1,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx'],
    docsUrl: 'https://www.typescriptlang.org/docs/',
    since: '0.1.0',
  },
  ...KNIP_RULE_ENTRIES,
  ...ASTGREP_RULE_ENTRIES,
  ...SCHEMA_RULE_ENTRIES,
  ...ACTIONLINT_RULE_ENTRIES,
  ...BIOME_CSS_RULE_ENTRIES,
  ...DEPS_SECURITY_RULE_ENTRIES,
  ...HADOLINT_RULE_ENTRIES,
] as const satisfies readonly RuleEntry[]
