import type { RuleEntry } from './types.ts'

const OXLINT_DOCS = 'https://oxc.rs/docs/guide/usage/linter/rules'

export const RULE_ENTRIES = [
  {
    engine: 'oxlint',
    engineRuleId: 'no-debugger',
    concepts: ['correctness.no-debugger'],
    tier: 0,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'safe',
    fixTouches: ['statements'],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/no-debugger.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'no-dupe-keys',
    concepts: ['correctness.no-duplicate-object-key'],
    tier: 0,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/no-dupe-keys.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'no-constant-condition',
    concepts: ['correctness.no-constant-condition'],
    tier: 0,
    priority: 100,
    severityDefault: 'error',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/no-constant-condition.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'no-unused-vars',
    concepts: ['dead-code.unused-variable', 'dead-code.unused-import'],
    classify: [{ messagePattern: '\\bimport(ed)?\\b', concept: 'dead-code.unused-import' }],
    tier: 0,
    priority: 90,
    severityDefault: 'warn',
    fixKind: 'suggested',
    fixTouches: ['imports', 'statements'],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/no-unused-vars.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'no-var',
    concepts: ['style.no-var'],
    tier: 0,
    priority: 80,
    severityDefault: 'warn',
    fixKind: 'safe',
    fixTouches: ['statements'],
    requires: [],
    languages: ['ts', 'tsx', 'js', 'jsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/eslint/no-var.html`,
    since: '0.1.0',
  },
  {
    engine: 'oxlint',
    engineRuleId: 'typescript/no-explicit-any',
    concepts: ['slop.as-any-cast'],
    tier: 0,
    priority: 85,
    severityDefault: 'warn',
    fixKind: 'none',
    fixTouches: [],
    requires: [],
    languages: ['ts', 'tsx', 'vue', 'svelte', 'astro'],
    docsUrl: `${OXLINT_DOCS}/typescript/no-explicit-any.html`,
    since: '0.1.0',
  },
  {
    engine: 'eslint',
    engineRuleId: '@typescript-eslint/no-unused-vars',
    concepts: ['dead-code.unused-variable'],
    tier: 2,
    priority: 50,
    severityDefault: 'warn',
    fixKind: 'suggested',
    fixTouches: ['imports', 'statements'],
    requires: [],
    languages: ['ts', 'tsx'],
    docsUrl: 'https://typescript-eslint.io/rules/no-unused-vars/',
    since: '0.1.0',
  },
] as const satisfies readonly RuleEntry[]
