/**
 * How often a rule actually fires, over the 20-repository alpha corpus in `docs/measurements.md`.
 *
 * Two numbers, because they answer different questions. `seenIn` is how many of the 20 projects the
 * rule fired on at all — the honest measure of how widely a rule applies, and not swayed by one
 * repository contributing thousands of findings. `findings` is the raw total, which says how loud it
 * is when it does apply.
 *
 * A rule absent from this table fired on none of the 20, which is not the same as "never fires": the
 * corpus is JavaScript and TypeScript projects, so a Dockerfile or workflow rule can be absent simply
 * because nothing there exercised it.
 *
 * Generated from the corpus run rather than written by hand.
 */
export type Prevalence = {
  /** Projects of `CORPUS_PROJECTS` where the rule produced at least one finding. */
  readonly seenIn: number
  /** Findings across all of them. */
  readonly findings: number
}

export const CORPUS_PROJECTS = 20

const RULE_PREVALENCE: Readonly<Record<string, Prevalence>> = {
  'actionlint/deprecated-commands': { seenIn: 1, findings: 1 },
  'actionlint/events': { seenIn: 2, findings: 2 },
  'actionlint/expression': { seenIn: 2, findings: 7 },
  'actionlint/if-cond': { seenIn: 1, findings: 1 },
  'actionlint/workflow-call': { seenIn: 1, findings: 1 },
  'astgrep/slop-double-cast': { seenIn: 9, findings: 208 },
  'astgrep/slop-narrative-comment': { seenIn: 2, findings: 4 },
  'astgrep/slop-stub-implementation': { seenIn: 1, findings: 1 },
  'biome-css/css-parse-error': { seenIn: 2, findings: 5 },
  'biome-css/noDuplicateCustomProperties': { seenIn: 2, findings: 5 },
  'biome-css/noDuplicateProperties': { seenIn: 4, findings: 11 },
  'biome-css/noUnknownPseudoElement': { seenIn: 1, findings: 1 },
  'deps-security/coverage-gap': { seenIn: 7, findings: 7 },
  'deps-security/vulnerability': { seenIn: 13, findings: 526 },
  'hadolint/DL3006': { seenIn: 1, findings: 2 },
  'hadolint/DL4006': { seenIn: 1, findings: 2 },
  'knip/exports': { seenIn: 8, findings: 112 },
  'knip/types': { seenIn: 7, findings: 56 },
  'knip/unlisted': { seenIn: 5, findings: 43 },
  'knip/unresolved': { seenIn: 3, findings: 4 },
  'oxlint/block-scoped-var': { seenIn: 2, findings: 44 },
  'oxlint/eqeqeq': { seenIn: 7, findings: 176 },
  'oxlint/getter-return': { seenIn: 1, findings: 3 },
  'oxlint/import/default': { seenIn: 1, findings: 3 },
  'oxlint/import/namespace': { seenIn: 2, findings: 22 },
  'oxlint/import/no-empty-named-blocks': { seenIn: 1, findings: 1 },
  'oxlint/import/no-named-as-default': { seenIn: 1, findings: 1 },
  'oxlint/import/no-named-as-default-member': { seenIn: 2, findings: 144 },
  'oxlint/jest/no-export': { seenIn: 4, findings: 10 },
  'oxlint/jsdoc/check-tag-names': { seenIn: 10, findings: 76 },
  'oxlint/jsdoc/no-defaults': { seenIn: 3, findings: 53 },
  'oxlint/jsdoc/require-property-type': { seenIn: 1, findings: 3 },
  'oxlint/jsdoc/require-yields': { seenIn: 1, findings: 1 },
  'oxlint/jsx-a11y/alt-text': { seenIn: 2, findings: 18 },
  'oxlint/jsx-a11y/anchor-has-content': { seenIn: 3, findings: 20 },
  'oxlint/jsx-a11y/anchor-is-valid': { seenIn: 3, findings: 27 },
  'oxlint/jsx-a11y/aria-proptypes': { seenIn: 1, findings: 1 },
  'oxlint/jsx-a11y/aria-role': { seenIn: 1, findings: 3 },
  'oxlint/jsx-a11y/click-events-have-key-events': { seenIn: 6, findings: 59 },
  'oxlint/jsx-a11y/control-has-associated-label': { seenIn: 4, findings: 32 },
  'oxlint/jsx-a11y/heading-has-content': { seenIn: 1, findings: 1 },
  'oxlint/jsx-a11y/html-has-lang': { seenIn: 1, findings: 51 },
  'oxlint/jsx-a11y/iframe-has-title': { seenIn: 2, findings: 4 },
  'oxlint/jsx-a11y/label-has-associated-control': { seenIn: 3, findings: 9 },
  'oxlint/jsx-a11y/lang': { seenIn: 1, findings: 51 },
  'oxlint/jsx-a11y/media-has-caption': { seenIn: 2, findings: 2 },
  'oxlint/jsx-a11y/mouse-events-have-key-events': { seenIn: 1, findings: 1 },
  'oxlint/jsx-a11y/no-autofocus': { seenIn: 2, findings: 37 },
  'oxlint/jsx-a11y/no-interactive-element-to-noninteractive-role': { seenIn: 2, findings: 10 },
  'oxlint/jsx-a11y/no-noninteractive-element-interactions': { seenIn: 3, findings: 15 },
  'oxlint/jsx-a11y/no-noninteractive-element-to-interactive-role': { seenIn: 1, findings: 5 },
  'oxlint/jsx-a11y/no-noninteractive-tabindex': { seenIn: 4, findings: 6 },
  'oxlint/jsx-a11y/no-redundant-roles': { seenIn: 2, findings: 18 },
  'oxlint/jsx-a11y/no-static-element-interactions': { seenIn: 6, findings: 51 },
  'oxlint/jsx-a11y/prefer-tag-over-role': { seenIn: 4, findings: 61 },
  'oxlint/jsx-a11y/role-has-required-aria-props': { seenIn: 1, findings: 16 },
  'oxlint/jsx-a11y/role-supports-aria-props': { seenIn: 3, findings: 5 },
  'oxlint/jsx-a11y/tabindex-no-positive': { seenIn: 1, findings: 31 },
  'oxlint/nextjs/no-assign-module-variable': { seenIn: 2, findings: 3 },
  'oxlint/nextjs/no-html-link-for-pages': { seenIn: 2, findings: 13 },
  'oxlint/nextjs/no-img-element': { seenIn: 1, findings: 58 },
  'oxlint/no-async-promise-executor': { seenIn: 3, findings: 15 },
  'oxlint/no-constant-binary-expression': { seenIn: 4, findings: 15 },
  'oxlint/no-constant-condition': { seenIn: 3, findings: 6 },
  'oxlint/no-control-regex': { seenIn: 2, findings: 11 },
  'oxlint/no-empty-pattern': { seenIn: 2, findings: 5 },
  'oxlint/no-eval': { seenIn: 2, findings: 4 },
  'oxlint/no-ex-assign': { seenIn: 1, findings: 5 },
  'oxlint/no-extend-native': { seenIn: 3, findings: 6 },
  'oxlint/no-extra-boolean-cast': { seenIn: 2, findings: 3 },
  'oxlint/no-loss-of-precision': { seenIn: 1, findings: 50 },
  'oxlint/no-new': { seenIn: 7, findings: 18 },
  'oxlint/no-self-assign': { seenIn: 2, findings: 10 },
  'oxlint/no-shadow': { seenIn: 17, findings: 2823 },
  'oxlint/no-unassigned-vars': { seenIn: 3, findings: 21 },
  'oxlint/no-unexpected-multiline': { seenIn: 1, findings: 2 },
  'oxlint/no-unmodified-loop-condition': { seenIn: 5, findings: 12 },
  'oxlint/no-unneeded-ternary': { seenIn: 4, findings: 8 },
  'oxlint/no-unreachable': { seenIn: 1, findings: 1 },
  'oxlint/no-unsafe-finally': { seenIn: 1, findings: 4 },
  'oxlint/no-unsafe-optional-chaining': { seenIn: 2, findings: 3 },
  'oxlint/no-unused-expressions': { seenIn: 12, findings: 133 },
  'oxlint/no-unused-labels': { seenIn: 1, findings: 1 },
  'oxlint/no-unused-private-class-members': { seenIn: 1, findings: 1 },
  'oxlint/no-unused-vars': { seenIn: 15, findings: 2374 },
  'oxlint/no-useless-catch': { seenIn: 1, findings: 1 },
  'oxlint/no-useless-concat': { seenIn: 4, findings: 13 },
  'oxlint/no-useless-constructor': { seenIn: 5, findings: 9 },
  'oxlint/no-useless-escape': { seenIn: 8, findings: 86 },
  'oxlint/no-useless-rename': { seenIn: 1, findings: 3 },
  'oxlint/oxc/approx-constant': { seenIn: 1, findings: 28 },
  'oxlint/oxc/const-comparisons': { seenIn: 3, findings: 3 },
  'oxlint/oxc/erasing-op': { seenIn: 1, findings: 1 },
  'oxlint/oxc/no-accumulating-spread': { seenIn: 2, findings: 11 },
  'oxlint/oxc/no-async-endpoint-handlers': { seenIn: 4, findings: 38 },
  'oxlint/oxc/no-this-in-exported-function': { seenIn: 3, findings: 14 },
  'oxlint/oxc/only-used-in-recursion': { seenIn: 1, findings: 1 },
  'oxlint/parse-error': { seenIn: 1, findings: 1 },
  'oxlint/preserve-caught-error': { seenIn: 6, findings: 24 },
  'oxlint/promise/always-return': { seenIn: 12, findings: 227 },
  'oxlint/promise/no-callback-in-promise': { seenIn: 9, findings: 63 },
  'oxlint/promise/no-multiple-resolved': { seenIn: 4, findings: 13 },
  'oxlint/promise/no-promise-in-callback': { seenIn: 4, findings: 37 },
  'oxlint/promise/valid-params': { seenIn: 1, findings: 19 },
  'oxlint/react/exhaustive-deps': { seenIn: 5, findings: 57 },
  'oxlint/react/forward-ref-uses-ref': { seenIn: 1, findings: 1 },
  'oxlint/react/iframe-missing-sandbox': { seenIn: 2, findings: 4 },
  'oxlint/react/jsx-key': { seenIn: 2, findings: 86 },
  'oxlint/react/jsx-no-script-url': { seenIn: 1, findings: 1 },
  'oxlint/react/no-children-prop': { seenIn: 1, findings: 8 },
  'oxlint/react/no-danger-with-children': { seenIn: 2, findings: 2 },
  'oxlint/react/no-did-mount-set-state': { seenIn: 1, findings: 1 },
  'oxlint/react/no-did-update-set-state': { seenIn: 2, findings: 11 },
  'oxlint/react/no-find-dom-node': { seenIn: 1, findings: 5 },
  'oxlint/react/no-string-refs': { seenIn: 1, findings: 3 },
  'oxlint/react/no-this-in-sfc': { seenIn: 1, findings: 29 },
  'oxlint/react/no-unsafe': { seenIn: 1, findings: 7 },
  'oxlint/react/no-unstable-nested-components': { seenIn: 3, findings: 32 },
  'oxlint/react/react-in-jsx-scope': { seenIn: 4, findings: 3889 },
  'oxlint/react/style-prop-object': { seenIn: 3, findings: 27 },
  'oxlint/react/void-dom-elements-no-children': { seenIn: 1, findings: 1 },
  'oxlint/require-yield': { seenIn: 1, findings: 7 },
  'oxlint/typescript/no-confusing-non-null-assertion': { seenIn: 1, findings: 2 },
  'oxlint/typescript/no-duplicate-enum-values': { seenIn: 1, findings: 3 },
  'oxlint/typescript/no-explicit-any': { seenIn: 17, findings: 2699 },
  'oxlint/typescript/no-extra-non-null-assertion': { seenIn: 2, findings: 6 },
  'oxlint/typescript/no-extraneous-class': { seenIn: 7, findings: 32 },
  'oxlint/typescript/no-import-type-side-effects': { seenIn: 6, findings: 116 },
  'oxlint/typescript/no-non-null-asserted-optional-chain': { seenIn: 4, findings: 11 },
  'oxlint/typescript/no-unnecessary-parameter-property-assignment': { seenIn: 1, findings: 1 },
  'oxlint/typescript/no-unnecessary-type-constraint': { seenIn: 3, findings: 11 },
  'oxlint/typescript/no-useless-empty-export': { seenIn: 2, findings: 2 },
  'oxlint/typescript/no-wrapper-object-types': { seenIn: 4, findings: 22 },
  'oxlint/typescript/prefer-ts-expect-error': { seenIn: 10, findings: 415 },
  'oxlint/typescript/triple-slash-reference': { seenIn: 1, findings: 1 },
  'oxlint/unicorn/consistent-function-scoping': { seenIn: 16, findings: 1418 },
  'oxlint/unicorn/no-array-fill-with-reference-type': { seenIn: 1, findings: 1 },
  'oxlint/unicorn/no-empty-file': { seenIn: 5, findings: 11 },
  'oxlint/unicorn/no-instanceof-builtins': { seenIn: 2, findings: 27 },
  'oxlint/unicorn/no-new-array': { seenIn: 9, findings: 35 },
  'oxlint/unicorn/no-thenable': { seenIn: 4, findings: 16 },
  'oxlint/unicorn/no-useless-fallback-in-spread': { seenIn: 1, findings: 10 },
  'oxlint/unicorn/no-useless-spread': { seenIn: 5, findings: 10 },
  'oxlint/unicorn/prefer-add-event-listener': { seenIn: 11, findings: 89 },
  'oxlint/unicorn/prefer-string-starts-ends-with': { seenIn: 5, findings: 33 },
  'oxlint/unicorn/require-module-specifiers': { seenIn: 6, findings: 13 },
  'oxlint/unicorn/require-post-message-target-origin': { seenIn: 3, findings: 14 },
  'oxlint/valid-typeof': { seenIn: 1, findings: 1 },
  'oxlint/vitest/expect-expect': { seenIn: 5, findings: 206 },
  'oxlint/vitest/hoisted-apis-on-top': { seenIn: 1, findings: 1 },
  'oxlint/vitest/no-commented-out-tests': { seenIn: 2, findings: 7 },
  'oxlint/vitest/no-conditional-expect': { seenIn: 5, findings: 90 },
  'oxlint/vitest/no-conditional-tests': { seenIn: 3, findings: 11 },
  'oxlint/vitest/no-disabled-tests': { seenIn: 5, findings: 60 },
  'oxlint/vitest/no-standalone-expect': { seenIn: 4, findings: 26 },
  'oxlint/vitest/prefer-snapshot-hint': { seenIn: 1, findings: 19 },
  'oxlint/vitest/require-mock-type-parameters': { seenIn: 5, findings: 683 },
  'oxlint/vitest/require-to-throw-message': { seenIn: 5, findings: 49 },
  'oxlint/vitest/valid-describe-callback': { seenIn: 1, findings: 3 },
  'oxlint/vitest/valid-title': { seenIn: 5, findings: 174 },
  'oxlint/vitest/warn-todo': { seenIn: 1, findings: 1 },
  'tsc/type-error': { seenIn: 4, findings: 1488 },
}

export function prevalenceOf(ruleRefKey: string): Prevalence | null {
  return RULE_PREVALENCE[ruleRefKey] ?? null
}
