import { createHash } from 'node:crypto'
import { existsSync } from 'node:fs'
import { mkdir, rename, rm, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { HADOLINT_CHECKSUMS, HADOLINT_RELEASE_URL, HADOLINT_VERSION, hadolintAsset } from './release.ts'
import { hadolintBinaryName, hadolintCacheDir } from './resolve-binary.ts'

export type InstallHadolintOptions = {
  platform?: string
  arch?: string
  env?: Readonly<Record<string, string | undefined>>
  homeDir?: string
  /** Injected in tests. Production uses the global `fetch`. */
  fetch?: (url: string) => Promise<{ ok: boolean; status: number; arrayBuffer(): Promise<ArrayBuffer> }>
  /**
   * Injected in tests so the success path can be driven with locally generated bytes. Production
   * always uses `HADOLINT_CHECKSUMS`, and the *mismatch* path is exercised against that real table —
   * a suite that only ever supplied its own digests would prove the comparison runs, not that the
   * shipped digests are the ones being compared against.
   */
  checksums?: Readonly<Record<string, string>>
  signal?: AbortSignal
}

export type InstallHadolintResult = {
  readonly path: string
  readonly version: string
  /** True when the cache already held a binary and nothing was fetched. */
  readonly cached: boolean
}

export class HadolintInstallError extends Error {
  constructor(message: string, options?: { cause?: unknown }) {
    super(message, options)
    this.name = 'HadolintInstallError'
  }
}

/**
 * D3, implemented directly: download the pinned release, verify it against the digest upstream
 * published, and only then put it somewhere that will be executed.
 *
 * **Nothing on the check path ever calls this.** `Engine.availability` is filesystem-only and `run` is
 * only reached by an engine already reported available, so the only caller is `sgate engines install`.
 * That narrowing of D3's "downloaded on first use" is the same one the actionlint adapter makes and is
 * recorded in spec §13.5: *first use* and *availability* cannot both be the trigger, because
 * availability is what decides whether a use ever happens.
 *
 * **Simpler than the actionlint equivalent by one whole moving part.** hadolint publishes the
 * executable directly rather than inside an archive, so there is no tar reader here and no `.zip` to
 * be blocked on — which is why this adapter supports Windows x86_64 where actionlint's does not.
 *
 * **The digest is checked before anything is written, not after.** The bytes are hashed in memory and
 * a mismatch throws having created nothing; the verified binary then lands via a temporary file and a
 * `rename`, so a concurrent `resolveHadolintBinary` sees either no file or a complete, verified one.
 */
export async function installHadolint(options: InstallHadolintOptions = {}): Promise<InstallHadolintResult> {
  const platform = options.platform ?? process.platform
  const arch = options.arch ?? process.arch
  const fetchImpl = options.fetch ?? ((url: string) => fetch(url, options.signal === undefined ? {} : { signal: options.signal }))

  const asset = hadolintAsset(platform, arch)
  if (asset === undefined) {
    throw new HadolintInstallError(
      `no hadolint ${HADOLINT_VERSION} download is available for ${platform}/${arch}. ` +
        (platform === 'win32'
          ? 'Upstream builds no Windows arm64 binary. Install hadolint yourself and put it on PATH, or point SLOP_GATE_HADOLINT_PATH at it.'
          : 'Install hadolint yourself and put it on PATH, or point SLOP_GATE_HADOLINT_PATH at it.'),
    )
  }

  const expected = (options.checksums ?? HADOLINT_CHECKSUMS)[asset]
  if (expected === undefined) {
    // Unreachable while `HADOLINT_ASSETS` and `HADOLINT_CHECKSUMS` are transcribed from the same
    // upstream file, and asserted in release.test.ts — but an unverified download is exactly what this
    // module exists to refuse, so it refuses rather than trusting that invariant at run time.
    throw new HadolintInstallError(`no recorded SHA-256 for ${asset}; refusing to download an unverifiable binary`)
  }

  const directory = hadolintCacheDir({
    platform,
    ...(options.env === undefined ? {} : { env: options.env }),
    ...(options.homeDir === undefined ? {} : { homeDir: options.homeDir }),
  })
  const destination = join(directory, hadolintBinaryName(platform))
  if (existsSync(destination)) return { path: destination, version: HADOLINT_VERSION, cached: true }

  const url = `${HADOLINT_RELEASE_URL}/${asset}`
  let binary: Uint8Array
  try {
    const response = await fetchImpl(url)
    if (!response.ok) throw new HadolintInstallError(`${url} responded ${response.status}`)
    binary = new Uint8Array(await response.arrayBuffer())
  } catch (error) {
    if (error instanceof HadolintInstallError) throw error
    throw new HadolintInstallError(`could not download ${url}: ${error instanceof Error ? error.message : String(error)}`, {
      cause: error,
    })
  }

  const actual = createHash('sha256').update(binary).digest('hex')
  if (actual !== expected) {
    throw new HadolintInstallError(
      `checksum mismatch for ${asset}: expected ${expected}, got ${actual}. Nothing was written. ` +
        'Either the download was corrupted or the published asset changed — do not work around this by rerunning.',
    )
  }

  await mkdir(directory, { recursive: true })
  const staging = `${destination}.${process.pid}.partial`
  try {
    // `mode` at creation rather than a later `chmod`: the npm hadolint wrapper's second defect is
    // writing the binary 0644 and never chmodding it, so every Unix spawn fails EACCES.
    await writeFile(staging, binary, { mode: 0o755 })
    await rename(staging, destination)
  } catch (error) {
    await rm(staging, { force: true })
    throw new HadolintInstallError(`could not write ${destination}: ${error instanceof Error ? error.message : String(error)}`, {
      cause: error,
    })
  }

  return { path: destination, version: HADOLINT_VERSION, cached: false }
}
