import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import {
  absolutePrefixes,
  EngineError,
  hashJson,
  runEngineTool,
  toolVersion,
  type Engine,
  type EngineAvailability,
  type EngineConfigHandle,
  type EngineRuleSelection,
  type FileBatch,
  type RawDiagnostic,
  type RunContext,
} from '@misaon/slop-gate-core'
import { parseHadolintOutput, readHadolintFindings, stripPrefixes } from './parse.ts'
import { HADOLINT_PATH_ENV, resolveHadolintBinary, type HadolintResolution } from './resolve-binary.ts'

export {
  HADOLINT_ASSETS,
  HADOLINT_CHECKSUMS,
  HADOLINT_RELEASE_URL,
  HADOLINT_VERSION,
  hadolintAsset,
} from './release.ts'
export { HadolintInstallError, installHadolint, type InstallHadolintResult } from './install.ts'
export { instructionKeywordRange, parseHadolintOutput, readHadolintFindings, type HadolintFinding } from './parse.ts'
export {
  EMBEDDED_SHELLCHECK_PREFIX,
  HADOLINT_RULES,
  HADOLINT_RULE_IDS,
  SOURCE_EXCLUSIONS,
  conceptForEngineRuleId,
  type HadolintRuleId,
} from './rules.ts'
export {
  CACHE_DIR_ENV,
  HADOLINT_PATH_ENV,
  hadolintBinaryName,
  hadolintCacheDir,
  resolveHadolintBinary,
  type HadolintResolution,
  type HadolintSource,
} from './resolve-binary.ts'

const MAX_FINDINGS_EXIT_CODE = 1

export function createHadolintEngine(options: { binaryPath?: string } = {}): Engine {
  const selections = new Map<string, ReadonlySet<string>>()

  const resolution = (): HadolintResolution | undefined =>
    options.binaryPath === undefined ? resolveHadolintBinary() : { command: options.binaryPath, source: 'env' }

  const required = (): HadolintResolution => {
    const resolved = resolution()
    if (resolved === undefined) throw new EngineError('hadolint', unavailableReason())
    return resolved
  }

  return {
    id: 'hadolint',

    capabilities: {
      languages: ['dockerfile'],
      granularity: 'file',
      provides: [],
      fixes: false,
    },

    async availability(): Promise<EngineAvailability> {
      const resolved = resolution()
      if (resolved !== undefined) return { available: true }
      return { available: false, reason: unavailableReason(), install: 'sgate engines install hadolint' }
    },

    async version(cache) {
      return toolVersion({ command: required().command, prefixArgs: [] }, undefined, cache)
    },

    async materializeConfig(selection: EngineRuleSelection, context: RunContext) {
      const enabled = [...selection].filter(([, [level]]) => level !== 'off')
      const rulesetHash = hashJson(enabled.map(([rule, [level]]) => [rule, level]).sort())
      const path = join(context.tmpDir, `hadolint.${rulesetHash.slice(0, 12)}.yaml`)
      selections.set(path, new Set(enabled.map(([rule]) => rule)))
      await mkdir(context.tmpDir, { recursive: true })
      await writeFile(
        path,
        ['# Generated by slop-gate. Do not edit; it is deleted when the run ends.', 'failure-threshold: none', ''].join('\n'),
        'utf8',
      )
      return {
        path,
        rulesetHash,
        async dispose() {
          selections.delete(path)
        },
      } satisfies EngineConfigHandle
    },

    run(batch: FileBatch, handle: EngineConfigHandle, context: RunContext, signal: AbortSignal) {
      return execute(required(), batch, handle, context, signal, selections.get(handle.path) ?? new Set())
    },
  }
}

function unavailableReason(): string {
  return `hadolint was not found on PATH, in the slop-gate cache, or at ${HADOLINT_PATH_ENV}`
}

async function* execute(
  invocation: HadolintResolution,
  batch: FileBatch,
  handle: EngineConfigHandle,
  context: RunContext,
  signal: AbortSignal,
  selected: ReadonlySet<string>,
): AsyncIterable<RawDiagnostic> {
  if (batch.files.length === 0) return

  const args = ['-f', 'json', '--no-color', '-c', handle.path, ...batch.files.map((file) => join(context.rootDir, file.path))]

  const { stdout } = await runEngineTool({
    engine: 'hadolint',
    command: invocation.command,
    args,
    cwd: context.rootDir,
    signal,
    maxFindingsExitCode: MAX_FINDINGS_EXIT_CODE,
  })

  const findings = readHadolintFindings(stdout)
  const prefixes = await absolutePrefixes(context)

  const sources = new Map<string, string | undefined>()
  for (const finding of findings) {
    const file = stripPrefixes(finding.file, prefixes)
    if (file === '' || sources.has(file)) continue
    try {
      sources.set(file, await readFile(join(context.rootDir, file), 'utf8'))
    } catch {
      sources.set(file, undefined)
    }
  }

  yield* parseHadolintOutput(findings, {
    absolutePrefixes: prefixes,
    enabled: (rule) => selected.has(rule),
    readSource: (file) => sources.get(file),
  })
}
