// GENERATED FILE — do not edit by hand.
// Produced by scripts/generate-registry.ts from the live oxlint rule catalogue (`oxlint --rules --format json`).
// Regenerate: pnpm --filter @misaon/slop-gate-core generate:registry
// CI fails if this file would differ from a fresh regeneration (generate:registry:check).
import type { ConceptDefinition } from './catalogue.ts'

/**
 * One entry per mechanically-named concept a generated rule entry invents; `title` and
 * `description` are factual passthroughs of the source rule, not curated prose.
 *
 * `as const satisfies` and never a type annotation: `ConceptId` is `(typeof CONCEPTS)[number]['id']`,
 * so an annotation widens every id to `string` and collapses the union, erasing concept-id checking
 * everywhere it is used.
 */
export const GENERATED_CONCEPTS = [
  {
    id: 'correctness.no-misused-spread',
    group: 'correctness',
    title: 'typescript/no-misused-spread',
    description: 'Generated from oxlint\'s `typescript/no-misused-spread` rule (category: correctness). No Misused Spread.',
  },
  {
    id: 'correctness.unbound-method',
    group: 'correctness',
    title: 'typescript/unbound-method',
    description: 'Generated from oxlint\'s `typescript/unbound-method` rule (category: correctness). Unbound Method.',
  },
  {
    id: 'correctness.vitest-valid-expect',
    group: 'correctness',
    title: 'vitest/valid-expect',
    description: 'Generated from oxlint\'s `vitest/valid-expect` rule (category: correctness). Valid Expect.',
  },
  {
    id: 'nursery.no-restricted-exports',
    group: 'nursery',
    title: 'no-restricted-exports',
    description: 'Generated from oxlint\'s `eslint/no-restricted-exports` rule (category: nursery). No Restricted Exports.',
  },
  {
    id: 'nursery.no-undef',
    group: 'nursery',
    title: 'no-undef',
    description: 'Generated from oxlint\'s `eslint/no-undef` rule (category: nursery). No Undef.',
  },
  {
    id: 'nursery.no-unnecessary-condition',
    group: 'nursery',
    title: 'typescript/no-unnecessary-condition',
    description: 'Generated from oxlint\'s `typescript/no-unnecessary-condition` rule (category: nursery). No Unnecessary Condition.',
  },
  {
    id: 'nursery.no-unreachable-loop',
    group: 'nursery',
    title: 'no-unreachable-loop',
    description: 'Generated from oxlint\'s `eslint/no-unreachable-loop` rule (category: nursery). No Unreachable Loop.',
  },
  {
    id: 'nursery.prefer-optional-chain',
    group: 'nursery',
    title: 'typescript/prefer-optional-chain',
    description: 'Generated from oxlint\'s `typescript/prefer-optional-chain` rule (category: nursery). Prefer Optional Chain.',
  },
  {
    id: 'nursery.react-compiler',
    group: 'nursery',
    title: 'react/react-compiler',
    description: 'Generated from oxlint\'s `react/react-compiler` rule (category: nursery). React Compiler.',
  },
  {
    id: 'pedantic.accessor-pairs',
    group: 'pedantic',
    title: 'accessor-pairs',
    description: 'Generated from oxlint\'s `eslint/accessor-pairs` rule (category: pedantic). Accessor Pairs.',
  },
  {
    id: 'pedantic.consistent-assert',
    group: 'pedantic',
    title: 'unicorn/consistent-assert',
    description: 'Generated from oxlint\'s `unicorn/consistent-assert` rule (category: pedantic). Consistent Assert.',
  },
  {
    id: 'pedantic.escape-case',
    group: 'pedantic',
    title: 'unicorn/escape-case',
    description: 'Generated from oxlint\'s `unicorn/escape-case` rule (category: pedantic). Escape Case.',
  },
  {
    id: 'pedantic.eslint-no-lonely-if',
    group: 'pedantic',
    title: 'no-lonely-if',
    description: 'Generated from oxlint\'s `eslint/no-lonely-if` rule (category: pedantic). No Lonely If.',
  },
  {
    id: 'pedantic.eslint-no-negated-condition',
    group: 'pedantic',
    title: 'no-negated-condition',
    description: 'Generated from oxlint\'s `eslint/no-negated-condition` rule (category: pedantic). No Negated Condition.',
  },
  {
    id: 'pedantic.eslint-require-await',
    group: 'pedantic',
    title: 'require-await',
    description: 'Generated from oxlint\'s `eslint/require-await` rule (category: pedantic). Require Await.',
  },
  {
    id: 'pedantic.explicit-length-check',
    group: 'pedantic',
    title: 'unicorn/explicit-length-check',
    description: 'Generated from oxlint\'s `unicorn/explicit-length-check` rule (category: pedantic). Explicit Length Check.',
  },
  {
    id: 'pedantic.jest-no-conditional-in-test',
    group: 'pedantic',
    title: 'jest/no-conditional-in-test',
    description: 'Generated from oxlint\'s `jest/no-conditional-in-test` rule (category: pedantic). No Conditional In Test.',
  },
  {
    id: 'pedantic.max-classes-per-file',
    group: 'pedantic',
    title: 'max-classes-per-file',
    description: 'Generated from oxlint\'s `eslint/max-classes-per-file` rule (category: pedantic). Max Classes Per File.',
  },
  {
    id: 'pedantic.max-dependencies',
    group: 'pedantic',
    title: 'import/max-dependencies',
    description: 'Generated from oxlint\'s `import/max-dependencies` rule (category: pedantic). Max Dependencies.',
  },
  {
    id: 'pedantic.max-depth',
    group: 'pedantic',
    title: 'max-depth',
    description: 'Generated from oxlint\'s `eslint/max-depth` rule (category: pedantic). Max Depth.',
  },
  {
    id: 'pedantic.max-lines',
    group: 'pedantic',
    title: 'max-lines',
    description: 'Generated from oxlint\'s `eslint/max-lines` rule (category: pedantic). Max Lines.',
  },
  {
    id: 'pedantic.max-lines-per-function',
    group: 'pedantic',
    title: 'max-lines-per-function',
    description: 'Generated from oxlint\'s `eslint/max-lines-per-function` rule (category: pedantic). Max Lines Per Function.',
  },
  {
    id: 'pedantic.max-nested-callbacks',
    group: 'pedantic',
    title: 'max-nested-callbacks',
    description: 'Generated from oxlint\'s `eslint/max-nested-callbacks` rule (category: pedantic). Max Nested Callbacks.',
  },
  {
    id: 'pedantic.no-array-callback-reference',
    group: 'pedantic',
    title: 'unicorn/no-array-callback-reference',
    description: 'Generated from oxlint\'s `unicorn/no-array-callback-reference` rule (category: pedantic). No Array Callback Reference.',
  },
  {
    id: 'pedantic.no-confusing-void-expression',
    group: 'pedantic',
    title: 'typescript/no-confusing-void-expression',
    description: 'Generated from oxlint\'s `typescript/no-confusing-void-expression` rule (category: pedantic). No Confusing Void Expression.',
  },
  {
    id: 'pedantic.no-else-return',
    group: 'pedantic',
    title: 'no-else-return',
    description: 'Generated from oxlint\'s `eslint/no-else-return` rule (category: pedantic). No Else Return.',
  },
  {
    id: 'pedantic.no-immediate-mutation',
    group: 'pedantic',
    title: 'unicorn/no-immediate-mutation',
    description: 'Generated from oxlint\'s `unicorn/no-immediate-mutation` rule (category: pedantic). No Immediate Mutation.',
  },
  {
    id: 'pedantic.no-inline-comments',
    group: 'pedantic',
    title: 'no-inline-comments',
    description: 'Generated from oxlint\'s `eslint/no-inline-comments` rule (category: pedantic). No Inline Comments.',
  },
  {
    id: 'pedantic.no-loop-func',
    group: 'pedantic',
    title: 'no-loop-func',
    description: 'Generated from oxlint\'s `eslint/no-loop-func` rule (category: pedantic). No Loop Func.',
  },
  {
    id: 'pedantic.no-promise-executor-return',
    group: 'pedantic',
    title: 'no-promise-executor-return',
    description: 'Generated from oxlint\'s `eslint/no-promise-executor-return` rule (category: pedantic). No Promise Executor Return.',
  },
  {
    id: 'pedantic.no-unsafe-argument',
    group: 'pedantic',
    title: 'typescript/no-unsafe-argument',
    description: 'Generated from oxlint\'s `typescript/no-unsafe-argument` rule (category: pedantic). No Unsafe Argument.',
  },
  {
    id: 'pedantic.no-unsafe-assignment',
    group: 'pedantic',
    title: 'typescript/no-unsafe-assignment',
    description: 'Generated from oxlint\'s `typescript/no-unsafe-assignment` rule (category: pedantic). No Unsafe Assignment.',
  },
  {
    id: 'pedantic.no-unsafe-call',
    group: 'pedantic',
    title: 'typescript/no-unsafe-call',
    description: 'Generated from oxlint\'s `typescript/no-unsafe-call` rule (category: pedantic). No Unsafe Call.',
  },
  {
    id: 'pedantic.no-unsafe-member-access',
    group: 'pedantic',
    title: 'typescript/no-unsafe-member-access',
    description: 'Generated from oxlint\'s `typescript/no-unsafe-member-access` rule (category: pedantic). No Unsafe Member Access.',
  },
  {
    id: 'pedantic.no-unsafe-return',
    group: 'pedantic',
    title: 'typescript/no-unsafe-return',
    description: 'Generated from oxlint\'s `typescript/no-unsafe-return` rule (category: pedantic). No Unsafe Return.',
  },
  {
    id: 'pedantic.no-useless-undefined',
    group: 'pedantic',
    title: 'unicorn/no-useless-undefined',
    description: 'Generated from oxlint\'s `unicorn/no-useless-undefined` rule (category: pedantic). No Useless Undefined.',
  },
  {
    id: 'pedantic.no-warning-comments',
    group: 'pedantic',
    title: 'no-warning-comments',
    description: 'Generated from oxlint\'s `eslint/no-warning-comments` rule (category: pedantic). No Warning Comments.',
  },
  {
    id: 'pedantic.prefer-event-target',
    group: 'pedantic',
    title: 'unicorn/prefer-event-target',
    description: 'Generated from oxlint\'s `unicorn/prefer-event-target` rule (category: pedantic). Prefer Event Target.',
  },
  {
    id: 'pedantic.prefer-math-trunc',
    group: 'pedantic',
    title: 'unicorn/prefer-math-trunc',
    description: 'Generated from oxlint\'s `unicorn/prefer-math-trunc` rule (category: pedantic). Prefer Math Trunc.',
  },
  {
    id: 'pedantic.prefer-nullish-coalescing',
    group: 'pedantic',
    title: 'typescript/prefer-nullish-coalescing',
    description: 'Generated from oxlint\'s `typescript/prefer-nullish-coalescing` rule (category: pedantic). Prefer Nullish Coalescing.',
  },
  {
    id: 'pedantic.prefer-readonly-parameter-types',
    group: 'pedantic',
    title: 'typescript/prefer-readonly-parameter-types',
    description: 'Generated from oxlint\'s `typescript/prefer-readonly-parameter-types` rule (category: pedantic). Prefer Readonly Parameter Types.',
  },
  {
    id: 'pedantic.prefer-single-call',
    group: 'pedantic',
    title: 'unicorn/prefer-single-call',
    description: 'Generated from oxlint\'s `unicorn/prefer-single-call` rule (category: pedantic). Prefer Single Call.',
  },
  {
    id: 'pedantic.prefer-top-level-await',
    group: 'pedantic',
    title: 'unicorn/prefer-top-level-await',
    description: 'Generated from oxlint\'s `unicorn/prefer-top-level-await` rule (category: pedantic). Prefer Top Level Await.',
  },
  {
    id: 'pedantic.require-param',
    group: 'pedantic',
    title: 'jsdoc/require-param',
    description: 'Generated from oxlint\'s `jsdoc/require-param` rule (category: pedantic). Require Param.',
  },
  {
    id: 'pedantic.require-param-description',
    group: 'pedantic',
    title: 'jsdoc/require-param-description',
    description: 'Generated from oxlint\'s `jsdoc/require-param-description` rule (category: pedantic). Require Param Description.',
  },
  {
    id: 'pedantic.require-param-name',
    group: 'pedantic',
    title: 'jsdoc/require-param-name',
    description: 'Generated from oxlint\'s `jsdoc/require-param-name` rule (category: pedantic). Require Param Name.',
  },
  {
    id: 'pedantic.require-param-type',
    group: 'pedantic',
    title: 'jsdoc/require-param-type',
    description: 'Generated from oxlint\'s `jsdoc/require-param-type` rule (category: pedantic). Require Param Type.',
  },
  {
    id: 'pedantic.require-returns',
    group: 'pedantic',
    title: 'jsdoc/require-returns',
    description: 'Generated from oxlint\'s `jsdoc/require-returns` rule (category: pedantic). Require Returns.',
  },
  {
    id: 'pedantic.require-returns-description',
    group: 'pedantic',
    title: 'jsdoc/require-returns-description',
    description: 'Generated from oxlint\'s `jsdoc/require-returns-description` rule (category: pedantic). Require Returns Description.',
  },
  {
    id: 'pedantic.require-returns-type',
    group: 'pedantic',
    title: 'jsdoc/require-returns-type',
    description: 'Generated from oxlint\'s `jsdoc/require-returns-type` rule (category: pedantic). Require Returns Type.',
  },
  {
    id: 'pedantic.require-throws-type',
    group: 'pedantic',
    title: 'jsdoc/require-throws-type',
    description: 'Generated from oxlint\'s `jsdoc/require-throws-type` rule (category: pedantic). Require Throws Type.',
  },
  {
    id: 'pedantic.require-unicode-regexp',
    group: 'pedantic',
    title: 'require-unicode-regexp',
    description: 'Generated from oxlint\'s `eslint/require-unicode-regexp` rule (category: pedantic). Require Unicode Regexp.',
  },
  {
    id: 'pedantic.require-yields-type',
    group: 'pedantic',
    title: 'jsdoc/require-yields-type',
    description: 'Generated from oxlint\'s `jsdoc/require-yields-type` rule (category: pedantic). Require Yields Type.',
  },
  {
    id: 'pedantic.restrict-plus-operands',
    group: 'pedantic',
    title: 'typescript/restrict-plus-operands',
    description: 'Generated from oxlint\'s `typescript/restrict-plus-operands` rule (category: pedantic). Restrict Plus Operands.',
  },
  {
    id: 'pedantic.return-await',
    group: 'pedantic',
    title: 'typescript/return-await',
    description: 'Generated from oxlint\'s `typescript/return-await` rule (category: pedantic). Return Await.',
  },
  {
    id: 'pedantic.sort-vars',
    group: 'pedantic',
    title: 'sort-vars',
    description: 'Generated from oxlint\'s `eslint/sort-vars` rule (category: pedantic). Sort Vars.',
  },
  {
    id: 'pedantic.strict-boolean-expressions',
    group: 'pedantic',
    title: 'typescript/strict-boolean-expressions',
    description: 'Generated from oxlint\'s `typescript/strict-boolean-expressions` rule (category: pedantic). Strict Boolean Expressions.',
  },
  {
    id: 'pedantic.strict-void-return',
    group: 'pedantic',
    title: 'typescript/strict-void-return',
    description: 'Generated from oxlint\'s `typescript/strict-void-return` rule (category: pedantic). Strict Void Return.',
  },
  {
    id: 'pedantic.typescript-require-await',
    group: 'pedantic',
    title: 'typescript/require-await',
    description: 'Generated from oxlint\'s `typescript/require-await` rule (category: pedantic). Require Await.',
  },
  {
    id: 'pedantic.unicorn-no-lonely-if',
    group: 'pedantic',
    title: 'unicorn/no-lonely-if',
    description: 'Generated from oxlint\'s `unicorn/no-lonely-if` rule (category: pedantic). No Lonely If.',
  },
  {
    id: 'pedantic.unicorn-no-negated-condition',
    group: 'pedantic',
    title: 'unicorn/no-negated-condition',
    description: 'Generated from oxlint\'s `unicorn/no-negated-condition` rule (category: pedantic). No Negated Condition.',
  },
  {
    id: 'pedantic.vitest-no-conditional-in-test',
    group: 'pedantic',
    title: 'vitest/no-conditional-in-test',
    description: 'Generated from oxlint\'s `vitest/no-conditional-in-test` rule (category: pedantic). No Conditional In Test.',
  },
  {
    id: 'perf.jsx-no-jsx-as-prop',
    group: 'perf',
    title: 'react-perf/jsx-no-jsx-as-prop',
    description: 'Generated from oxlint\'s `react_perf/jsx-no-jsx-as-prop` rule (category: perf). Jsx No Jsx As Prop.',
  },
  {
    id: 'perf.jsx-no-new-array-as-prop',
    group: 'perf',
    title: 'react-perf/jsx-no-new-array-as-prop',
    description: 'Generated from oxlint\'s `react_perf/jsx-no-new-array-as-prop` rule (category: perf). Jsx No New Array As Prop.',
  },
  {
    id: 'perf.jsx-no-new-function-as-prop',
    group: 'perf',
    title: 'react-perf/jsx-no-new-function-as-prop',
    description: 'Generated from oxlint\'s `react_perf/jsx-no-new-function-as-prop` rule (category: perf). Jsx No New Function As Prop.',
  },
  {
    id: 'perf.jsx-no-new-object-as-prop',
    group: 'perf',
    title: 'react-perf/jsx-no-new-object-as-prop',
    description: 'Generated from oxlint\'s `react_perf/jsx-no-new-object-as-prop` rule (category: perf). Jsx No New Object As Prop.',
  },
  {
    id: 'perf.no-await-in-loop',
    group: 'perf',
    title: 'no-await-in-loop',
    description: 'Generated from oxlint\'s `eslint/no-await-in-loop` rule (category: perf). No Await In Loop.',
  },
  {
    id: 'perf.no-map-spread',
    group: 'perf',
    title: 'oxc/no-map-spread',
    description: 'Generated from oxlint\'s `oxc/no-map-spread` rule (category: perf). No Map Spread.',
  },
  {
    id: 'restriction.check-access',
    group: 'restriction',
    title: 'jsdoc/check-access',
    description: 'Generated from oxlint\'s `jsdoc/check-access` rule (category: restriction). Check Access.',
  },
  {
    id: 'restriction.class-methods-use-this',
    group: 'restriction',
    title: 'class-methods-use-this',
    description: 'Generated from oxlint\'s `eslint/class-methods-use-this` rule (category: restriction). Class Methods Use This.',
  },
  {
    id: 'restriction.complexity',
    group: 'restriction',
    title: 'complexity',
    description: 'Generated from oxlint\'s `eslint/complexity` rule (category: restriction). Complexity.',
  },
  {
    id: 'restriction.default-case',
    group: 'restriction',
    title: 'default-case',
    description: 'Generated from oxlint\'s `eslint/default-case` rule (category: restriction). Default Case.',
  },
  {
    id: 'restriction.empty-tags',
    group: 'restriction',
    title: 'jsdoc/empty-tags',
    description: 'Generated from oxlint\'s `jsdoc/empty-tags` rule (category: restriction). Empty Tags.',
  },
  {
    id: 'restriction.explicit-function-return-type',
    group: 'restriction',
    title: 'typescript/explicit-function-return-type',
    description: 'Generated from oxlint\'s `typescript/explicit-function-return-type` rule (category: restriction). Explicit Function Return Type.',
  },
  {
    id: 'restriction.explicit-member-accessibility',
    group: 'restriction',
    title: 'typescript/explicit-member-accessibility',
    description: 'Generated from oxlint\'s `typescript/explicit-member-accessibility` rule (category: restriction). Explicit Member Accessibility.',
  },
  {
    id: 'restriction.explicit-module-boundary-types',
    group: 'restriction',
    title: 'typescript/explicit-module-boundary-types',
    description: 'Generated from oxlint\'s `typescript/explicit-module-boundary-types` rule (category: restriction). Explicit Module Boundary Types.',
  },
  {
    id: 'restriction.extensions',
    group: 'restriction',
    title: 'import/extensions',
    description: 'Generated from oxlint\'s `import/extensions` rule (category: restriction). Extensions.',
  },
  {
    id: 'restriction.forbid-component-props',
    group: 'restriction',
    title: 'react/forbid-component-props',
    description: 'Generated from oxlint\'s `react/forbid-component-props` rule (category: restriction). Forbid Component Props.',
  },
  {
    id: 'restriction.forbid-dom-props',
    group: 'restriction',
    title: 'react/forbid-dom-props',
    description: 'Generated from oxlint\'s `react/forbid-dom-props` rule (category: restriction). Forbid Dom Props.',
  },
  {
    id: 'restriction.forbid-elements',
    group: 'restriction',
    title: 'react/forbid-elements',
    description: 'Generated from oxlint\'s `react/forbid-elements` rule (category: restriction). Forbid Elements.',
  },
  {
    id: 'restriction.import-style',
    group: 'restriction',
    title: 'unicorn/import-style',
    description: 'Generated from oxlint\'s `unicorn/import-style` rule (category: restriction). Import Style.',
  },
  {
    id: 'restriction.jsx-filename-extension',
    group: 'restriction',
    title: 'react/jsx-filename-extension',
    description: 'Generated from oxlint\'s `react/jsx-filename-extension` rule (category: restriction). Jsx Filename Extension.',
  },
  {
    id: 'restriction.jsx-no-literals',
    group: 'restriction',
    title: 'react/jsx-no-literals',
    description: 'Generated from oxlint\'s `react/jsx-no-literals` rule (category: restriction). Jsx No Literals.',
  },
  {
    id: 'restriction.max-props',
    group: 'restriction',
    title: 'vue/max-props',
    description: 'Generated from oxlint\'s `vue/max-props` rule (category: restriction). Max Props.',
  },
  {
    id: 'restriction.no-array-for-each',
    group: 'restriction',
    title: 'unicorn/no-array-for-each',
    description: 'Generated from oxlint\'s `unicorn/no-array-for-each` rule (category: restriction). No Array For Each.',
  },
  {
    id: 'restriction.no-array-reduce',
    group: 'restriction',
    title: 'unicorn/no-array-reduce',
    description: 'Generated from oxlint\'s `unicorn/no-array-reduce` rule (category: restriction). No Array Reduce.',
  },
  {
    id: 'restriction.no-async-await',
    group: 'restriction',
    title: 'oxc/no-async-await',
    description: 'Generated from oxlint\'s `oxc/no-async-await` rule (category: restriction). No Async Await.',
  },
  {
    id: 'restriction.no-barrel-file',
    group: 'restriction',
    title: 'oxc/no-barrel-file',
    description: 'Generated from oxlint\'s `oxc/no-barrel-file` rule (category: restriction). No Barrel File.',
  },
  {
    id: 'restriction.no-bitwise',
    group: 'restriction',
    title: 'no-bitwise',
    description: 'Generated from oxlint\'s `eslint/no-bitwise` rule (category: restriction). No Bitwise.',
  },
  {
    id: 'restriction.no-console',
    group: 'restriction',
    title: 'no-console',
    description: 'Generated from oxlint\'s `eslint/no-console` rule (category: restriction). No Console.',
  },
  {
    id: 'restriction.no-default-export',
    group: 'restriction',
    title: 'import/no-default-export',
    description: 'Generated from oxlint\'s `import/no-default-export` rule (category: restriction). No Default Export.',
  },
  {
    id: 'restriction.no-div-regex',
    group: 'restriction',
    title: 'no-div-regex',
    description: 'Generated from oxlint\'s `eslint/no-div-regex` rule (category: restriction). No Div Regex.',
  },
  {
    id: 'restriction.no-dynamic-delete',
    group: 'restriction',
    title: 'typescript/no-dynamic-delete',
    description: 'Generated from oxlint\'s `typescript/no-dynamic-delete` rule (category: restriction). No Dynamic Delete.',
  },
  {
    id: 'restriction.no-empty',
    group: 'restriction',
    title: 'no-empty',
    description: 'Generated from oxlint\'s `eslint/no-empty` rule (category: restriction). No Empty.',
  },
  {
    id: 'restriction.no-empty-function',
    group: 'restriction',
    title: 'no-empty-function',
    description: 'Generated from oxlint\'s `eslint/no-empty-function` rule (category: restriction). No Empty Function.',
  },
  {
    id: 'restriction.no-eq-null',
    group: 'restriction',
    title: 'no-eq-null',
    description: 'Generated from oxlint\'s `eslint/no-eq-null` rule (category: restriction). No Eq Null.',
  },
  {
    id: 'restriction.no-invalid-void-type',
    group: 'restriction',
    title: 'typescript/no-invalid-void-type',
    description: 'Generated from oxlint\'s `typescript/no-invalid-void-type` rule (category: restriction). No Invalid Void Type.',
  },
  {
    id: 'restriction.no-multi-comp',
    group: 'restriction',
    title: 'react/no-multi-comp',
    description: 'Generated from oxlint\'s `react/no-multi-comp` rule (category: restriction). No Multi Comp.',
  },
  {
    id: 'restriction.no-non-null-assertion',
    group: 'restriction',
    title: 'typescript/no-non-null-assertion',
    description: 'Generated from oxlint\'s `typescript/no-non-null-assertion` rule (category: restriction). No Non Null Assertion.',
  },
  {
    id: 'restriction.no-optional-chaining',
    group: 'restriction',
    title: 'oxc/no-optional-chaining',
    description: 'Generated from oxlint\'s `oxc/no-optional-chaining` rule (category: restriction). No Optional Chaining.',
  },
  {
    id: 'restriction.no-param-reassign',
    group: 'restriction',
    title: 'no-param-reassign',
    description: 'Generated from oxlint\'s `eslint/no-param-reassign` rule (category: restriction). No Param Reassign.',
  },
  {
    id: 'restriction.no-plusplus',
    group: 'restriction',
    title: 'no-plusplus',
    description: 'Generated from oxlint\'s `eslint/no-plusplus` rule (category: restriction). No Plusplus.',
  },
  {
    id: 'restriction.no-process-env',
    group: 'restriction',
    title: 'node/no-process-env',
    description: 'Generated from oxlint\'s `node/no-process-env` rule (category: restriction). No Process Env.',
  },
  {
    id: 'restriction.no-process-exit',
    group: 'restriction',
    title: 'unicorn/no-process-exit',
    description: 'Generated from oxlint\'s `unicorn/no-process-exit` rule (category: restriction). No Process Exit.',
  },
  {
    id: 'restriction.no-relative-parent-imports',
    group: 'restriction',
    title: 'import/no-relative-parent-imports',
    description: 'Generated from oxlint\'s `import/no-relative-parent-imports` rule (category: restriction). No Relative Parent Imports.',
  },
  {
    id: 'restriction.no-rest-spread-properties',
    group: 'restriction',
    title: 'oxc/no-rest-spread-properties',
    description: 'Generated from oxlint\'s `oxc/no-rest-spread-properties` rule (category: restriction). No Rest Spread Properties.',
  },
  {
    id: 'restriction.no-restricted-globals',
    group: 'restriction',
    title: 'no-restricted-globals',
    description: 'Generated from oxlint\'s `eslint/no-restricted-globals` rule (category: restriction). No Restricted Globals.',
  },
  {
    id: 'restriction.no-restricted-imports',
    group: 'restriction',
    title: 'no-restricted-imports',
    description: 'Generated from oxlint\'s `eslint/no-restricted-imports` rule (category: restriction). No Restricted Imports.',
  },
  {
    id: 'restriction.no-restricted-properties',
    group: 'restriction',
    title: 'no-restricted-properties',
    description: 'Generated from oxlint\'s `eslint/no-restricted-properties` rule (category: restriction). No Restricted Properties.',
  },
  {
    id: 'restriction.no-restricted-types',
    group: 'restriction',
    title: 'typescript/no-restricted-types',
    description: 'Generated from oxlint\'s `typescript/no-restricted-types` rule (category: restriction). No Restricted Types.',
  },
  {
    id: 'restriction.no-top-level-await',
    group: 'restriction',
    title: 'node/no-top-level-await',
    description: 'Generated from oxlint\'s `node/no-top-level-await` rule (category: restriction). No Top Level Await.',
  },
  {
    id: 'restriction.no-undefined',
    group: 'restriction',
    title: 'no-undefined',
    description: 'Generated from oxlint\'s `eslint/no-undefined` rule (category: restriction). No Undefined.',
  },
  {
    id: 'restriction.no-unknown-property',
    group: 'restriction',
    title: 'react/no-unknown-property',
    description: 'Generated from oxlint\'s `react/no-unknown-property` rule (category: restriction). No Unknown Property.',
  },
  {
    id: 'restriction.no-use-before-define',
    group: 'restriction',
    title: 'no-use-before-define',
    description: 'Generated from oxlint\'s `eslint/no-use-before-define` rule (category: restriction). No Use Before Define.',
  },
  {
    id: 'restriction.no-void',
    group: 'restriction',
    title: 'no-void',
    description: 'Generated from oxlint\'s `eslint/no-void` rule (category: restriction). No Void.',
  },
  {
    id: 'restriction.non-nullable-type-assertion-style',
    group: 'restriction',
    title: 'typescript/non-nullable-type-assertion-style',
    description: 'Generated from oxlint\'s `typescript/non-nullable-type-assertion-style` rule (category: restriction). Non Nullable Type Assertion Style.',
  },
  {
    id: 'restriction.only-export-components',
    group: 'restriction',
    title: 'react/only-export-components',
    description: 'Generated from oxlint\'s `react/only-export-components` rule (category: restriction). Only Export Components.',
  },
  {
    id: 'restriction.prefer-function-component',
    group: 'restriction',
    title: 'react/prefer-function-component',
    description: 'Generated from oxlint\'s `react/prefer-function-component` rule (category: restriction). Prefer Function Component.',
  },
  {
    id: 'restriction.prefer-module',
    group: 'restriction',
    title: 'unicorn/prefer-module',
    description: 'Generated from oxlint\'s `unicorn/prefer-module` rule (category: restriction). Prefer Module.',
  },
  {
    id: 'restriction.promise-function-async',
    group: 'restriction',
    title: 'typescript/promise-function-async',
    description: 'Generated from oxlint\'s `typescript/promise-function-async` rule (category: restriction). Promise Function Async.',
  },
  {
    id: 'restriction.require-test-timeout',
    group: 'restriction',
    title: 'vitest/require-test-timeout',
    description: 'Generated from oxlint\'s `vitest/require-test-timeout` rule (category: restriction). Require Test Timeout.',
  },
  {
    id: 'restriction.unambiguous',
    group: 'restriction',
    title: 'import/unambiguous',
    description: 'Generated from oxlint\'s `import/unambiguous` rule (category: restriction). Unambiguous.',
  },
  {
    id: 'restriction.use-unknown-in-catch-callback-variable',
    group: 'restriction',
    title: 'typescript/use-unknown-in-catch-callback-variable',
    description: 'Generated from oxlint\'s `typescript/use-unknown-in-catch-callback-variable` rule (category: restriction). Use Unknown In Catch Callback Variable.',
  },
  {
    id: 'style.array-type',
    group: 'style',
    title: 'typescript/array-type',
    description: 'Generated from oxlint\'s `typescript/array-type` rule (category: style). Array Type.',
  },
  {
    id: 'style.arrow-body-style',
    group: 'style',
    title: 'arrow-body-style',
    description: 'Generated from oxlint\'s `eslint/arrow-body-style` rule (category: style). Arrow Body Style.',
  },
  {
    id: 'style.avoid-new',
    group: 'style',
    title: 'promise/avoid-new',
    description: 'Generated from oxlint\'s `promise/avoid-new` rule (category: style). Avoid New.',
  },
  {
    id: 'style.ban-tslint-comment',
    group: 'style',
    title: 'typescript/ban-tslint-comment',
    description: 'Generated from oxlint\'s `typescript/ban-tslint-comment` rule (category: style). Ban Tslint Comment.',
  },
  {
    id: 'style.callback-return',
    group: 'style',
    title: 'node/callback-return',
    description: 'Generated from oxlint\'s `node/callback-return` rule (category: style). Callback Return.',
  },
  {
    id: 'style.capitalized-comments',
    group: 'style',
    title: 'capitalized-comments',
    description: 'Generated from oxlint\'s `eslint/capitalized-comments` rule (category: style). Capitalized Comments.',
  },
  {
    id: 'style.catch-error-name',
    group: 'style',
    title: 'unicorn/catch-error-name',
    description: 'Generated from oxlint\'s `unicorn/catch-error-name` rule (category: style). Catch Error Name.',
  },
  {
    id: 'style.class-literal-property-style',
    group: 'style',
    title: 'typescript/class-literal-property-style',
    description: 'Generated from oxlint\'s `typescript/class-literal-property-style` rule (category: style). Class Literal Property Style.',
  },
  {
    id: 'style.component-definition-name-casing',
    group: 'style',
    title: 'vue/component-definition-name-casing',
    description: 'Generated from oxlint\'s `vue/component-definition-name-casing` rule (category: style). Component Definition Name Casing.',
  },
  {
    id: 'style.consistent-each-for',
    group: 'style',
    title: 'vitest/consistent-each-for',
    description: 'Generated from oxlint\'s `vitest/consistent-each-for` rule (category: style). Consistent Each For.',
  },
  {
    id: 'style.consistent-generic-constructors',
    group: 'style',
    title: 'typescript/consistent-generic-constructors',
    description: 'Generated from oxlint\'s `typescript/consistent-generic-constructors` rule (category: style). Consistent Generic Constructors.',
  },
  {
    id: 'style.consistent-indexed-object-style',
    group: 'style',
    title: 'typescript/consistent-indexed-object-style',
    description: 'Generated from oxlint\'s `typescript/consistent-indexed-object-style` rule (category: style). Consistent Indexed Object Style.',
  },
  {
    id: 'style.consistent-template-literal-escape',
    group: 'style',
    title: 'unicorn/consistent-template-literal-escape',
    description: 'Generated from oxlint\'s `unicorn/consistent-template-literal-escape` rule (category: style). Consistent Template Literal Escape.',
  },
  {
    id: 'style.consistent-test-filename',
    group: 'style',
    title: 'vitest/consistent-test-filename',
    description: 'Generated from oxlint\'s `vitest/consistent-test-filename` rule (category: style). Consistent Test Filename.',
  },
  {
    id: 'style.consistent-type-assertions',
    group: 'style',
    title: 'typescript/consistent-type-assertions',
    description: 'Generated from oxlint\'s `typescript/consistent-type-assertions` rule (category: style). Consistent Type Assertions.',
  },
  {
    id: 'style.consistent-type-definitions',
    group: 'style',
    title: 'typescript/consistent-type-definitions',
    description: 'Generated from oxlint\'s `typescript/consistent-type-definitions` rule (category: style). Consistent Type Definitions.',
  },
  {
    id: 'style.consistent-type-exports',
    group: 'style',
    title: 'typescript/consistent-type-exports',
    description: 'Generated from oxlint\'s `typescript/consistent-type-exports` rule (category: style). Consistent Type Exports.',
  },
  {
    id: 'style.consistent-type-imports',
    group: 'style',
    title: 'typescript/consistent-type-imports',
    description: 'Generated from oxlint\'s `typescript/consistent-type-imports` rule (category: style). Consistent Type Imports.',
  },
  {
    id: 'style.consistent-type-specifier-style',
    group: 'style',
    title: 'import/consistent-type-specifier-style',
    description: 'Generated from oxlint\'s `import/consistent-type-specifier-style` rule (category: style). Consistent Type Specifier Style.',
  },
  {
    id: 'style.consistent-vitest-vi',
    group: 'style',
    title: 'vitest/consistent-vitest-vi',
    description: 'Generated from oxlint\'s `vitest/consistent-vitest-vi` rule (category: style). Consistent Vitest Vi.',
  },
  {
    id: 'style.curly',
    group: 'style',
    title: 'curly',
    description: 'Generated from oxlint\'s `eslint/curly` rule (category: style). Curly.',
  },
  {
    id: 'style.custom-error-definition',
    group: 'style',
    title: 'unicorn/custom-error-definition',
    description: 'Generated from oxlint\'s `unicorn/custom-error-definition` rule (category: style). Custom Error Definition.',
  },
  {
    id: 'style.define-emits-declaration',
    group: 'style',
    title: 'vue/define-emits-declaration',
    description: 'Generated from oxlint\'s `vue/define-emits-declaration` rule (category: style). Define Emits Declaration.',
  },
  {
    id: 'style.define-props-declaration',
    group: 'style',
    title: 'vue/define-props-declaration',
    description: 'Generated from oxlint\'s `vue/define-props-declaration` rule (category: style). Define Props Declaration.',
  },
  {
    id: 'style.define-props-destructuring',
    group: 'style',
    title: 'vue/define-props-destructuring',
    description: 'Generated from oxlint\'s `vue/define-props-destructuring` rule (category: style). Define Props Destructuring.',
  },
  {
    id: 'style.dot-notation',
    group: 'style',
    title: 'typescript/dot-notation',
    description: 'Generated from oxlint\'s `typescript/dot-notation` rule (category: style). Dot Notation.',
  },
  {
    id: 'style.empty-brace-spaces',
    group: 'style',
    title: 'unicorn/empty-brace-spaces',
    description: 'Generated from oxlint\'s `unicorn/empty-brace-spaces` rule (category: style). Empty Brace Spaces.',
  },
  {
    id: 'style.eslint-no-nested-ternary',
    group: 'style',
    title: 'no-nested-ternary',
    description: 'Generated from oxlint\'s `eslint/no-nested-ternary` rule (category: style). No Nested Ternary.',
  },
  {
    id: 'style.exports-last',
    group: 'style',
    title: 'import/exports-last',
    description: 'Generated from oxlint\'s `import/exports-last` rule (category: style). Exports Last.',
  },
  {
    id: 'style.exports-style',
    group: 'style',
    title: 'node/exports-style',
    description: 'Generated from oxlint\'s `node/exports-style` rule (category: style). Exports Style.',
  },
  {
    id: 'style.filename-case',
    group: 'style',
    title: 'unicorn/filename-case',
    description: 'Generated from oxlint\'s `unicorn/filename-case` rule (category: style). Filename Case.',
  },
  {
    id: 'style.first',
    group: 'style',
    title: 'import/first',
    description: 'Generated from oxlint\'s `import/first` rule (category: style). First.',
  },
  {
    id: 'style.func-name-matching',
    group: 'style',
    title: 'func-name-matching',
    description: 'Generated from oxlint\'s `eslint/func-name-matching` rule (category: style). Func Name Matching.',
  },
  {
    id: 'style.func-names',
    group: 'style',
    title: 'func-names',
    description: 'Generated from oxlint\'s `eslint/func-names` rule (category: style). Func Names.',
  },
  {
    id: 'style.func-style',
    group: 'style',
    title: 'func-style',
    description: 'Generated from oxlint\'s `eslint/func-style` rule (category: style). Func Style.',
  },
  {
    id: 'style.function-component-definition',
    group: 'style',
    title: 'react/function-component-definition',
    description: 'Generated from oxlint\'s `react/function-component-definition` rule (category: style). Function Component Definition.',
  },
  {
    id: 'style.global-require',
    group: 'style',
    title: 'node/global-require',
    description: 'Generated from oxlint\'s `node/global-require` rule (category: style). Global Require.',
  },
  {
    id: 'style.group-exports',
    group: 'style',
    title: 'import/group-exports',
    description: 'Generated from oxlint\'s `import/group-exports` rule (category: style). Group Exports.',
  },
  {
    id: 'style.grouped-accessor-pairs',
    group: 'style',
    title: 'grouped-accessor-pairs',
    description: 'Generated from oxlint\'s `eslint/grouped-accessor-pairs` rule (category: style). Grouped Accessor Pairs.',
  },
  {
    id: 'style.hook-use-state',
    group: 'style',
    title: 'react/hook-use-state',
    description: 'Generated from oxlint\'s `react/hook-use-state` rule (category: style). Hook Use State.',
  },
  {
    id: 'style.id-denylist',
    group: 'style',
    title: 'id-denylist',
    description: 'Generated from oxlint\'s `eslint/id-denylist` rule (category: style). Id Denylist.',
  },
  {
    id: 'style.id-length',
    group: 'style',
    title: 'id-length',
    description: 'Generated from oxlint\'s `eslint/id-length` rule (category: style). Id Length.',
  },
  {
    id: 'style.id-match',
    group: 'style',
    title: 'id-match',
    description: 'Generated from oxlint\'s `eslint/id-match` rule (category: style). Id Match.',
  },
  {
    id: 'style.init-declarations',
    group: 'style',
    title: 'init-declarations',
    description: 'Generated from oxlint\'s `eslint/init-declarations` rule (category: style). Init Declarations.',
  },
  {
    id: 'style.jest-consistent-test-it',
    group: 'style',
    title: 'jest/consistent-test-it',
    description: 'Generated from oxlint\'s `jest/consistent-test-it` rule (category: style). Consistent Test It.',
  },
  {
    id: 'style.jest-max-expects',
    group: 'style',
    title: 'jest/max-expects',
    description: 'Generated from oxlint\'s `jest/max-expects` rule (category: style). Max Expects.',
  },
  {
    id: 'style.jest-max-nested-describe',
    group: 'style',
    title: 'jest/max-nested-describe',
    description: 'Generated from oxlint\'s `jest/max-nested-describe` rule (category: style). Max Nested Describe.',
  },
  {
    id: 'style.jest-no-hooks',
    group: 'style',
    title: 'jest/no-hooks',
    description: 'Generated from oxlint\'s `jest/no-hooks` rule (category: style). No Hooks.',
  },
  {
    id: 'style.jest-no-interpolation-in-snapshots',
    group: 'style',
    title: 'jest/no-interpolation-in-snapshots',
    description: 'Generated from oxlint\'s `jest/no-interpolation-in-snapshots` rule (category: style). No Interpolation In Snapshots.',
  },
  {
    id: 'style.jest-no-large-snapshots',
    group: 'style',
    title: 'jest/no-large-snapshots',
    description: 'Generated from oxlint\'s `jest/no-large-snapshots` rule (category: style). No Large Snapshots.',
  },
  {
    id: 'style.jest-no-restricted-matchers',
    group: 'style',
    title: 'jest/no-restricted-matchers',
    description: 'Generated from oxlint\'s `jest/no-restricted-matchers` rule (category: style). No Restricted Matchers.',
  },
  {
    id: 'style.jest-no-test-prefixes',
    group: 'style',
    title: 'jest/no-test-prefixes',
    description: 'Generated from oxlint\'s `jest/no-test-prefixes` rule (category: style). No Test Prefixes.',
  },
  {
    id: 'style.jest-no-unneeded-async-expect-function',
    group: 'style',
    title: 'jest/no-unneeded-async-expect-function',
    description: 'Generated from oxlint\'s `jest/no-unneeded-async-expect-function` rule (category: style). No Unneeded Async Expect Function.',
  },
  {
    id: 'style.jest-padding-around-after-all-blocks',
    group: 'style',
    title: 'jest/padding-around-after-all-blocks',
    description: 'Generated from oxlint\'s `jest/padding-around-after-all-blocks` rule (category: style). Padding Around After All Blocks.',
  },
  {
    id: 'style.jest-padding-around-test-blocks',
    group: 'style',
    title: 'jest/padding-around-test-blocks',
    description: 'Generated from oxlint\'s `jest/padding-around-test-blocks` rule (category: style). Padding Around Test Blocks.',
  },
  {
    id: 'style.jest-prefer-called-with',
    group: 'style',
    title: 'jest/prefer-called-with',
    description: 'Generated from oxlint\'s `jest/prefer-called-with` rule (category: style). Prefer Called With.',
  },
  {
    id: 'style.jest-prefer-comparison-matcher',
    group: 'style',
    title: 'jest/prefer-comparison-matcher',
    description: 'Generated from oxlint\'s `jest/prefer-comparison-matcher` rule (category: style). Prefer Comparison Matcher.',
  },
  {
    id: 'style.jest-prefer-each',
    group: 'style',
    title: 'jest/prefer-each',
    description: 'Generated from oxlint\'s `jest/prefer-each` rule (category: style). Prefer Each.',
  },
  {
    id: 'style.jest-prefer-equality-matcher',
    group: 'style',
    title: 'jest/prefer-equality-matcher',
    description: 'Generated from oxlint\'s `jest/prefer-equality-matcher` rule (category: style). Prefer Equality Matcher.',
  },
  {
    id: 'style.jest-prefer-expect-assertions',
    group: 'style',
    title: 'jest/prefer-expect-assertions',
    description: 'Generated from oxlint\'s `jest/prefer-expect-assertions` rule (category: style). Prefer Expect Assertions.',
  },
  {
    id: 'style.jest-prefer-expect-resolves',
    group: 'style',
    title: 'jest/prefer-expect-resolves',
    description: 'Generated from oxlint\'s `jest/prefer-expect-resolves` rule (category: style). Prefer Expect Resolves.',
  },
  {
    id: 'style.jest-prefer-hooks-in-order',
    group: 'style',
    title: 'jest/prefer-hooks-in-order',
    description: 'Generated from oxlint\'s `jest/prefer-hooks-in-order` rule (category: style). Prefer Hooks In Order.',
  },
  {
    id: 'style.jest-prefer-hooks-on-top',
    group: 'style',
    title: 'jest/prefer-hooks-on-top',
    description: 'Generated from oxlint\'s `jest/prefer-hooks-on-top` rule (category: style). Prefer Hooks On Top.',
  },
  {
    id: 'style.jest-prefer-lowercase-title',
    group: 'style',
    title: 'jest/prefer-lowercase-title',
    description: 'Generated from oxlint\'s `jest/prefer-lowercase-title` rule (category: style). Prefer Lowercase Title.',
  },
  {
    id: 'style.jest-prefer-mock-promise-shorthand',
    group: 'style',
    title: 'jest/prefer-mock-promise-shorthand',
    description: 'Generated from oxlint\'s `jest/prefer-mock-promise-shorthand` rule (category: style). Prefer Mock Promise Shorthand.',
  },
  {
    id: 'style.jest-prefer-mock-return-shorthand',
    group: 'style',
    title: 'jest/prefer-mock-return-shorthand',
    description: 'Generated from oxlint\'s `jest/prefer-mock-return-shorthand` rule (category: style). Prefer Mock Return Shorthand.',
  },
  {
    id: 'style.jest-prefer-spy-on',
    group: 'style',
    title: 'jest/prefer-spy-on',
    description: 'Generated from oxlint\'s `jest/prefer-spy-on` rule (category: style). Prefer Spy On.',
  },
  {
    id: 'style.jest-prefer-strict-equal',
    group: 'style',
    title: 'jest/prefer-strict-equal',
    description: 'Generated from oxlint\'s `jest/prefer-strict-equal` rule (category: style). Prefer Strict Equal.',
  },
  {
    id: 'style.jest-prefer-to-be',
    group: 'style',
    title: 'jest/prefer-to-be',
    description: 'Generated from oxlint\'s `jest/prefer-to-be` rule (category: style). Prefer To Be.',
  },
  {
    id: 'style.jest-prefer-to-contain',
    group: 'style',
    title: 'jest/prefer-to-contain',
    description: 'Generated from oxlint\'s `jest/prefer-to-contain` rule (category: style). Prefer To Contain.',
  },
  {
    id: 'style.jest-prefer-to-have-been-called-times',
    group: 'style',
    title: 'jest/prefer-to-have-been-called-times',
    description: 'Generated from oxlint\'s `jest/prefer-to-have-been-called-times` rule (category: style). Prefer To Have Been Called Times.',
  },
  {
    id: 'style.jest-prefer-to-have-length',
    group: 'style',
    title: 'jest/prefer-to-have-length',
    description: 'Generated from oxlint\'s `jest/prefer-to-have-length` rule (category: style). Prefer To Have Length.',
  },
  {
    id: 'style.jest-prefer-todo',
    group: 'style',
    title: 'jest/prefer-todo',
    description: 'Generated from oxlint\'s `jest/prefer-todo` rule (category: style). Prefer Todo.',
  },
  {
    id: 'style.jest-require-hook',
    group: 'style',
    title: 'jest/require-hook',
    description: 'Generated from oxlint\'s `jest/require-hook` rule (category: style). Require Hook.',
  },
  {
    id: 'style.jest-require-top-level-describe',
    group: 'style',
    title: 'jest/require-top-level-describe',
    description: 'Generated from oxlint\'s `jest/require-top-level-describe` rule (category: style). Require Top Level Describe.',
  },
  {
    id: 'style.jsx-boolean-value',
    group: 'style',
    title: 'react/jsx-boolean-value',
    description: 'Generated from oxlint\'s `react/jsx-boolean-value` rule (category: style). Jsx Boolean Value.',
  },
  {
    id: 'style.jsx-curly-brace-presence',
    group: 'style',
    title: 'react/jsx-curly-brace-presence',
    description: 'Generated from oxlint\'s `react/jsx-curly-brace-presence` rule (category: style). Jsx Curly Brace Presence.',
  },
  {
    id: 'style.jsx-fragments',
    group: 'style',
    title: 'react/jsx-fragments',
    description: 'Generated from oxlint\'s `react/jsx-fragments` rule (category: style). Jsx Fragments.',
  },
  {
    id: 'style.jsx-handler-names',
    group: 'style',
    title: 'react/jsx-handler-names',
    description: 'Generated from oxlint\'s `react/jsx-handler-names` rule (category: style). Jsx Handler Names.',
  },
  {
    id: 'style.jsx-max-depth',
    group: 'style',
    title: 'react/jsx-max-depth',
    description: 'Generated from oxlint\'s `react/jsx-max-depth` rule (category: style). Jsx Max Depth.',
  },
  {
    id: 'style.jsx-pascal-case',
    group: 'style',
    title: 'react/jsx-pascal-case',
    description: 'Generated from oxlint\'s `react/jsx-pascal-case` rule (category: style). Jsx Pascal Case.',
  },
  {
    id: 'style.jsx-props-no-spreading',
    group: 'style',
    title: 'react/jsx-props-no-spreading',
    description: 'Generated from oxlint\'s `react/jsx-props-no-spreading` rule (category: style). Jsx Props No Spreading.',
  },
  {
    id: 'style.max-nested-calls',
    group: 'style',
    title: 'unicorn/max-nested-calls',
    description: 'Generated from oxlint\'s `unicorn/max-nested-calls` rule (category: style). Max Nested Calls.',
  },
  {
    id: 'style.max-params',
    group: 'style',
    title: 'max-params',
    description: 'Generated from oxlint\'s `eslint/max-params` rule (category: style). Max Params.',
  },
  {
    id: 'style.max-statements',
    group: 'style',
    title: 'max-statements',
    description: 'Generated from oxlint\'s `eslint/max-statements` rule (category: style). Max Statements.',
  },
  {
    id: 'style.method-signature-style',
    group: 'style',
    title: 'typescript/method-signature-style',
    description: 'Generated from oxlint\'s `typescript/method-signature-style` rule (category: style). Method Signature Style.',
  },
  {
    id: 'style.new-cap',
    group: 'style',
    title: 'new-cap',
    description: 'Generated from oxlint\'s `eslint/new-cap` rule (category: style). New Cap.',
  },
  {
    id: 'style.newline-after-import',
    group: 'style',
    title: 'import/newline-after-import',
    description: 'Generated from oxlint\'s `import/newline-after-import` rule (category: style). Newline After Import.',
  },
  {
    id: 'style.next-tick-style',
    group: 'style',
    title: 'vue/next-tick-style',
    description: 'Generated from oxlint\'s `vue/next-tick-style` rule (category: style). Next Tick Style.',
  },
  {
    id: 'style.no-anonymous-default-export',
    group: 'style',
    title: 'import/no-anonymous-default-export',
    description: 'Generated from oxlint\'s `import/no-anonymous-default-export` rule (category: style). No Anonymous Default Export.',
  },
  {
    id: 'style.no-await-expression-member',
    group: 'style',
    title: 'unicorn/no-await-expression-member',
    description: 'Generated from oxlint\'s `unicorn/no-await-expression-member` rule (category: style). No Await Expression Member.',
  },
  {
    id: 'style.no-console-spaces',
    group: 'style',
    title: 'unicorn/no-console-spaces',
    description: 'Generated from oxlint\'s `unicorn/no-console-spaces` rule (category: style). No Console Spaces.',
  },
  {
    id: 'style.no-continue',
    group: 'style',
    title: 'no-continue',
    description: 'Generated from oxlint\'s `eslint/no-continue` rule (category: style). No Continue.',
  },
  {
    id: 'style.no-done-callback',
    group: 'style',
    title: 'jest/no-done-callback',
    description: 'Generated from oxlint\'s `jest/no-done-callback` rule (category: style). No Done Callback.',
  },
  {
    id: 'style.no-duplicate-imports',
    group: 'style',
    title: 'no-duplicate-imports',
    description: 'Generated from oxlint\'s `eslint/no-duplicate-imports` rule (category: style). No Duplicate Imports.',
  },
  {
    id: 'style.no-duplicates',
    group: 'style',
    title: 'import/no-duplicates',
    description: 'Generated from oxlint\'s `import/no-duplicates` rule (category: style). No Duplicates.',
  },
  {
    id: 'style.no-extra-label',
    group: 'style',
    title: 'no-extra-label',
    description: 'Generated from oxlint\'s `eslint/no-extra-label` rule (category: style). No Extra Label.',
  },
  {
    id: 'style.no-implicit-coercion',
    group: 'style',
    title: 'no-implicit-coercion',
    description: 'Generated from oxlint\'s `eslint/no-implicit-coercion` rule (category: style). No Implicit Coercion.',
  },
  {
    id: 'style.no-importing-vitest-globals',
    group: 'style',
    title: 'vitest/no-importing-vitest-globals',
    description: 'Generated from oxlint\'s `vitest/no-importing-vitest-globals` rule (category: style). No Importing Vitest Globals.',
  },
  {
    id: 'style.no-inferrable-types',
    group: 'style',
    title: 'typescript/no-inferrable-types',
    description: 'Generated from oxlint\'s `typescript/no-inferrable-types` rule (category: style). No Inferrable Types.',
  },
  {
    id: 'style.no-label-var',
    group: 'style',
    title: 'no-label-var',
    description: 'Generated from oxlint\'s `eslint/no-label-var` rule (category: style). No Label Var.',
  },
  {
    id: 'style.no-labels',
    group: 'style',
    title: 'no-labels',
    description: 'Generated from oxlint\'s `eslint/no-labels` rule (category: style). No Labels.',
  },
  {
    id: 'style.no-lone-blocks',
    group: 'style',
    title: 'no-lone-blocks',
    description: 'Generated from oxlint\'s `eslint/no-lone-blocks` rule (category: style). No Lone Blocks.',
  },
  {
    id: 'style.no-magic-numbers',
    group: 'style',
    title: 'no-magic-numbers',
    description: 'Generated from oxlint\'s `eslint/no-magic-numbers` rule (category: style). No Magic Numbers.',
  },
  {
    id: 'style.no-mixed-requires',
    group: 'style',
    title: 'node/no-mixed-requires',
    description: 'Generated from oxlint\'s `node/no-mixed-requires` rule (category: style). No Mixed Requires.',
  },
  {
    id: 'style.no-multi-assign',
    group: 'style',
    title: 'no-multi-assign',
    description: 'Generated from oxlint\'s `eslint/no-multi-assign` rule (category: style). No Multi Assign.',
  },
  {
    id: 'style.no-named-default',
    group: 'style',
    title: 'import/no-named-default',
    description: 'Generated from oxlint\'s `import/no-named-default` rule (category: style). No Named Default.',
  },
  {
    id: 'style.no-named-export',
    group: 'style',
    title: 'import/no-named-export',
    description: 'Generated from oxlint\'s `import/no-named-export` rule (category: style). No Named Export.',
  },
  {
    id: 'style.no-namespace',
    group: 'style',
    title: 'import/no-namespace',
    description: 'Generated from oxlint\'s `import/no-namespace` rule (category: style). No Namespace.',
  },
  {
    id: 'style.no-nesting',
    group: 'style',
    title: 'promise/no-nesting',
    description: 'Generated from oxlint\'s `promise/no-nesting` rule (category: style). No Nesting.',
  },
  {
    id: 'style.no-nodejs-modules',
    group: 'style',
    title: 'import/no-nodejs-modules',
    description: 'Generated from oxlint\'s `import/no-nodejs-modules` rule (category: style). No Nodejs Modules.',
  },
  {
    id: 'style.no-null',
    group: 'style',
    title: 'unicorn/no-null',
    description: 'Generated from oxlint\'s `unicorn/no-null` rule (category: style). No Null.',
  },
  {
    id: 'style.no-redundant-should-component-update',
    group: 'style',
    title: 'react/no-redundant-should-component-update',
    description: 'Generated from oxlint\'s `react/no-redundant-should-component-update` rule (category: style). No Redundant Should Component Update.',
  },
  {
    id: 'style.no-restricted-jest-methods',
    group: 'style',
    title: 'jest/no-restricted-jest-methods',
    description: 'Generated from oxlint\'s `jest/no-restricted-jest-methods` rule (category: style). No Restricted Jest Methods.',
  },
  {
    id: 'style.no-restricted-vi-methods',
    group: 'style',
    title: 'vitest/no-restricted-vi-methods',
    description: 'Generated from oxlint\'s `vitest/no-restricted-vi-methods` rule (category: style). No Restricted Vi Methods.',
  },
  {
    id: 'style.no-set-state',
    group: 'style',
    title: 'react/no-set-state',
    description: 'Generated from oxlint\'s `react/no-set-state` rule (category: style). No Set State.',
  },
  {
    id: 'style.no-sync',
    group: 'style',
    title: 'node/no-sync',
    description: 'Generated from oxlint\'s `node/no-sync` rule (category: style). No Sync.',
  },
  {
    id: 'style.no-template-curly-in-string',
    group: 'style',
    title: 'no-template-curly-in-string',
    description: 'Generated from oxlint\'s `eslint/no-template-curly-in-string` rule (category: style). No Template Curly In String.',
  },
  {
    id: 'style.no-ternary',
    group: 'style',
    title: 'no-ternary',
    description: 'Generated from oxlint\'s `eslint/no-ternary` rule (category: style). No Ternary.',
  },
  {
    id: 'style.no-unnecessary-qualifier',
    group: 'style',
    title: 'typescript/no-unnecessary-qualifier',
    description: 'Generated from oxlint\'s `typescript/no-unnecessary-qualifier` rule (category: style). No Unnecessary Qualifier.',
  },
  {
    id: 'style.no-useless-collection-argument',
    group: 'style',
    title: 'unicorn/no-useless-collection-argument',
    description: 'Generated from oxlint\'s `unicorn/no-useless-collection-argument` rule (category: style). No Useless Collection Argument.',
  },
  {
    id: 'style.no-useless-computed-key',
    group: 'style',
    title: 'no-useless-computed-key',
    description: 'Generated from oxlint\'s `eslint/no-useless-computed-key` rule (category: style). No Useless Computed Key.',
  },
  {
    id: 'style.number-literal-case',
    group: 'style',
    title: 'unicorn/number-literal-case',
    description: 'Generated from oxlint\'s `unicorn/number-literal-case` rule (category: style). Number Literal Case.',
  },
  {
    id: 'style.numeric-separators-style',
    group: 'style',
    title: 'unicorn/numeric-separators-style',
    description: 'Generated from oxlint\'s `unicorn/numeric-separators-style` rule (category: style). Numeric Separators Style.',
  },
  {
    id: 'style.object-shorthand',
    group: 'style',
    title: 'object-shorthand',
    description: 'Generated from oxlint\'s `eslint/object-shorthand` rule (category: style). Object Shorthand.',
  },
  {
    id: 'style.param-names',
    group: 'style',
    title: 'promise/param-names',
    description: 'Generated from oxlint\'s `promise/param-names` rule (category: style). Param Names.',
  },
  {
    id: 'style.parameter-properties',
    group: 'style',
    title: 'typescript/parameter-properties',
    description: 'Generated from oxlint\'s `typescript/parameter-properties` rule (category: style). Parameter Properties.',
  },
  {
    id: 'style.prefer-await-to-callbacks',
    group: 'style',
    title: 'promise/prefer-await-to-callbacks',
    description: 'Generated from oxlint\'s `promise/prefer-await-to-callbacks` rule (category: style). Prefer Await To Callbacks.',
  },
  {
    id: 'style.prefer-await-to-then',
    group: 'style',
    title: 'promise/prefer-await-to-then',
    description: 'Generated from oxlint\'s `promise/prefer-await-to-then` rule (category: style). Prefer Await To Then.',
  },
  {
    id: 'style.prefer-called-exactly-once-with',
    group: 'style',
    title: 'vitest/prefer-called-exactly-once-with',
    description: 'Generated from oxlint\'s `vitest/prefer-called-exactly-once-with` rule (category: style). Prefer Called Exactly Once With.',
  },
  {
    id: 'style.prefer-called-once',
    group: 'style',
    title: 'vitest/prefer-called-once',
    description: 'Generated from oxlint\'s `vitest/prefer-called-once` rule (category: style). Prefer Called Once.',
  },
  {
    id: 'style.prefer-called-times',
    group: 'style',
    title: 'vitest/prefer-called-times',
    description: 'Generated from oxlint\'s `vitest/prefer-called-times` rule (category: style). Prefer Called Times.',
  },
  {
    id: 'style.prefer-catch',
    group: 'style',
    title: 'promise/prefer-catch',
    description: 'Generated from oxlint\'s `promise/prefer-catch` rule (category: style). Prefer Catch.',
  },
  {
    id: 'style.prefer-default-export',
    group: 'style',
    title: 'import/prefer-default-export',
    description: 'Generated from oxlint\'s `import/prefer-default-export` rule (category: style). Prefer Default Export.',
  },
  {
    id: 'style.prefer-describe-function-title',
    group: 'style',
    title: 'vitest/prefer-describe-function-title',
    description: 'Generated from oxlint\'s `vitest/prefer-describe-function-title` rule (category: style). Prefer Describe Function Title.',
  },
  {
    id: 'style.prefer-destructuring',
    group: 'style',
    title: 'prefer-destructuring',
    description: 'Generated from oxlint\'s `eslint/prefer-destructuring` rule (category: style). Prefer Destructuring.',
  },
  {
    id: 'style.prefer-ending-with-an-expect',
    group: 'style',
    title: 'jest/prefer-ending-with-an-expect',
    description: 'Generated from oxlint\'s `jest/prefer-ending-with-an-expect` rule (category: style). Prefer Ending With An Expect.',
  },
  {
    id: 'style.prefer-es6-class',
    group: 'style',
    title: 'react/prefer-es6-class',
    description: 'Generated from oxlint\'s `react/prefer-es6-class` rule (category: style). Prefer Es6 Class.',
  },
  {
    id: 'style.prefer-expect-type-of',
    group: 'style',
    title: 'vitest/prefer-expect-type-of',
    description: 'Generated from oxlint\'s `vitest/prefer-expect-type-of` rule (category: style). Prefer Expect Type Of.',
  },
  {
    id: 'style.prefer-export-from',
    group: 'style',
    title: 'unicorn/prefer-export-from',
    description: 'Generated from oxlint\'s `unicorn/prefer-export-from` rule (category: style). Prefer Export From.',
  },
  {
    id: 'style.prefer-find',
    group: 'style',
    title: 'typescript/prefer-find',
    description: 'Generated from oxlint\'s `typescript/prefer-find` rule (category: style). Prefer Find.',
  },
  {
    id: 'style.prefer-import-in-mock',
    group: 'style',
    title: 'vitest/prefer-import-in-mock',
    description: 'Generated from oxlint\'s `vitest/prefer-import-in-mock` rule (category: style). Prefer Import In Mock.',
  },
  {
    id: 'style.prefer-importing-jest-globals',
    group: 'style',
    title: 'jest/prefer-importing-jest-globals',
    description: 'Generated from oxlint\'s `jest/prefer-importing-jest-globals` rule (category: style). Prefer Importing Jest Globals.',
  },
  {
    id: 'style.prefer-importing-vitest-globals',
    group: 'style',
    title: 'vitest/prefer-importing-vitest-globals',
    description: 'Generated from oxlint\'s `vitest/prefer-importing-vitest-globals` rule (category: style). Prefer Importing Vitest Globals.',
  },
  {
    id: 'style.prefer-jest-mocked',
    group: 'style',
    title: 'jest/prefer-jest-mocked',
    description: 'Generated from oxlint\'s `jest/prefer-jest-mocked` rule (category: style). Prefer Jest Mocked.',
  },
  {
    id: 'style.prefer-named-capture-group',
    group: 'style',
    title: 'prefer-named-capture-group',
    description: 'Generated from oxlint\'s `eslint/prefer-named-capture-group` rule (category: style). Prefer Named Capture Group.',
  },
  {
    id: 'style.prefer-negative-index',
    group: 'style',
    title: 'unicorn/prefer-negative-index',
    description: 'Generated from oxlint\'s `unicorn/prefer-negative-index` rule (category: style). Prefer Negative Index.',
  },
  {
    id: 'style.prefer-optional-catch-binding',
    group: 'style',
    title: 'unicorn/prefer-optional-catch-binding',
    description: 'Generated from oxlint\'s `unicorn/prefer-optional-catch-binding` rule (category: style). Prefer Optional Catch Binding.',
  },
  {
    id: 'style.prefer-readonly',
    group: 'style',
    title: 'typescript/prefer-readonly',
    description: 'Generated from oxlint\'s `typescript/prefer-readonly` rule (category: style). Prefer Readonly.',
  },
  {
    id: 'style.prefer-reduce-type-parameter',
    group: 'style',
    title: 'typescript/prefer-reduce-type-parameter',
    description: 'Generated from oxlint\'s `typescript/prefer-reduce-type-parameter` rule (category: style). Prefer Reduce Type Parameter.',
  },
  {
    id: 'style.prefer-regexp-exec',
    group: 'style',
    title: 'typescript/prefer-regexp-exec',
    description: 'Generated from oxlint\'s `typescript/prefer-regexp-exec` rule (category: style). Prefer Regexp Exec.',
  },
  {
    id: 'style.prefer-return-this-type',
    group: 'style',
    title: 'typescript/prefer-return-this-type',
    description: 'Generated from oxlint\'s `typescript/prefer-return-this-type` rule (category: style). Prefer Return This Type.',
  },
  {
    id: 'style.prefer-strict-boolean-matchers',
    group: 'style',
    title: 'vitest/prefer-strict-boolean-matchers',
    description: 'Generated from oxlint\'s `vitest/prefer-strict-boolean-matchers` rule (category: style). Prefer Strict Boolean Matchers.',
  },
  {
    id: 'style.prefer-string-raw',
    group: 'style',
    title: 'unicorn/prefer-string-raw',
    description: 'Generated from oxlint\'s `unicorn/prefer-string-raw` rule (category: style). Prefer String Raw.',
  },
  {
    id: 'style.prefer-string-starts-ends-with',
    group: 'style',
    title: 'typescript/prefer-string-starts-ends-with',
    description: 'Generated from oxlint\'s `typescript/prefer-string-starts-ends-with` rule (category: style). Prefer String Starts Ends With.',
  },
  {
    id: 'style.prefer-structured-clone',
    group: 'style',
    title: 'unicorn/prefer-structured-clone',
    description: 'Generated from oxlint\'s `unicorn/prefer-structured-clone` rule (category: style). Prefer Structured Clone.',
  },
  {
    id: 'style.prefer-template',
    group: 'style',
    title: 'prefer-template',
    description: 'Generated from oxlint\'s `eslint/prefer-template` rule (category: style). Prefer Template.',
  },
  {
    id: 'style.prefer-ternary',
    group: 'style',
    title: 'unicorn/prefer-ternary',
    description: 'Generated from oxlint\'s `unicorn/prefer-ternary` rule (category: style). Prefer Ternary.',
  },
  {
    id: 'style.prefer-to-be-falsy',
    group: 'style',
    title: 'vitest/prefer-to-be-falsy',
    description: 'Generated from oxlint\'s `vitest/prefer-to-be-falsy` rule (category: style). Prefer To Be Falsy.',
  },
  {
    id: 'style.prefer-to-be-object',
    group: 'style',
    title: 'vitest/prefer-to-be-object',
    description: 'Generated from oxlint\'s `vitest/prefer-to-be-object` rule (category: style). Prefer To Be Object.',
  },
  {
    id: 'style.prefer-to-be-truthy',
    group: 'style',
    title: 'vitest/prefer-to-be-truthy',
    description: 'Generated from oxlint\'s `vitest/prefer-to-be-truthy` rule (category: style). Prefer To Be Truthy.',
  },
  {
    id: 'style.prefer-to-have-been-called',
    group: 'style',
    title: 'jest/prefer-to-have-been-called',
    description: 'Generated from oxlint\'s `jest/prefer-to-have-been-called` rule (category: style). Prefer To Have Been Called.',
  },
  {
    id: 'style.prop-name-casing',
    group: 'style',
    title: 'vue/prop-name-casing',
    description: 'Generated from oxlint\'s `vue/prop-name-casing` rule (category: style). Prop Name Casing.',
  },
  {
    id: 'style.relative-url-style',
    group: 'style',
    title: 'unicorn/relative-url-style',
    description: 'Generated from oxlint\'s `unicorn/relative-url-style` rule (category: style). Relative Url Style.',
  },
  {
    id: 'style.require-default-prop',
    group: 'style',
    title: 'vue/require-default-prop',
    description: 'Generated from oxlint\'s `vue/require-default-prop` rule (category: style). Require Default Prop.',
  },
  {
    id: 'style.require-direct-export',
    group: 'style',
    title: 'vue/require-direct-export',
    description: 'Generated from oxlint\'s `vue/require-direct-export` rule (category: style). Require Direct Export.',
  },
  {
    id: 'style.require-module-attributes',
    group: 'style',
    title: 'unicorn/require-module-attributes',
    description: 'Generated from oxlint\'s `unicorn/require-module-attributes` rule (category: style). Require Module Attributes.',
  },
  {
    id: 'style.require-prop-types',
    group: 'style',
    title: 'vue/require-prop-types',
    description: 'Generated from oxlint\'s `vue/require-prop-types` rule (category: style). Require Prop Types.',
  },
  {
    id: 'style.require-throws-description',
    group: 'style',
    title: 'jsdoc/require-throws-description',
    description: 'Generated from oxlint\'s `jsdoc/require-throws-description` rule (category: style). Require Throws Description.',
  },
  {
    id: 'style.require-typed-ref',
    group: 'style',
    title: 'vue/require-typed-ref',
    description: 'Generated from oxlint\'s `vue/require-typed-ref` rule (category: style). Require Typed Ref.',
  },
  {
    id: 'style.require-yields-description',
    group: 'style',
    title: 'jsdoc/require-yields-description',
    description: 'Generated from oxlint\'s `jsdoc/require-yields-description` rule (category: style). Require Yields Description.',
  },
  {
    id: 'style.self-closing-comp',
    group: 'style',
    title: 'react/self-closing-comp',
    description: 'Generated from oxlint\'s `react/self-closing-comp` rule (category: style). Self Closing Comp.',
  },
  {
    id: 'style.sort-imports',
    group: 'style',
    title: 'sort-imports',
    description: 'Generated from oxlint\'s `eslint/sort-imports` rule (category: style). Sort Imports.',
  },
  {
    id: 'style.sort-keys',
    group: 'style',
    title: 'sort-keys',
    description: 'Generated from oxlint\'s `eslint/sort-keys` rule (category: style). Sort Keys.',
  },
  {
    id: 'style.state-in-constructor',
    group: 'style',
    title: 'react/state-in-constructor',
    description: 'Generated from oxlint\'s `react/state-in-constructor` rule (category: style). State In Constructor.',
  },
  {
    id: 'style.switch-case-braces',
    group: 'style',
    title: 'unicorn/switch-case-braces',
    description: 'Generated from oxlint\'s `unicorn/switch-case-braces` rule (category: style). Switch Case Braces.',
  },
  {
    id: 'style.switch-case-break-position',
    group: 'style',
    title: 'unicorn/switch-case-break-position',
    description: 'Generated from oxlint\'s `unicorn/switch-case-break-position` rule (category: style). Switch Case Break Position.',
  },
  {
    id: 'style.unicorn-no-nested-ternary',
    group: 'style',
    title: 'unicorn/no-nested-ternary',
    description: 'Generated from oxlint\'s `unicorn/no-nested-ternary` rule (category: style). No Nested Ternary.',
  },
  {
    id: 'style.unicorn-prefer-spread',
    group: 'style',
    title: 'unicorn/prefer-spread',
    description: 'Generated from oxlint\'s `unicorn/prefer-spread` rule (category: style). Prefer Spread.',
  },
  {
    id: 'style.vars-on-top',
    group: 'style',
    title: 'vars-on-top',
    description: 'Generated from oxlint\'s `eslint/vars-on-top` rule (category: style). Vars On Top.',
  },
  {
    id: 'style.vitest-consistent-test-it',
    group: 'style',
    title: 'vitest/consistent-test-it',
    description: 'Generated from oxlint\'s `vitest/consistent-test-it` rule (category: style). Consistent Test It.',
  },
  {
    id: 'style.vitest-max-expects',
    group: 'style',
    title: 'vitest/max-expects',
    description: 'Generated from oxlint\'s `vitest/max-expects` rule (category: style). Max Expects.',
  },
  {
    id: 'style.vitest-max-nested-describe',
    group: 'style',
    title: 'vitest/max-nested-describe',
    description: 'Generated from oxlint\'s `vitest/max-nested-describe` rule (category: style). Max Nested Describe.',
  },
  {
    id: 'style.vitest-no-hooks',
    group: 'style',
    title: 'vitest/no-hooks',
    description: 'Generated from oxlint\'s `vitest/no-hooks` rule (category: style). No Hooks.',
  },
  {
    id: 'style.vitest-no-interpolation-in-snapshots',
    group: 'style',
    title: 'vitest/no-interpolation-in-snapshots',
    description: 'Generated from oxlint\'s `vitest/no-interpolation-in-snapshots` rule (category: style). No Interpolation In Snapshots.',
  },
  {
    id: 'style.vitest-no-large-snapshots',
    group: 'style',
    title: 'vitest/no-large-snapshots',
    description: 'Generated from oxlint\'s `vitest/no-large-snapshots` rule (category: style). No Large Snapshots.',
  },
  {
    id: 'style.vitest-no-restricted-matchers',
    group: 'style',
    title: 'vitest/no-restricted-matchers',
    description: 'Generated from oxlint\'s `vitest/no-restricted-matchers` rule (category: style). No Restricted Matchers.',
  },
  {
    id: 'style.vitest-no-test-prefixes',
    group: 'style',
    title: 'vitest/no-test-prefixes',
    description: 'Generated from oxlint\'s `vitest/no-test-prefixes` rule (category: style). No Test Prefixes.',
  },
  {
    id: 'style.vitest-no-unneeded-async-expect-function',
    group: 'style',
    title: 'vitest/no-unneeded-async-expect-function',
    description: 'Generated from oxlint\'s `vitest/no-unneeded-async-expect-function` rule (category: style). No Unneeded Async Expect Function.',
  },
  {
    id: 'style.vitest-padding-around-after-all-blocks',
    group: 'style',
    title: 'vitest/padding-around-after-all-blocks',
    description: 'Generated from oxlint\'s `vitest/padding-around-after-all-blocks` rule (category: style). Padding Around After All Blocks.',
  },
  {
    id: 'style.vitest-padding-around-test-blocks',
    group: 'style',
    title: 'vitest/padding-around-test-blocks',
    description: 'Generated from oxlint\'s `vitest/padding-around-test-blocks` rule (category: style). Padding Around Test Blocks.',
  },
  {
    id: 'style.vitest-prefer-called-with',
    group: 'style',
    title: 'vitest/prefer-called-with',
    description: 'Generated from oxlint\'s `vitest/prefer-called-with` rule (category: style). Prefer Called With.',
  },
  {
    id: 'style.vitest-prefer-comparison-matcher',
    group: 'style',
    title: 'vitest/prefer-comparison-matcher',
    description: 'Generated from oxlint\'s `vitest/prefer-comparison-matcher` rule (category: style). Prefer Comparison Matcher.',
  },
  {
    id: 'style.vitest-prefer-each',
    group: 'style',
    title: 'vitest/prefer-each',
    description: 'Generated from oxlint\'s `vitest/prefer-each` rule (category: style). Prefer Each.',
  },
  {
    id: 'style.vitest-prefer-equality-matcher',
    group: 'style',
    title: 'vitest/prefer-equality-matcher',
    description: 'Generated from oxlint\'s `vitest/prefer-equality-matcher` rule (category: style). Prefer Equality Matcher.',
  },
  {
    id: 'style.vitest-prefer-expect-assertions',
    group: 'style',
    title: 'vitest/prefer-expect-assertions',
    description: 'Generated from oxlint\'s `vitest/prefer-expect-assertions` rule (category: style). Prefer Expect Assertions.',
  },
  {
    id: 'style.vitest-prefer-expect-resolves',
    group: 'style',
    title: 'vitest/prefer-expect-resolves',
    description: 'Generated from oxlint\'s `vitest/prefer-expect-resolves` rule (category: style). Prefer Expect Resolves.',
  },
  {
    id: 'style.vitest-prefer-hooks-in-order',
    group: 'style',
    title: 'vitest/prefer-hooks-in-order',
    description: 'Generated from oxlint\'s `vitest/prefer-hooks-in-order` rule (category: style). Prefer Hooks In Order.',
  },
  {
    id: 'style.vitest-prefer-hooks-on-top',
    group: 'style',
    title: 'vitest/prefer-hooks-on-top',
    description: 'Generated from oxlint\'s `vitest/prefer-hooks-on-top` rule (category: style). Prefer Hooks On Top.',
  },
  {
    id: 'style.vitest-prefer-lowercase-title',
    group: 'style',
    title: 'vitest/prefer-lowercase-title',
    description: 'Generated from oxlint\'s `vitest/prefer-lowercase-title` rule (category: style). Prefer Lowercase Title.',
  },
  {
    id: 'style.vitest-prefer-mock-promise-shorthand',
    group: 'style',
    title: 'vitest/prefer-mock-promise-shorthand',
    description: 'Generated from oxlint\'s `vitest/prefer-mock-promise-shorthand` rule (category: style). Prefer Mock Promise Shorthand.',
  },
  {
    id: 'style.vitest-prefer-mock-return-shorthand',
    group: 'style',
    title: 'vitest/prefer-mock-return-shorthand',
    description: 'Generated from oxlint\'s `vitest/prefer-mock-return-shorthand` rule (category: style). Prefer Mock Return Shorthand.',
  },
  {
    id: 'style.vitest-prefer-spy-on',
    group: 'style',
    title: 'vitest/prefer-spy-on',
    description: 'Generated from oxlint\'s `vitest/prefer-spy-on` rule (category: style). Prefer Spy On.',
  },
  {
    id: 'style.vitest-prefer-strict-equal',
    group: 'style',
    title: 'vitest/prefer-strict-equal',
    description: 'Generated from oxlint\'s `vitest/prefer-strict-equal` rule (category: style). Prefer Strict Equal.',
  },
  {
    id: 'style.vitest-prefer-to-be',
    group: 'style',
    title: 'vitest/prefer-to-be',
    description: 'Generated from oxlint\'s `vitest/prefer-to-be` rule (category: style). Prefer To Be.',
  },
  {
    id: 'style.vitest-prefer-to-contain',
    group: 'style',
    title: 'vitest/prefer-to-contain',
    description: 'Generated from oxlint\'s `vitest/prefer-to-contain` rule (category: style). Prefer To Contain.',
  },
  {
    id: 'style.vitest-prefer-to-have-been-called-times',
    group: 'style',
    title: 'vitest/prefer-to-have-been-called-times',
    description: 'Generated from oxlint\'s `vitest/prefer-to-have-been-called-times` rule (category: style). Prefer To Have Been Called Times.',
  },
  {
    id: 'style.vitest-prefer-to-have-length',
    group: 'style',
    title: 'vitest/prefer-to-have-length',
    description: 'Generated from oxlint\'s `vitest/prefer-to-have-length` rule (category: style). Prefer To Have Length.',
  },
  {
    id: 'style.vitest-prefer-todo',
    group: 'style',
    title: 'vitest/prefer-todo',
    description: 'Generated from oxlint\'s `vitest/prefer-todo` rule (category: style). Prefer Todo.',
  },
  {
    id: 'style.vitest-require-hook',
    group: 'style',
    title: 'vitest/require-hook',
    description: 'Generated from oxlint\'s `vitest/require-hook` rule (category: style). Require Hook.',
  },
  {
    id: 'style.vitest-require-top-level-describe',
    group: 'style',
    title: 'vitest/require-top-level-describe',
    description: 'Generated from oxlint\'s `vitest/require-top-level-describe` rule (category: style). Require Top Level Describe.',
  },
  {
    id: 'style.yoda',
    group: 'style',
    title: 'yoda',
    description: 'Generated from oxlint\'s `eslint/yoda` rule (category: style). Yoda.',
  },
  {
    id: 'suspicious.consistent-return',
    group: 'suspicious',
    title: 'typescript/consistent-return',
    description: 'Generated from oxlint\'s `typescript/consistent-return` rule (category: suspicious). Consistent Return.',
  },
  {
    id: 'suspicious.no-array-reverse',
    group: 'suspicious',
    title: 'unicorn/no-array-reverse',
    description: 'Generated from oxlint\'s `unicorn/no-array-reverse` rule (category: suspicious). No Array Reverse.',
  },
  {
    id: 'suspicious.no-array-sort',
    group: 'suspicious',
    title: 'unicorn/no-array-sort',
    description: 'Generated from oxlint\'s `unicorn/no-array-sort` rule (category: suspicious). No Array Sort.',
  },
  {
    id: 'suspicious.no-implied-eval',
    group: 'suspicious',
    title: 'no-implied-eval',
    description: 'Generated from oxlint\'s `eslint/no-implied-eval` rule (category: suspicious). No Implied Eval.',
  },
  {
    id: 'suspicious.no-unassigned-import',
    group: 'suspicious',
    title: 'import/no-unassigned-import',
    description: 'Generated from oxlint\'s `import/no-unassigned-import` rule (category: suspicious). No Unassigned Import.',
  },
  {
    id: 'suspicious.no-underscore-dangle',
    group: 'suspicious',
    title: 'no-underscore-dangle',
    description: 'Generated from oxlint\'s `eslint/no-underscore-dangle` rule (category: suspicious). No Underscore Dangle.',
  },
  {
    id: 'suspicious.no-unnecessary-type-parameters',
    group: 'suspicious',
    title: 'typescript/no-unnecessary-type-parameters',
    description: 'Generated from oxlint\'s `typescript/no-unnecessary-type-parameters` rule (category: suspicious). No Unnecessary Type Parameters.',
  },
  {
    id: 'suspicious.no-unsafe-type-assertion',
    group: 'suspicious',
    title: 'typescript/no-unsafe-type-assertion',
    description: 'Generated from oxlint\'s `typescript/no-unsafe-type-assertion` rule (category: suspicious). No Unsafe Type Assertion.',
  },
] as const satisfies readonly ConceptDefinition[]
